/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[12] = 
  {0, 1, 2, 3, 4, 5, 6, 12,
  18, 24, 30, 36};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s7[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s8[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s10[60] = 
  {15, 15, 0, 1, 2, 3, 4, 5,
  6, 12, 18, 24, 30, 36, 42, 42,
  42, 42, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 6, 7,
  8, 9, 10, 11, 6, 7, 8, 9,
  10, 11, 6, 7, 8, 9, 10, 11,
  6, 7, 8, 9, 10, 11, 6, 7,
  8, 9, 10, 11};
static const casadi_int casadi_s11[3] = {15, 1, 1};
static const casadi_int casadi_s12[3] = {0, 1, 1};
static const casadi_int casadi_s13[3] = {51, 1, 1};
static const casadi_int casadi_s14[3] = {1, 1, 1};
static const casadi_int casadi_s15[3] = {0, 0, 1};
static const casadi_int casadi_s16[3] = {0, 15, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* planner_payload_jerk_cost_ext_cost_e_fun_jac_hess:(i0[15],i1[0],i2[0],i3[51])->(o0,o1[15],o2[15x15,42nz],o3[],o4[0x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w20=w+56, *w21=w+59, *w22=w+62, *w23=w+65;
  casadi_real *w24=w+68, *w25=w+71, *w26=w+74, *w27=w+83, *w28=w+92, *w29=w+95, *w30=w+98, *w31=w+107, *w32=w+110, *w33=w+113, *w34=w+116, *w36=w+122;
  casadi_real *w37=w+125, w38, w39, w40, w41, *w42=w+144, *w43=w+186, *w44=w+196, *w46=w+205, w47, w48, *w49=w+209;
  casadi_real *w50=w+221, *w51=w+227;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr19, *wr20, *wr22, *wr26, *wr31, *wr35;
  /* #0: @0 = 5000 */
  w00 = 5000.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = input[3][0] */
  wr19 = arg[3] ? arg[3] : casadi_zeros;
  /* #20: @20 = @19[:3] */
  wr20 = wr19+0;
  /* #21: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=wr20; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #23: @2 = mac(@20,@18,@1) */
  casadi_copy((&w01), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #24: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #25: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #26: @21 = @17[3:6] */
  for (rr=w21, cs=w17+3; cs!=w17+6; cs+=1) *rr++ = *cs;
  /* #27: @22 = @19[3:6] */
  wr22 = wr19+3;
  /* #28: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #29: @22 = @21' */
  casadi_copy(w21, 3, w22);
  /* #30: @4 = mac(@22,@21,@1) */
  casadi_copy((&w01), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #31: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #32: @2 = (@2+@4) */
  w02 += w04;
  /* #33: @4 = @19[7] */
  w04 = wr19[7];
  /* #34: @5 = (@4*@10) */
  w05  = (w04*w10);
  /* #35: @6 = @19[8] */
  w06 = wr19[8];
  /* #36: @7 = (@6*@9) */
  w07  = (w06*w09);
  /* #37: @5 = (@5-@7) */
  w05 -= w07;
  /* #38: @7 = (@6*@8) */
  w07  = (w06*w08);
  /* #39: @11 = @19[6] */
  w11 = wr19[6];
  /* #40: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #41: @7 = (@7-@10) */
  w07 -= w10;
  /* #42: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #43: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #44: @9 = (@9-@8) */
  w09 -= w08;
  /* #45: @23 = vertcat(@5, @7, @9) */
  rr=w23;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  /* #46: @24 = @23' */
  casadi_copy(w23, 3, w24);
  /* #47: @5 = mac(@24,@23,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@5) */
  w02 += w05;
  /* #49: @24 = @17[9:12] */
  for (rr=w24, cs=w17+9; cs!=w17+12; cs+=1) *rr++ = *cs;
  /* #50: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #51: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr26 = casadi_c0;
  /* #52: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #53: @28 = @17[6:9] */
  for (rr=w28, cs=w17+6; cs!=w17+9; cs+=1) *rr++ = *cs;
  /* #54: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #55: @30 = mac(@28,@29,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #56: @26 = (@26-@30) */
  for (i=0, rr=w26, cr=wr26, cs=w30; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #57: @31 = @19[9:12] */
  wr31 = wr19+9;
  /* #58: @32 = mac(@26,@31,@25) */
  casadi_copy(w25, 3, w32);
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #59: @32 = (@24-@32) */
  for (i=0, rr=w32, cr=w24, cs=w32; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #60: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #61: @1 = mac(@33,@32,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@1) */
  w02 += w01;
  /* #63: @1 = dot(@28, @24) */
  w01 = casadi_dot(3, w28, w24);
  /* #64: @5 = sq(@1) */
  w05 = casadi_sq( w01 );
  /* #65: @2 = (@2+@5) */
  w02 += w05;
  /* #66: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #67: @17 = zeros(15x1) */
  casadi_clear(w17, 15);
  /* #68: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #69: @33 = (@1*@24) */
  for (i=0, rr=w33, cs=w24; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #70: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #71: @34 = (-@32) */
  for (i=0, rr=w34, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #72: @35 = @31' */
  wr35 = wr31;
  /* #73: @26 = mac(@34,@35,@27) */
  casadi_copy(w27, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w34+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #74: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #75: @34 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #76: @33 = (@33+@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #77: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #78: @36 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #79: @36 = @36' */
  /* #80: @33 = (@33+@36) */
  for (i=0, rr=w33, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #81: @37 = @17; (@37[6:9] += @33) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w33; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #82: @33 = (@1*@28) */
  for (i=0, rr=w33, cs=w28; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #83: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #84: (@37[9:12] += @33) */
  for (rr=w37+9, cs=w33; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #85: @21 = (@3*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #86: @22 = (@3*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #87: @22 = @22' */
  /* #88: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #89: (@37[3:6] += @21) */
  for (rr=w37+3, cs=w21; rr!=w37+6; rr+=1) *rr += *cs++;
  /* #90: @18 = (@0*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #91: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #92: @20 = @20' */
  /* #93: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #94: (@37[:3] += @18) */
  for (rr=w37+0, cs=w18; rr!=w37+3; rr+=1) *rr += *cs++;
  /* #95: {@2, @5, @7, @9, @8, @10, @12, @13, @14, @15, @16, @38, @39, @40, @41} = vertsplit(@37) */
  w02 = w37[0];
  w05 = w37[1];
  w07 = w37[2];
  w09 = w37[3];
  w08 = w37[4];
  w10 = w37[5];
  w12 = w37[6];
  w13 = w37[7];
  w14 = w37[8];
  w15 = w37[9];
  w16 = w37[10];
  w38 = w37[11];
  w39 = w37[12];
  w40 = w37[13];
  w41 = w37[14];
  /* #96: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #97: output[1][1] = @5 */
  if (res[1]) res[1][1] = w05;
  /* #98: output[1][2] = @7 */
  if (res[1]) res[1][2] = w07;
  /* #99: output[1][3] = @9 */
  if (res[1]) res[1][3] = w09;
  /* #100: output[1][4] = @8 */
  if (res[1]) res[1][4] = w08;
  /* #101: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #102: @23 = (2.*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #103: {@10, @8, @9} = vertsplit(@23) */
  w10 = w23[0];
  w08 = w23[1];
  w09 = w23[2];
  /* #104: @7 = (@6*@8) */
  w07  = (w06*w08);
  /* #105: @5 = (@4*@9) */
  w05  = (w04*w09);
  /* #106: @7 = (@7-@5) */
  w07 -= w05;
  /* #107: @7 = (@7+@12) */
  w07 += w12;
  /* #108: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #109: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #110: @7 = (@6*@10) */
  w07  = (w06*w10);
  /* #111: @9 = (@9-@7) */
  w09 -= w07;
  /* #112: @9 = (@9+@13) */
  w09 += w13;
  /* #113: output[1][7] = @9 */
  if (res[1]) res[1][7] = w09;
  /* #114: @10 = (@4*@10) */
  w10  = (w04*w10);
  /* #115: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #116: @10 = (@10-@8) */
  w10 -= w08;
  /* #117: @10 = (@10+@14) */
  w10 += w14;
  /* #118: output[1][8] = @10 */
  if (res[1]) res[1][8] = w10;
  /* #119: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #120: output[1][10] = @16 */
  if (res[1]) res[1][10] = w16;
  /* #121: output[1][11] = @38 */
  if (res[1]) res[1][11] = w38;
  /* #122: output[1][12] = @39 */
  if (res[1]) res[1][12] = w39;
  /* #123: output[1][13] = @40 */
  if (res[1]) res[1][13] = w40;
  /* #124: output[1][14] = @41 */
  if (res[1]) res[1][14] = w41;
  /* #125: @42 = zeros(15x15,42nz) */
  casadi_clear(w42, 42);
  /* #126: @43 = ones(15x1,10nz) */
  casadi_fill(w43, 10, 1.);
  /* #127: {@41, @40, @39, @38, @16, @15, @10, NULL, NULL, NULL, NULL, NULL, @14, @8, @9} = vertsplit(@43) */
  w41 = w43[0];
  w40 = w43[1];
  w39 = w43[2];
  w38 = w43[3];
  w16 = w43[4];
  w15 = w43[5];
  w10 = w43[6];
  w14 = w43[7];
  w08 = w43[8];
  w09 = w43[9];
  /* #128: @13 = sparsity_cast(@10) */
  w13 = w10;
  /* #129: @7 = project(@24) */
  casadi_sparsify(w24, (&w07), casadi_s0, 0);
  /* #130: @12 = dot(@13, @7) */
  w12 = casadi_dot(1, (&w13), (&w07));
  /* #131: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #132: @23 = (@24*@12) */
  for (i=0, rr=w23, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #133: @18 = mac(@26,@13,@25) */
  casadi_copy(w25, 3, w18);
  casadi_mtimes(w26, casadi_s2, (&w13), casadi_s0, w18, casadi_s1, w, 0);
  /* #134: @7 = @13' */
  w07 = w13;
  /* #135: @30 = mac(@28,@7,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w07), casadi_s3, w30, casadi_s2, w, 0);
  /* #136: @44 = mac(@13,@29,@27) */
  casadi_copy(w27, 9, w44);
  casadi_mtimes((&w13), casadi_s0, w29, casadi_s4, w44, casadi_s2, w, 0);
  /* #137: @30 = (@30+@44) */
  for (i=0, rr=w30, cs=w44; i<9; ++i) (*rr++) += (*cs++);
  /* #138: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #139: @20 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #140: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #141: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #142: @21 = (-@20) */
  for (i=0, rr=w21, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #143: @30 = mac(@21,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #144: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #145: @21 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #146: @18 = (@18+@21) */
  for (i=0, rr=w18, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #147: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #148: @18 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w18);
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #149: @21 = mac(@7,@26,@34) */
  casadi_copy(w34, 3, w21);
  casadi_mtimes((&w07), casadi_s3, w26, casadi_s2, w21, casadi_s4, w, 0);
  /* #150: @18 = (@18+@21) */
  for (i=0, rr=w18, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #151: @18 = @18' */
  /* #152: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #153: @37 = @17; (@37[6:9] += @23) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w23; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #154: @23 = (@28*@12) */
  for (i=0, rr=w23, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #155: @13 = (@1*@13) */
  w13  = (w01*w13);
  /* #156: @18 = dense(@13) */
  casadi_densify((&w13), casadi_s0, w18, 0);
  /* #157: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #158: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #159: (@37[9:12] += @23) */
  for (rr=w37+9, cs=w23; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #160: @45 = 00 */
  /* #161: @43 = vertcat(@41, @40, @39, @38, @16, @15, @10, @45, @45, @45, @45, @45, @14, @8, @9) */
  rr=w43;
  *rr++ = w41;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w38;
  *rr++ = w16;
  *rr++ = w15;
  *rr++ = w10;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w09;
  /* #162: @23 = @43[3:6] */
  for (rr=w23, cs=w43+3; cs!=w43+6; cs+=1) *rr++ = *cs;
  /* #163: @20 = (@3*@23) */
  for (i=0, rr=w20, cs=w23; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #164: @23 = @23' */
  /* #165: @23 = (@3*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #166: @23 = @23' */
  /* #167: @20 = (@20+@23) */
  for (i=0, rr=w20, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #168: (@37[3:6] += @20) */
  for (rr=w37+3, cs=w20; rr!=w37+6; rr+=1) *rr += *cs++;
  /* #169: @20 = @43[:3] */
  for (rr=w20, cs=w43+0; cs!=w43+3; cs+=1) *rr++ = *cs;
  /* #170: @23 = (@0*@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #171: @20 = @20' */
  /* #172: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #173: @20 = @20' */
  /* #174: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #175: (@37[:3] += @23) */
  for (rr=w37+0, cs=w23; rr!=w37+3; rr+=1) *rr += *cs++;
  /* #176: {@0, @3, @41, @40, @39, @38, @16, @15, @14, @8, @9, @13, @12, @7, @5} = vertsplit(@37) */
  w00 = w37[0];
  w03 = w37[1];
  w41 = w37[2];
  w40 = w37[3];
  w39 = w37[4];
  w38 = w37[5];
  w16 = w37[6];
  w15 = w37[7];
  w14 = w37[8];
  w08 = w37[9];
  w09 = w37[10];
  w13 = w37[11];
  w12 = w37[12];
  w07 = w37[13];
  w05 = w37[14];
  /* #177: @2 = (@6*@10) */
  w02  = (w06*w10);
  /* #178: @10 = (@4*@10) */
  w10  = (w04*w10);
  /* #179: @10 = (-@10) */
  w10 = (- w10 );
  /* #180: @46 = vertcat(@45, @2, @10) */
  rr=w46;
  *rr++ = w02;
  *rr++ = w10;
  /* #181: @46 = (2.*@46) */
  for (i=0, rr=w46, cs=w46; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #182: {NULL, @2, @10} = vertsplit(@46) */
  w02 = w46[0];
  w10 = w46[1];
  /* #183: @47 = (@6*@2) */
  w47  = (w06*w02);
  /* #184: @48 = (@4*@10) */
  w48  = (w04*w10);
  /* #185: @47 = (@47-@48) */
  w47 -= w48;
  /* #186: @47 = (@47+@16) */
  w47 += w16;
  /* #187: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #188: @10 = (@10+@15) */
  w10 += w15;
  /* #189: @2 = (@11*@2) */
  w02  = (w11*w02);
  /* #190: @14 = (@14-@2) */
  w14 -= w02;
  /* #191: @37 = vertcat(@0, @3, @41, @40, @39, @38, @47, @10, @14, @8, @9, @13, @12, @7, @5) */
  rr=w37;
  *rr++ = w00;
  *rr++ = w03;
  *rr++ = w41;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w38;
  *rr++ = w47;
  *rr++ = w10;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w05;
  /* #192: @49 = @37[:12] */
  for (rr=w49, cs=w37+0; cs!=w37+12; cs+=1) *rr++ = *cs;
  /* #193: (@42[:12] = @49) */
  for (rr=w42+0, cs=w49; rr!=w42+12; rr+=1) *rr = *cs++;
  /* #194: (@42[0, 1, 2, 3, 4, 5, 6, 12, 18, 24, 30, 36] = @49) */
  for (cii=casadi_s5, rr=w42, cs=w49; cii!=casadi_s5+12; ++cii, ++cs) rr[*cii] = *cs;
  /* #195: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #196: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @3, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w03 = w00;
  /* #197: @0 = sparsity_cast(@3) */
  w00 = w03;
  /* #198: @41 = project(@24) */
  casadi_sparsify(w24, (&w41), casadi_s6, 0);
  /* #199: @40 = dot(@0, @41) */
  w40 = casadi_dot(1, (&w00), (&w41));
  /* #200: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #201: @23 = (@24*@40) */
  for (i=0, rr=w23, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #202: @20 = mac(@26,@0,@25) */
  casadi_copy(w25, 3, w20);
  casadi_mtimes(w26, casadi_s2, (&w00), casadi_s6, w20, casadi_s1, w, 0);
  /* #203: @41 = @0' */
  w41 = w00;
  /* #204: @30 = mac(@28,@41,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s7, w30, casadi_s2, w, 0);
  /* #205: @44 = mac(@0,@29,@27) */
  casadi_copy(w27, 9, w44);
  casadi_mtimes((&w00), casadi_s6, w29, casadi_s4, w44, casadi_s2, w, 0);
  /* #206: @30 = (@30+@44) */
  for (i=0, rr=w30, cs=w44; i<9; ++i) (*rr++) += (*cs++);
  /* #207: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #208: @18 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #209: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #210: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #211: @21 = (-@18) */
  for (i=0, rr=w21, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #212: @30 = mac(@21,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #213: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #214: @21 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #215: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #216: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #217: @20 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #218: @21 = mac(@41,@26,@34) */
  casadi_copy(w34, 3, w21);
  casadi_mtimes((&w41), casadi_s7, w26, casadi_s2, w21, casadi_s4, w, 0);
  /* #219: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #220: @20 = @20' */
  /* #221: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #222: @37 = @17; (@37[6:9] += @23) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w23; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #223: @23 = (@28*@40) */
  for (i=0, rr=w23, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #224: @0 = (@1*@0) */
  w00  = (w01*w00);
  /* #225: @20 = dense(@0) */
  casadi_densify((&w00), casadi_s6, w20, 0);
  /* #226: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #227: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #228: (@37[9:12] += @23) */
  for (rr=w37+9, cs=w23; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #229: {@0, @40, @41, @39, @38, @47, @10, @14, @8, @9, @13, @12, @7, @5, @2} = vertsplit(@37) */
  w00 = w37[0];
  w40 = w37[1];
  w41 = w37[2];
  w39 = w37[3];
  w38 = w37[4];
  w47 = w37[5];
  w10 = w37[6];
  w14 = w37[7];
  w08 = w37[8];
  w09 = w37[9];
  w13 = w37[10];
  w12 = w37[11];
  w07 = w37[12];
  w05 = w37[13];
  w02 = w37[14];
  /* #230: @15 = (@6*@3) */
  w15  = (w06*w03);
  /* #231: @15 = (-@15) */
  w15 = (- w15 );
  /* #232: @3 = (@11*@3) */
  w03  = (w11*w03);
  /* #233: @46 = vertcat(@15, @45, @3) */
  rr=w46;
  *rr++ = w15;
  *rr++ = w03;
  /* #234: @46 = (2.*@46) */
  for (i=0, rr=w46, cs=w46; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #235: {@15, NULL, @3} = vertsplit(@46) */
  w15 = w46[0];
  w03 = w46[1];
  /* #236: @16 = (@4*@3) */
  w16  = (w04*w03);
  /* #237: @10 = (@10-@16) */
  w10 -= w16;
  /* #238: @3 = (@11*@3) */
  w03  = (w11*w03);
  /* #239: @16 = (@6*@15) */
  w16  = (w06*w15);
  /* #240: @3 = (@3-@16) */
  w03 -= w16;
  /* #241: @3 = (@3+@14) */
  w03 += w14;
  /* #242: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #243: @15 = (@15+@8) */
  w15 += w08;
  /* #244: @37 = vertcat(@0, @40, @41, @39, @38, @47, @10, @3, @15, @9, @13, @12, @7, @5, @2) */
  rr=w37;
  *rr++ = w00;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w39;
  *rr++ = w38;
  *rr++ = w47;
  *rr++ = w10;
  *rr++ = w03;
  *rr++ = w15;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w02;
  /* #245: @50 = @37[6:12] */
  for (rr=w50, cs=w37+6; cs!=w37+12; cs+=1) *rr++ = *cs;
  /* #246: (@42[12:18] = @50) */
  for (rr=w42+12, cs=w50; rr!=w42+18; rr+=1) *rr = *cs++;
  /* #247: (@42[7:43:6] = @50) */
  for (rr=w42+7, cs=w50; rr!=w42+43; rr+=6) *rr = *cs++;
  /* #248: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #249: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @40, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w40 = w00;
  /* #250: @0 = sparsity_cast(@40) */
  w00 = w40;
  /* #251: @41 = project(@24) */
  casadi_sparsify(w24, (&w41), casadi_s8, 0);
  /* #252: @39 = dot(@0, @41) */
  w39 = casadi_dot(1, (&w00), (&w41));
  /* #253: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #254: @23 = (@24*@39) */
  for (i=0, rr=w23, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #255: @18 = mac(@26,@0,@25) */
  casadi_copy(w25, 3, w18);
  casadi_mtimes(w26, casadi_s2, (&w00), casadi_s8, w18, casadi_s1, w, 0);
  /* #256: @41 = @0' */
  w41 = w00;
  /* #257: @30 = mac(@28,@41,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s9, w30, casadi_s2, w, 0);
  /* #258: @44 = mac(@0,@29,@27) */
  casadi_copy(w27, 9, w44);
  casadi_mtimes((&w00), casadi_s8, w29, casadi_s4, w44, casadi_s2, w, 0);
  /* #259: @30 = (@30+@44) */
  for (i=0, rr=w30, cs=w44; i<9; ++i) (*rr++) += (*cs++);
  /* #260: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #261: @20 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #262: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #263: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #264: @31 = (-@20) */
  for (i=0, rr=w31, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #265: @30 = mac(@31,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #266: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #267: @31 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w31);
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #268: @18 = (@18+@31) */
  for (i=0, rr=w18, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #269: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #270: @18 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w18);
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #271: @31 = mac(@41,@26,@34) */
  casadi_copy(w34, 3, w31);
  casadi_mtimes((&w41), casadi_s9, w26, casadi_s2, w31, casadi_s4, w, 0);
  /* #272: @18 = (@18+@31) */
  for (i=0, rr=w18, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #273: @18 = @18' */
  /* #274: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #275: @37 = @17; (@37[6:9] += @23) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w23; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #276: @23 = (@28*@39) */
  for (i=0, rr=w23, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #277: @0 = (@1*@0) */
  w00  = (w01*w00);
  /* #278: @18 = dense(@0) */
  casadi_densify((&w00), casadi_s8, w18, 0);
  /* #279: @23 = (@23+@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #280: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #281: (@37[9:12] += @23) */
  for (rr=w37+9, cs=w23; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #282: {@0, @39, @41, @38, @47, @10, @3, @15, @9, @13, @12, @7, @5, @2, @8} = vertsplit(@37) */
  w00 = w37[0];
  w39 = w37[1];
  w41 = w37[2];
  w38 = w37[3];
  w47 = w37[4];
  w10 = w37[5];
  w03 = w37[6];
  w15 = w37[7];
  w09 = w37[8];
  w13 = w37[9];
  w12 = w37[10];
  w07 = w37[11];
  w05 = w37[12];
  w02 = w37[13];
  w08 = w37[14];
  /* #283: @14 = (@4*@40) */
  w14  = (w04*w40);
  /* #284: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #285: @40 = (-@40) */
  w40 = (- w40 );
  /* #286: @46 = vertcat(@14, @40, @45) */
  rr=w46;
  *rr++ = w14;
  *rr++ = w40;
  /* #287: @46 = (2.*@46) */
  for (i=0, rr=w46, cs=w46; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #288: {@14, @40, NULL} = vertsplit(@46) */
  w14 = w46[0];
  w40 = w46[1];
  /* #289: @16 = (@6*@40) */
  w16  = (w06*w40);
  /* #290: @16 = (@16+@3) */
  w16 += w03;
  /* #291: @6 = (@6*@14) */
  w06 *= w14;
  /* #292: @15 = (@15-@6) */
  w15 -= w06;
  /* #293: @4 = (@4*@14) */
  w04 *= w14;
  /* #294: @11 = (@11*@40) */
  w11 *= w40;
  /* #295: @4 = (@4-@11) */
  w04 -= w11;
  /* #296: @4 = (@4+@9) */
  w04 += w09;
  /* #297: @37 = vertcat(@0, @39, @41, @38, @47, @10, @16, @15, @4, @13, @12, @7, @5, @2, @8) */
  rr=w37;
  *rr++ = w00;
  *rr++ = w39;
  *rr++ = w41;
  *rr++ = w38;
  *rr++ = w47;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w15;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w08;
  /* #298: @50 = @37[6:12] */
  for (rr=w50, cs=w37+6; cs!=w37+12; cs+=1) *rr++ = *cs;
  /* #299: (@42[18:24] = @50) */
  for (rr=w42+18, cs=w50; rr!=w42+24; rr+=1) *rr = *cs++;
  /* #300: (@42[8:44:6] = @50) */
  for (rr=w42+8, cs=w50; rr!=w42+44; rr+=6) *rr = *cs++;
  /* #301: @0 = project(@28) */
  casadi_sparsify(w28, (&w00), casadi_s0, 0);
  /* #302: @39 = ones(15x1,1nz) */
  w39 = 1.;
  /* #303: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL, NULL, NULL} = vertsplit(@39) */
  w41 = w39;
  /* #304: @41 = sparsity_cast(@41) */
  /* #305: @39 = dot(@0, @41) */
  w39 = casadi_dot(1, (&w00), (&w41));
  /* #306: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #307: @23 = (@24*@39) */
  for (i=0, rr=w23, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #308: @0 = (@1*@41) */
  w00  = (w01*w41);
  /* #309: @20 = dense(@0) */
  casadi_densify((&w00), casadi_s0, w20, 0);
  /* #310: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #311: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #312: @0 = (-@41) */
  w00 = (- w41 );
  /* #313: @26 = mac(@0,@35,@27) */
  casadi_copy(w27, 9, w26);
  casadi_mtimes((&w00), casadi_s0, wr35, casadi_s4, w26, casadi_s2, w, 0);
  /* #314: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #315: @20 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #316: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #317: @20 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #318: @20 = @20' */
  /* #319: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #320: @37 = @17; (@37[6:9] += @23) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w23; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #321: @23 = (@28*@39) */
  for (i=0, rr=w23, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #322: @20 = dense(@41) */
  casadi_densify((&w41), casadi_s0, w20, 0);
  /* #323: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #324: (@37[9:12] += @23) */
  for (rr=w37+9, cs=w23; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #325: @50 = @37[6:12] */
  for (rr=w50, cs=w37+6; cs!=w37+12; cs+=1) *rr++ = *cs;
  /* #326: (@42[24:30] = @50) */
  for (rr=w42+24, cs=w50; rr!=w42+30; rr+=1) *rr = *cs++;
  /* #327: (@42[9:45:6] = @50) */
  for (rr=w42+9, cs=w50; rr!=w42+45; rr+=6) *rr = *cs++;
  /* #328: @41 = project(@28) */
  casadi_sparsify(w28, (&w41), casadi_s6, 0);
  /* #329: @39 = ones(15x1,1nz) */
  w39 = 1.;
  /* #330: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL} = vertsplit(@39) */
  w00 = w39;
  /* #331: @0 = sparsity_cast(@0) */
  /* #332: @39 = dot(@41, @0) */
  w39 = casadi_dot(1, (&w41), (&w00));
  /* #333: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #334: @23 = (@24*@39) */
  for (i=0, rr=w23, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #335: @41 = (@1*@0) */
  w41  = (w01*w00);
  /* #336: @20 = dense(@41) */
  casadi_densify((&w41), casadi_s6, w20, 0);
  /* #337: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #338: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #339: @41 = (-@0) */
  w41 = (- w00 );
  /* #340: @26 = mac(@41,@35,@27) */
  casadi_copy(w27, 9, w26);
  casadi_mtimes((&w41), casadi_s6, wr35, casadi_s4, w26, casadi_s2, w, 0);
  /* #341: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #342: @20 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #343: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #344: @20 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #345: @20 = @20' */
  /* #346: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #347: @37 = @17; (@37[6:9] += @23) */
  casadi_copy(w17, 15, w37);
  for (rr=w37+6, cs=w23; rr!=w37+9; rr+=1) *rr += *cs++;
  /* #348: @23 = (@28*@39) */
  for (i=0, rr=w23, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #349: @20 = dense(@0) */
  casadi_densify((&w00), casadi_s6, w20, 0);
  /* #350: @23 = (@23+@20) */
  for (i=0, rr=w23, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #351: (@37[9:12] += @23) */
  for (rr=w37+9, cs=w23; rr!=w37+12; rr+=1) *rr += *cs++;
  /* #352: @50 = @37[6:12] */
  for (rr=w50, cs=w37+6; cs!=w37+12; cs+=1) *rr++ = *cs;
  /* #353: (@42[30:36] = @50) */
  for (rr=w42+30, cs=w50; rr!=w42+36; rr+=1) *rr = *cs++;
  /* #354: (@42[10:46:6] = @50) */
  for (rr=w42+10, cs=w50; rr!=w42+46; rr+=6) *rr = *cs++;
  /* #355: @0 = project(@28) */
  casadi_sparsify(w28, (&w00), casadi_s8, 0);
  /* #356: @39 = ones(15x1,1nz) */
  w39 = 1.;
  /* #357: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL} = vertsplit(@39) */
  w41 = w39;
  /* #358: @41 = sparsity_cast(@41) */
  /* #359: @39 = dot(@0, @41) */
  w39 = casadi_dot(1, (&w00), (&w41));
  /* #360: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #361: @24 = (@24*@39) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w39;
  /* #362: @1 = (@1*@41) */
  w01 *= w41;
  /* #363: @23 = dense(@1) */
  casadi_densify((&w01), casadi_s8, w23, 0);
  /* #364: @24 = (@24+@23) */
  for (i=0, rr=w24, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #365: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #366: @1 = (-@41) */
  w01 = (- w41 );
  /* #367: @27 = mac(@1,@35,@27) */
  casadi_mtimes((&w01), casadi_s8, wr35, casadi_s4, w27, casadi_s2, w, 0);
  /* #368: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<9; ++i) *rr++ = (- *cs++ );
  /* #369: @25 = mac(@27,@28,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #370: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #371: @34 = mac(@29,@27,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #372: @34 = @34' */
  /* #373: @24 = (@24+@34) */
  for (i=0, rr=w24, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #374: (@17[6:9] += @24) */
  for (rr=w17+6, cs=w24; rr!=w17+9; rr+=1) *rr += *cs++;
  /* #375: @28 = (@28*@39) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) *= w39;
  /* #376: @24 = dense(@41) */
  casadi_densify((&w41), casadi_s8, w24, 0);
  /* #377: @28 = (@28+@24) */
  for (i=0, rr=w28, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #378: (@17[9:12] += @28) */
  for (rr=w17+9, cs=w28; rr!=w17+12; rr+=1) *rr += *cs++;
  /* #379: @50 = @17[6:12] */
  for (rr=w50, cs=w17+6; cs!=w17+12; cs+=1) *rr++ = *cs;
  /* #380: (@42[36:42] = @50) */
  for (rr=w42+36, cs=w50; rr!=w42+42; rr+=1) *rr = *cs++;
  /* #381: (@42[11:47:6] = @50) */
  for (rr=w42+11, cs=w50; rr!=w42+47; rr+=6) *rr = *cs++;
  /* #382: @51 = @42' */
  casadi_trans(w42,casadi_s10, w51, casadi_s10, iw);
  /* #383: output[2][0] = @51 */
  casadi_copy(w51, 42, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s11;
    case 2: return casadi_s10;
    case 3: return casadi_s15;
    case 4: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 269;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 20*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 269*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
