/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_jerk_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[18] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 45,
  46, 47};
static const casadi_int casadi_s6[18] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 15, 21, 27, 33, 39, 45,
  46, 47};
static const casadi_int casadi_s7[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s10[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s11[69] = 
  {18, 18, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 15, 21, 27, 33,
  39, 45, 46, 47, 48, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 12, 13, 14, 9, 10, 11, 12,
  13, 14, 9, 10, 11, 12, 13, 14,
  9, 10, 11, 12, 13, 14, 9, 10,
  11, 12, 13, 14, 9, 10, 11, 12,
  13, 14, 15, 16, 17};
static const casadi_int casadi_s12[3] = {15, 1, 1};
static const casadi_int casadi_s13[3] = {3, 1, 1};
static const casadi_int casadi_s14[3] = {0, 1, 1};
static const casadi_int casadi_s15[3] = {51, 1, 1};
static const casadi_int casadi_s16[3] = {1, 1, 1};
static const casadi_int casadi_s17[3] = {18, 1, 1};
static const casadi_int casadi_s18[3] = {0, 0, 1};
static const casadi_int casadi_s19[3] = {0, 18, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* planner_payload_jerk_cost_ext_cost_fun_jac_hess:(i0[15],i1[3],i2[0],i3[51])->(o0,o1[18],o2[18x18,48nz],o3[],o4[0x18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+56, *w21=w+59, *w22=w+62;
  casadi_real *w23=w+65, *w24=w+68, *w25=w+71, *w26=w+74, *w27=w+83, *w28=w+92, *w29=w+95, *w30=w+98, *w31=w+107, *w32=w+110, *w33=w+113, *w34=w+116;
  casadi_real *w35=w+119, *w36=w+122, *w37=w+137, w38, w39, w40, w41, w42, *w43=w+145, *w44=w+193, *w46=w+206, *w47=w+216;
  casadi_real w48, w49, *w50=w+227, w51, w52, *w53=w+231, *w54=w+237;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr19, *wr20, *wr22, *wr26, *wr31, *wr33, *wr35;
  /* #0: @0 = 5000 */
  w00 = 5000.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = input[3][0] */
  wr19 = arg[3] ? arg[3] : casadi_zeros;
  /* #20: @20 = @19[:3] */
  wr20 = wr19+0;
  /* #21: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=wr20; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #23: @2 = mac(@20,@18,@1) */
  casadi_copy((&w01), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #24: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #25: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #26: @21 = @17[3:6] */
  for (rr=w21, cs=w17+3; cs!=w17+6; cs+=1) *rr++ = *cs;
  /* #27: @22 = @19[3:6] */
  wr22 = wr19+3;
  /* #28: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #29: @22 = @21' */
  casadi_copy(w21, 3, w22);
  /* #30: @4 = mac(@22,@21,@1) */
  casadi_copy((&w01), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #31: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #32: @2 = (@2+@4) */
  w02 += w04;
  /* #33: @4 = @19[7] */
  w04 = wr19[7];
  /* #34: @5 = (@4*@10) */
  w05  = (w04*w10);
  /* #35: @6 = @19[8] */
  w06 = wr19[8];
  /* #36: @7 = (@6*@9) */
  w07  = (w06*w09);
  /* #37: @5 = (@5-@7) */
  w05 -= w07;
  /* #38: @7 = (@6*@8) */
  w07  = (w06*w08);
  /* #39: @11 = @19[6] */
  w11 = wr19[6];
  /* #40: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #41: @7 = (@7-@10) */
  w07 -= w10;
  /* #42: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #43: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #44: @9 = (@9-@8) */
  w09 -= w08;
  /* #45: @23 = vertcat(@5, @7, @9) */
  rr=w23;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  /* #46: @24 = @23' */
  casadi_copy(w23, 3, w24);
  /* #47: @5 = mac(@24,@23,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@5) */
  w02 += w05;
  /* #49: @24 = @17[9:12] */
  for (rr=w24, cs=w17+9; cs!=w17+12; cs+=1) *rr++ = *cs;
  /* #50: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #51: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr26 = casadi_c0;
  /* #52: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #53: @28 = @17[6:9] */
  for (rr=w28, cs=w17+6; cs!=w17+9; cs+=1) *rr++ = *cs;
  /* #54: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #55: @30 = mac(@28,@29,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #56: @26 = (@26-@30) */
  for (i=0, rr=w26, cr=wr26, cs=w30; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #57: @31 = @19[9:12] */
  wr31 = wr19+9;
  /* #58: @32 = mac(@26,@31,@25) */
  casadi_copy(w25, 3, w32);
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #59: @32 = (@24-@32) */
  for (i=0, rr=w32, cr=w24, cs=w32; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #60: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #61: @5 = mac(@33,@32,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@5) */
  w02 += w05;
  /* #63: @33 = @19[12:15] */
  wr33 = wr19+12;
  /* #64: @34 = @17[12:15] */
  for (rr=w34, cs=w17+12; cs!=w17+15; cs+=1) *rr++ = *cs;
  /* #65: @33 = (@33-@34) */
  for (i=0, rr=w33, cr=wr33, cs=w34; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #66: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #67: @5 = mac(@34,@33,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #68: @2 = (@2+@5) */
  w02 += w05;
  /* #69: @5 = 0.1 */
  w05 = 1.0000000000000001e-01;
  /* #70: @7 = input[1][0] */
  w07 = arg[1] ? arg[1][0] : 0;
  /* #71: @9 = input[1][1] */
  w09 = arg[1] ? arg[1][1] : 0;
  /* #72: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #73: @34 = vertcat(@7, @9, @8) */
  rr=w34;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w08;
  /* #74: @35 = @34' */
  casadi_copy(w34, 3, w35);
  /* #75: @1 = mac(@35,@34,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #76: @1 = (@5*@1) */
  w01  = (w05*w01);
  /* #77: @2 = (@2+@1) */
  w02 += w01;
  /* #78: @1 = dot(@28, @24) */
  w01 = casadi_dot(3, w28, w24);
  /* #79: @7 = sq(@1) */
  w07 = casadi_sq( w01 );
  /* #80: @2 = (@2+@7) */
  w02 += w07;
  /* #81: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #82: @34 = (@5*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #83: @35 = (@5*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #84: @35 = @35' */
  /* #85: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #86: {@2, @7, @9} = vertsplit(@34) */
  w02 = w34[0];
  w07 = w34[1];
  w09 = w34[2];
  /* #87: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #88: output[1][1] = @7 */
  if (res[1]) res[1][1] = w07;
  /* #89: output[1][2] = @9 */
  if (res[1]) res[1][2] = w09;
  /* #90: @17 = zeros(15x1) */
  casadi_clear(w17, 15);
  /* #91: @33 = (2.*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #92: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #93: @36 = @17; (@36[12:15] += @33) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+12, cs=w33; rr!=w36+15; rr+=1) *rr += *cs++;
  /* #94: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #95: @33 = (@1*@24) */
  for (i=0, rr=w33, cs=w24; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #96: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: @34 = (-@32) */
  for (i=0, rr=w34, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #98: @35 = @31' */
  wr35 = wr31;
  /* #99: @26 = mac(@34,@35,@27) */
  casadi_copy(w27, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w34+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #101: @34 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #102: @33 = (@33+@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #103: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #104: @37 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #105: @37 = @37' */
  /* #106: @33 = (@33+@37) */
  for (i=0, rr=w33, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #107: (@36[6:9] += @33) */
  for (rr=w36+6, cs=w33; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #108: @33 = (@1*@28) */
  for (i=0, rr=w33, cs=w28; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #109: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #110: (@36[9:12] += @33) */
  for (rr=w36+9, cs=w33; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #111: @21 = (@3*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #112: @22 = (@3*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #113: @22 = @22' */
  /* #114: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #115: (@36[3:6] += @21) */
  for (rr=w36+3, cs=w21; rr!=w36+6; rr+=1) *rr += *cs++;
  /* #116: @18 = (@0*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #117: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #118: @20 = @20' */
  /* #119: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #120: (@36[:3] += @18) */
  for (rr=w36+0, cs=w18; rr!=w36+3; rr+=1) *rr += *cs++;
  /* #121: {@9, @7, @2, @8, @10, @12, @13, @14, @15, @16, @38, @39, @40, @41, @42} = vertsplit(@36) */
  w09 = w36[0];
  w07 = w36[1];
  w02 = w36[2];
  w08 = w36[3];
  w10 = w36[4];
  w12 = w36[5];
  w13 = w36[6];
  w14 = w36[7];
  w15 = w36[8];
  w16 = w36[9];
  w38 = w36[10];
  w39 = w36[11];
  w40 = w36[12];
  w41 = w36[13];
  w42 = w36[14];
  /* #122: output[1][3] = @9 */
  if (res[1]) res[1][3] = w09;
  /* #123: output[1][4] = @7 */
  if (res[1]) res[1][4] = w07;
  /* #124: output[1][5] = @2 */
  if (res[1]) res[1][5] = w02;
  /* #125: output[1][6] = @8 */
  if (res[1]) res[1][6] = w08;
  /* #126: output[1][7] = @10 */
  if (res[1]) res[1][7] = w10;
  /* #127: output[1][8] = @12 */
  if (res[1]) res[1][8] = w12;
  /* #128: @23 = (2.*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #129: {@12, @10, @8} = vertsplit(@23) */
  w12 = w23[0];
  w10 = w23[1];
  w08 = w23[2];
  /* #130: @2 = (@6*@10) */
  w02  = (w06*w10);
  /* #131: @7 = (@4*@8) */
  w07  = (w04*w08);
  /* #132: @2 = (@2-@7) */
  w02 -= w07;
  /* #133: @2 = (@2+@13) */
  w02 += w13;
  /* #134: output[1][9] = @2 */
  if (res[1]) res[1][9] = w02;
  /* #135: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #136: @2 = (@6*@12) */
  w02  = (w06*w12);
  /* #137: @8 = (@8-@2) */
  w08 -= w02;
  /* #138: @8 = (@8+@14) */
  w08 += w14;
  /* #139: output[1][10] = @8 */
  if (res[1]) res[1][10] = w08;
  /* #140: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #141: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #142: @12 = (@12-@10) */
  w12 -= w10;
  /* #143: @12 = (@12+@15) */
  w12 += w15;
  /* #144: output[1][11] = @12 */
  if (res[1]) res[1][11] = w12;
  /* #145: output[1][12] = @16 */
  if (res[1]) res[1][12] = w16;
  /* #146: output[1][13] = @38 */
  if (res[1]) res[1][13] = w38;
  /* #147: output[1][14] = @39 */
  if (res[1]) res[1][14] = w39;
  /* #148: output[1][15] = @40 */
  if (res[1]) res[1][15] = w40;
  /* #149: output[1][16] = @41 */
  if (res[1]) res[1][16] = w41;
  /* #150: output[1][17] = @42 */
  if (res[1]) res[1][17] = w42;
  /* #151: @43 = zeros(18x18,48nz) */
  casadi_clear(w43, 48);
  /* #152: @44 = ones(18x1,13nz) */
  casadi_fill(w44, 13, 1.);
  /* #153: {@42, @41, @40, @39, @38, @16, @12, @15, @10, @8, NULL, NULL, NULL, NULL, NULL, @14, @2, @13} = vertsplit(@44) */
  w42 = w44[0];
  w41 = w44[1];
  w40 = w44[2];
  w39 = w44[3];
  w38 = w44[4];
  w16 = w44[5];
  w12 = w44[6];
  w15 = w44[7];
  w10 = w44[8];
  w08 = w44[9];
  w14 = w44[10];
  w02 = w44[11];
  w13 = w44[12];
  /* #154: @23 = vertcat(@42, @41, @40) */
  rr=w23;
  *rr++ = w42;
  *rr++ = w41;
  *rr++ = w40;
  /* #155: @18 = (@5*@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #156: @23 = @23' */
  /* #157: @23 = (@5*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #158: @23 = @23' */
  /* #159: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #160: {@5, @42, @41} = vertsplit(@18) */
  w05 = w18[0];
  w42 = w18[1];
  w41 = w18[2];
  /* #161: @45 = 00 */
  /* #162: @46 = vertcat(@39, @38, @16, @12, @15, @10, @8, @45, @45, @45, @45, @45, @14, @2, @13) */
  rr=w46;
  *rr++ = w39;
  *rr++ = w38;
  *rr++ = w16;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  /* #163: @18 = @46[7:10] */
  for (rr=w18, cs=w46+7; cs!=w46+10; cs+=1) *rr++ = *cs;
  /* #164: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #165: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #166: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #167: @36 = @17; (@36[12:15] += @18) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+12, cs=w18; rr!=w36+15; rr+=1) *rr += *cs++;
  /* #168: @39 = sparsity_cast(@8) */
  w39 = w08;
  /* #169: @38 = project(@24) */
  casadi_sparsify(w24, (&w38), casadi_s0, 0);
  /* #170: @16 = dot(@39, @38) */
  w16 = casadi_dot(1, (&w39), (&w38));
  /* #171: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #172: @18 = (@24*@16) */
  for (i=0, rr=w18, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #173: @23 = mac(@26,@39,@25) */
  casadi_copy(w25, 3, w23);
  casadi_mtimes(w26, casadi_s2, (&w39), casadi_s0, w23, casadi_s1, w, 0);
  /* #174: @38 = @39' */
  w38 = w39;
  /* #175: @30 = mac(@28,@38,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w38), casadi_s3, w30, casadi_s2, w, 0);
  /* #176: @47 = mac(@39,@29,@27) */
  casadi_copy(w27, 9, w47);
  casadi_mtimes((&w39), casadi_s0, w29, casadi_s4, w47, casadi_s2, w, 0);
  /* #177: @30 = (@30+@47) */
  for (i=0, rr=w30, cs=w47; i<9; ++i) (*rr++) += (*cs++);
  /* #178: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #179: @20 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #180: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #181: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #182: @21 = (-@20) */
  for (i=0, rr=w21, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #183: @30 = mac(@21,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #184: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #185: @21 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #186: @23 = (@23+@21) */
  for (i=0, rr=w23, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #187: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #188: @23 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #189: @21 = mac(@38,@26,@34) */
  casadi_copy(w34, 3, w21);
  casadi_mtimes((&w38), casadi_s3, w26, casadi_s2, w21, casadi_s4, w, 0);
  /* #190: @23 = (@23+@21) */
  for (i=0, rr=w23, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #191: @23 = @23' */
  /* #192: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #193: (@36[6:9] += @18) */
  for (rr=w36+6, cs=w18; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #194: @18 = (@28*@16) */
  for (i=0, rr=w18, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #195: @39 = (@1*@39) */
  w39  = (w01*w39);
  /* #196: @23 = dense(@39) */
  casadi_densify((&w39), casadi_s0, w23, 0);
  /* #197: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #198: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #199: (@36[9:12] += @18) */
  for (rr=w36+9, cs=w18; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #200: @18 = @46[3:6] */
  for (rr=w18, cs=w46+3; cs!=w46+6; cs+=1) *rr++ = *cs;
  /* #201: @20 = (@3*@18) */
  for (i=0, rr=w20, cs=w18; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #202: @18 = @18' */
  /* #203: @18 = (@3*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #204: @18 = @18' */
  /* #205: @20 = (@20+@18) */
  for (i=0, rr=w20, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #206: (@36[3:6] += @20) */
  for (rr=w36+3, cs=w20; rr!=w36+6; rr+=1) *rr += *cs++;
  /* #207: @20 = @46[:3] */
  for (rr=w20, cs=w46+0; cs!=w46+3; cs+=1) *rr++ = *cs;
  /* #208: @18 = (@0*@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #209: @20 = @20' */
  /* #210: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #211: @20 = @20' */
  /* #212: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #213: (@36[:3] += @18) */
  for (rr=w36+0, cs=w18; rr!=w36+3; rr+=1) *rr += *cs++;
  /* #214: {@0, @3, @39, @16, @38, @12, @15, @10, @14, @2, @13, @40, @7, @9, @48} = vertsplit(@36) */
  w00 = w36[0];
  w03 = w36[1];
  w39 = w36[2];
  w16 = w36[3];
  w38 = w36[4];
  w12 = w36[5];
  w15 = w36[6];
  w10 = w36[7];
  w14 = w36[8];
  w02 = w36[9];
  w13 = w36[10];
  w40 = w36[11];
  w07 = w36[12];
  w09 = w36[13];
  w48 = w36[14];
  /* #215: @49 = (@6*@8) */
  w49  = (w06*w08);
  /* #216: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #217: @8 = (-@8) */
  w08 = (- w08 );
  /* #218: @50 = vertcat(@45, @49, @8) */
  rr=w50;
  *rr++ = w49;
  *rr++ = w08;
  /* #219: @50 = (2.*@50) */
  for (i=0, rr=w50, cs=w50; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #220: {NULL, @49, @8} = vertsplit(@50) */
  w49 = w50[0];
  w08 = w50[1];
  /* #221: @51 = (@6*@49) */
  w51  = (w06*w49);
  /* #222: @52 = (@4*@8) */
  w52  = (w04*w08);
  /* #223: @51 = (@51-@52) */
  w51 -= w52;
  /* #224: @51 = (@51+@15) */
  w51 += w15;
  /* #225: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #226: @8 = (@8+@10) */
  w08 += w10;
  /* #227: @49 = (@11*@49) */
  w49  = (w11*w49);
  /* #228: @14 = (@14-@49) */
  w14 -= w49;
  /* #229: @19 = vertcat(@5, @42, @41, @0, @3, @39, @16, @38, @12, @51, @8, @14, @2, @13, @40, @7, @9, @48) */
  rr=w19;
  *rr++ = w05;
  *rr++ = w42;
  *rr++ = w41;
  *rr++ = w00;
  *rr++ = w03;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w12;
  *rr++ = w51;
  *rr++ = w08;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w48;
  /* #230: (@43[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 45, 46, 47] = @19) */
  for (cii=casadi_s5, rr=w43, cs=w19; cii!=casadi_s5+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #231: (@43[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 21, 27, 33, 39, 45, 46, 47] = @19) */
  for (cii=casadi_s6, rr=w43, cs=w19; cii!=casadi_s6+18; ++cii, ++cs) rr[*cii] = *cs;
  /* #232: @5 = ones(18x1,1nz) */
  w05 = 1.;
  /* #233: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @42, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w42 = w05;
  /* #234: @5 = sparsity_cast(@42) */
  w05 = w42;
  /* #235: @41 = project(@24) */
  casadi_sparsify(w24, (&w41), casadi_s7, 0);
  /* #236: @0 = dot(@5, @41) */
  w00 = casadi_dot(1, (&w05), (&w41));
  /* #237: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #238: @18 = (@24*@0) */
  for (i=0, rr=w18, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w00);
  /* #239: @20 = mac(@26,@5,@25) */
  casadi_copy(w25, 3, w20);
  casadi_mtimes(w26, casadi_s2, (&w05), casadi_s7, w20, casadi_s1, w, 0);
  /* #240: @41 = @5' */
  w41 = w05;
  /* #241: @30 = mac(@28,@41,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s8, w30, casadi_s2, w, 0);
  /* #242: @47 = mac(@5,@29,@27) */
  casadi_copy(w27, 9, w47);
  casadi_mtimes((&w05), casadi_s7, w29, casadi_s4, w47, casadi_s2, w, 0);
  /* #243: @30 = (@30+@47) */
  for (i=0, rr=w30, cs=w47; i<9; ++i) (*rr++) += (*cs++);
  /* #244: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #245: @23 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #246: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #247: @23 = (2.*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #248: @21 = (-@23) */
  for (i=0, rr=w21, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #249: @30 = mac(@21,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #250: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #251: @21 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #252: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #253: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #254: @20 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #255: @21 = mac(@41,@26,@34) */
  casadi_copy(w34, 3, w21);
  casadi_mtimes((&w41), casadi_s8, w26, casadi_s2, w21, casadi_s4, w, 0);
  /* #256: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #257: @20 = @20' */
  /* #258: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #259: @36 = @17; (@36[6:9] += @18) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+6, cs=w18; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #260: @18 = (@28*@0) */
  for (i=0, rr=w18, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w00);
  /* #261: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #262: @20 = dense(@5) */
  casadi_densify((&w05), casadi_s7, w20, 0);
  /* #263: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #264: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #265: (@36[9:12] += @18) */
  for (rr=w36+9, cs=w18; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #266: {@5, @0, @41, @3, @39, @16, @38, @12, @51, @8, @14, @2, @13, @40, @7} = vertsplit(@36) */
  w05 = w36[0];
  w00 = w36[1];
  w41 = w36[2];
  w03 = w36[3];
  w39 = w36[4];
  w16 = w36[5];
  w38 = w36[6];
  w12 = w36[7];
  w51 = w36[8];
  w08 = w36[9];
  w14 = w36[10];
  w02 = w36[11];
  w13 = w36[12];
  w40 = w36[13];
  w07 = w36[14];
  /* #267: @9 = (@6*@42) */
  w09  = (w06*w42);
  /* #268: @9 = (-@9) */
  w09 = (- w09 );
  /* #269: @42 = (@11*@42) */
  w42  = (w11*w42);
  /* #270: @50 = vertcat(@9, @45, @42) */
  rr=w50;
  *rr++ = w09;
  *rr++ = w42;
  /* #271: @50 = (2.*@50) */
  for (i=0, rr=w50, cs=w50; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #272: {@9, NULL, @42} = vertsplit(@50) */
  w09 = w50[0];
  w42 = w50[1];
  /* #273: @48 = (@4*@42) */
  w48  = (w04*w42);
  /* #274: @38 = (@38-@48) */
  w38 -= w48;
  /* #275: @42 = (@11*@42) */
  w42  = (w11*w42);
  /* #276: @48 = (@6*@9) */
  w48  = (w06*w09);
  /* #277: @42 = (@42-@48) */
  w42 -= w48;
  /* #278: @42 = (@42+@12) */
  w42 += w12;
  /* #279: @9 = (@4*@9) */
  w09  = (w04*w09);
  /* #280: @9 = (@9+@51) */
  w09 += w51;
  /* #281: @36 = vertcat(@45, @45, @45, @5, @0, @41, @3, @39, @16, @38, @42, @9, @8, @14, @2, @13, @40, @7) */
  rr=w36;
  *rr++ = w05;
  *rr++ = w00;
  *rr++ = w41;
  *rr++ = w03;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w42;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  /* #282: @53 = @36[6:12] */
  for (rr=w53, cs=w36+6; cs!=w36+12; cs+=1) *rr++ = *cs;
  /* #283: (@43[15:21] = @53) */
  for (rr=w43+15, cs=w53; rr!=w43+21; rr+=1) *rr = *cs++;
  /* #284: (@43[10:46:6] = @53) */
  for (rr=w43+10, cs=w53; rr!=w43+46; rr+=6) *rr = *cs++;
  /* #285: @5 = ones(18x1,1nz) */
  w05 = 1.;
  /* #286: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w00 = w05;
  /* #287: @5 = sparsity_cast(@0) */
  w05 = w00;
  /* #288: @41 = project(@24) */
  casadi_sparsify(w24, (&w41), casadi_s9, 0);
  /* #289: @3 = dot(@5, @41) */
  w03 = casadi_dot(1, (&w05), (&w41));
  /* #290: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #291: @18 = (@24*@3) */
  for (i=0, rr=w18, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #292: @23 = mac(@26,@5,@25) */
  casadi_copy(w25, 3, w23);
  casadi_mtimes(w26, casadi_s2, (&w05), casadi_s9, w23, casadi_s1, w, 0);
  /* #293: @41 = @5' */
  w41 = w05;
  /* #294: @30 = mac(@28,@41,@27) */
  casadi_copy(w27, 9, w30);
  casadi_mtimes(w28, casadi_s1, (&w41), casadi_s10, w30, casadi_s2, w, 0);
  /* #295: @47 = mac(@5,@29,@27) */
  casadi_copy(w27, 9, w47);
  casadi_mtimes((&w05), casadi_s9, w29, casadi_s4, w47, casadi_s2, w, 0);
  /* #296: @30 = (@30+@47) */
  for (i=0, rr=w30, cs=w47; i<9; ++i) (*rr++) += (*cs++);
  /* #297: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #298: @20 = mac(@30,@31,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #299: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #300: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #301: @31 = (-@20) */
  for (i=0, rr=w31, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #302: @30 = mac(@31,@35,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=wr35+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #303: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (- *cs++ );
  /* #304: @31 = mac(@30,@28,@25) */
  casadi_copy(w25, 3, w31);
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #305: @23 = (@23+@31) */
  for (i=0, rr=w23, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #306: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #307: @23 = mac(@29,@30,@34) */
  casadi_copy(w34, 3, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #308: @31 = mac(@41,@26,@34) */
  casadi_copy(w34, 3, w31);
  casadi_mtimes((&w41), casadi_s10, w26, casadi_s2, w31, casadi_s4, w, 0);
  /* #309: @23 = (@23+@31) */
  for (i=0, rr=w23, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #310: @23 = @23' */
  /* #311: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #312: @36 = @17; (@36[6:9] += @18) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+6, cs=w18; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #313: @18 = (@28*@3) */
  for (i=0, rr=w18, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #314: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #315: @23 = dense(@5) */
  casadi_densify((&w05), casadi_s9, w23, 0);
  /* #316: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #317: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #318: (@36[9:12] += @18) */
  for (rr=w36+9, cs=w18; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #319: {@5, @3, @41, @39, @16, @38, @42, @9, @8, @14, @2, @13, @40, @7, @51} = vertsplit(@36) */
  w05 = w36[0];
  w03 = w36[1];
  w41 = w36[2];
  w39 = w36[3];
  w16 = w36[4];
  w38 = w36[5];
  w42 = w36[6];
  w09 = w36[7];
  w08 = w36[8];
  w14 = w36[9];
  w02 = w36[10];
  w13 = w36[11];
  w40 = w36[12];
  w07 = w36[13];
  w51 = w36[14];
  /* #320: @12 = (@4*@0) */
  w12  = (w04*w00);
  /* #321: @0 = (@11*@0) */
  w00  = (w11*w00);
  /* #322: @0 = (-@0) */
  w00 = (- w00 );
  /* #323: @50 = vertcat(@12, @0, @45) */
  rr=w50;
  *rr++ = w12;
  *rr++ = w00;
  /* #324: @50 = (2.*@50) */
  for (i=0, rr=w50, cs=w50; i<2; ++i) *rr++ = (2.* *cs++ );
  /* #325: {@12, @0, NULL} = vertsplit(@50) */
  w12 = w50[0];
  w00 = w50[1];
  /* #326: @48 = (@6*@0) */
  w48  = (w06*w00);
  /* #327: @48 = (@48+@42) */
  w48 += w42;
  /* #328: @6 = (@6*@12) */
  w06 *= w12;
  /* #329: @9 = (@9-@6) */
  w09 -= w06;
  /* #330: @4 = (@4*@12) */
  w04 *= w12;
  /* #331: @11 = (@11*@0) */
  w11 *= w00;
  /* #332: @4 = (@4-@11) */
  w04 -= w11;
  /* #333: @4 = (@4+@8) */
  w04 += w08;
  /* #334: @36 = vertcat(@45, @45, @45, @5, @3, @41, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7, @51) */
  rr=w36;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w41;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w48;
  *rr++ = w09;
  *rr++ = w04;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  *rr++ = w51;
  /* #335: @53 = @36[6:12] */
  for (rr=w53, cs=w36+6; cs!=w36+12; cs+=1) *rr++ = *cs;
  /* #336: (@43[21:27] = @53) */
  for (rr=w43+21, cs=w53; rr!=w43+27; rr+=1) *rr = *cs++;
  /* #337: (@43[11:47:6] = @53) */
  for (rr=w43+11, cs=w53; rr!=w43+47; rr+=6) *rr = *cs++;
  /* #338: @5 = project(@28) */
  casadi_sparsify(w28, (&w05), casadi_s0, 0);
  /* #339: @3 = ones(18x1,1nz) */
  w03 = 1.;
  /* #340: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w41 = w03;
  /* #341: @41 = sparsity_cast(@41) */
  /* #342: @3 = dot(@5, @41) */
  w03 = casadi_dot(1, (&w05), (&w41));
  /* #343: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #344: @18 = (@24*@3) */
  for (i=0, rr=w18, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #345: @5 = (@1*@41) */
  w05  = (w01*w41);
  /* #346: @20 = dense(@5) */
  casadi_densify((&w05), casadi_s0, w20, 0);
  /* #347: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #348: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #349: @5 = (-@41) */
  w05 = (- w41 );
  /* #350: @26 = mac(@5,@35,@27) */
  casadi_copy(w27, 9, w26);
  casadi_mtimes((&w05), casadi_s0, wr35, casadi_s4, w26, casadi_s2, w, 0);
  /* #351: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #352: @20 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #353: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #354: @20 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #355: @20 = @20' */
  /* #356: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #357: @36 = @17; (@36[6:9] += @18) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+6, cs=w18; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #358: @18 = (@28*@3) */
  for (i=0, rr=w18, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #359: @20 = dense(@41) */
  casadi_densify((&w41), casadi_s0, w20, 0);
  /* #360: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #361: (@36[9:12] += @18) */
  for (rr=w36+9, cs=w18; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #362: {@41, @3, @5, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7, @51} = vertsplit(@36) */
  w41 = w36[0];
  w03 = w36[1];
  w05 = w36[2];
  w39 = w36[3];
  w16 = w36[4];
  w38 = w36[5];
  w48 = w36[6];
  w09 = w36[7];
  w04 = w36[8];
  w14 = w36[9];
  w02 = w36[10];
  w13 = w36[11];
  w40 = w36[12];
  w07 = w36[13];
  w51 = w36[14];
  /* #363: @36 = vertcat(@45, @45, @45, @41, @3, @5, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7, @51) */
  rr=w36;
  *rr++ = w41;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w48;
  *rr++ = w09;
  *rr++ = w04;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  *rr++ = w51;
  /* #364: @53 = @36[6:12] */
  for (rr=w53, cs=w36+6; cs!=w36+12; cs+=1) *rr++ = *cs;
  /* #365: (@43[27:33] = @53) */
  for (rr=w43+27, cs=w53; rr!=w43+33; rr+=1) *rr = *cs++;
  /* #366: (@43[12:48:6] = @53) */
  for (rr=w43+12, cs=w53; rr!=w43+48; rr+=6) *rr = *cs++;
  /* #367: @41 = project(@28) */
  casadi_sparsify(w28, (&w41), casadi_s7, 0);
  /* #368: @3 = ones(18x1,1nz) */
  w03 = 1.;
  /* #369: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w05 = w03;
  /* #370: @5 = sparsity_cast(@5) */
  /* #371: @3 = dot(@41, @5) */
  w03 = casadi_dot(1, (&w41), (&w05));
  /* #372: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #373: @18 = (@24*@3) */
  for (i=0, rr=w18, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #374: @41 = (@1*@5) */
  w41  = (w01*w05);
  /* #375: @20 = dense(@41) */
  casadi_densify((&w41), casadi_s7, w20, 0);
  /* #376: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #377: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #378: @41 = (-@5) */
  w41 = (- w05 );
  /* #379: @26 = mac(@41,@35,@27) */
  casadi_copy(w27, 9, w26);
  casadi_mtimes((&w41), casadi_s7, wr35, casadi_s4, w26, casadi_s2, w, 0);
  /* #380: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #381: @20 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #382: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #383: @20 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #384: @20 = @20' */
  /* #385: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #386: @36 = @17; (@36[6:9] += @18) */
  casadi_copy(w17, 15, w36);
  for (rr=w36+6, cs=w18; rr!=w36+9; rr+=1) *rr += *cs++;
  /* #387: @18 = (@28*@3) */
  for (i=0, rr=w18, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #388: @20 = dense(@5) */
  casadi_densify((&w05), casadi_s7, w20, 0);
  /* #389: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #390: (@36[9:12] += @18) */
  for (rr=w36+9, cs=w18; rr!=w36+12; rr+=1) *rr += *cs++;
  /* #391: {@5, @3, @41, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7, @51} = vertsplit(@36) */
  w05 = w36[0];
  w03 = w36[1];
  w41 = w36[2];
  w39 = w36[3];
  w16 = w36[4];
  w38 = w36[5];
  w48 = w36[6];
  w09 = w36[7];
  w04 = w36[8];
  w14 = w36[9];
  w02 = w36[10];
  w13 = w36[11];
  w40 = w36[12];
  w07 = w36[13];
  w51 = w36[14];
  /* #392: @36 = vertcat(@45, @45, @45, @5, @3, @41, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7, @51) */
  rr=w36;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w41;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w48;
  *rr++ = w09;
  *rr++ = w04;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  *rr++ = w51;
  /* #393: @53 = @36[6:12] */
  for (rr=w53, cs=w36+6; cs!=w36+12; cs+=1) *rr++ = *cs;
  /* #394: (@43[33:39] = @53) */
  for (rr=w43+33, cs=w53; rr!=w43+39; rr+=1) *rr = *cs++;
  /* #395: (@43[13:49:6] = @53) */
  for (rr=w43+13, cs=w53; rr!=w43+49; rr+=6) *rr = *cs++;
  /* #396: @5 = project(@28) */
  casadi_sparsify(w28, (&w05), casadi_s9, 0);
  /* #397: @3 = ones(18x1,1nz) */
  w03 = 1.;
  /* #398: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL} = vertsplit(@3) */
  w41 = w03;
  /* #399: @41 = sparsity_cast(@41) */
  /* #400: @3 = dot(@5, @41) */
  w03 = casadi_dot(1, (&w05), (&w41));
  /* #401: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #402: @24 = (@24*@3) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w03;
  /* #403: @1 = (@1*@41) */
  w01 *= w41;
  /* #404: @18 = dense(@1) */
  casadi_densify((&w01), casadi_s9, w18, 0);
  /* #405: @24 = (@24+@18) */
  for (i=0, rr=w24, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #406: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #407: @1 = (-@41) */
  w01 = (- w41 );
  /* #408: @27 = mac(@1,@35,@27) */
  casadi_mtimes((&w01), casadi_s9, wr35, casadi_s4, w27, casadi_s2, w, 0);
  /* #409: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<9; ++i) *rr++ = (- *cs++ );
  /* #410: @25 = mac(@27,@28,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #411: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #412: @34 = mac(@29,@27,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #413: @34 = @34' */
  /* #414: @24 = (@24+@34) */
  for (i=0, rr=w24, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #415: (@17[6:9] += @24) */
  for (rr=w17+6, cs=w24; rr!=w17+9; rr+=1) *rr += *cs++;
  /* #416: @28 = (@28*@3) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) *= w03;
  /* #417: @24 = dense(@41) */
  casadi_densify((&w41), casadi_s9, w24, 0);
  /* #418: @28 = (@28+@24) */
  for (i=0, rr=w28, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #419: (@17[9:12] += @28) */
  for (rr=w17+9, cs=w28; rr!=w17+12; rr+=1) *rr += *cs++;
  /* #420: {@41, @3, @1, @5, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7} = vertsplit(@17) */
  w41 = w17[0];
  w03 = w17[1];
  w01 = w17[2];
  w05 = w17[3];
  w39 = w17[4];
  w16 = w17[5];
  w38 = w17[6];
  w48 = w17[7];
  w09 = w17[8];
  w04 = w17[9];
  w14 = w17[10];
  w02 = w17[11];
  w13 = w17[12];
  w40 = w17[13];
  w07 = w17[14];
  /* #421: @17 = vertcat(@45, @45, @45, @41, @3, @1, @5, @39, @16, @38, @48, @9, @4, @14, @2, @13, @40, @7) */
  rr=w17;
  *rr++ = w41;
  *rr++ = w03;
  *rr++ = w01;
  *rr++ = w05;
  *rr++ = w39;
  *rr++ = w16;
  *rr++ = w38;
  *rr++ = w48;
  *rr++ = w09;
  *rr++ = w04;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w07;
  /* #422: @53 = @17[6:12] */
  for (rr=w53, cs=w17+6; cs!=w17+12; cs+=1) *rr++ = *cs;
  /* #423: (@43[39:45] = @53) */
  for (rr=w43+39, cs=w53; rr!=w43+45; rr+=1) *rr = *cs++;
  /* #424: (@43[14:50:6] = @53) */
  for (rr=w43+14, cs=w53; rr!=w43+50; rr+=6) *rr = *cs++;
  /* #425: @54 = @43' */
  casadi_trans(w43,casadi_s11, w54, casadi_s11, iw);
  /* #426: output[2][0] = @54 */
  casadi_copy(w54, 48, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_jerk_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    case 3: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s11;
    case 3: return casadi_s18;
    case 4: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 19;
  if (sz_w) *sz_w = 285;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 23*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 19*sizeof(casadi_int);
  if (sz_w) *sz_w = 285*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
