/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_jerk_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {51, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {18, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* planner_payload_jerk_cost_ext_cost_fun_jac:(i0[15],i1[3],i2[0],i3[51])->(o0,o1[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w20=w+56, *w21=w+59, *w22=w+62, *w23=w+65;
  casadi_real *w24=w+68, *w25=w+71, *w26=w+74, *w27=w+83, *w28=w+92, *w29=w+95, *w30=w+98, *w32=w+110, *w33=w+113, *w34=w+116, *w35=w+119, w36;
  const casadi_real *cr, *cs, *ct, *wr19, *wr20, *wr22, *wr26, *wr31, *wr33;
  /* #0: @0 = 5000 */
  w00 = 5000.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = input[3][0] */
  wr19 = arg[3] ? arg[3] : casadi_zeros;
  /* #20: @20 = @19[:3] */
  wr20 = wr19+0;
  /* #21: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=wr20; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #23: @2 = mac(@20,@18,@1) */
  casadi_copy((&w01), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #24: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #25: @3 = 0.3 */
  w03 = 2.9999999999999999e-01;
  /* #26: @21 = @17[3:6] */
  for (rr=w21, cs=w17+3; cs!=w17+6; cs+=1) *rr++ = *cs;
  /* #27: @22 = @19[3:6] */
  wr22 = wr19+3;
  /* #28: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #29: @22 = @21' */
  casadi_copy(w21, 3, w22);
  /* #30: @4 = mac(@22,@21,@1) */
  casadi_copy((&w01), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #31: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #32: @2 = (@2+@4) */
  w02 += w04;
  /* #33: @4 = @19[7] */
  w04 = wr19[7];
  /* #34: @5 = (@4*@10) */
  w05  = (w04*w10);
  /* #35: @6 = @19[8] */
  w06 = wr19[8];
  /* #36: @7 = (@6*@9) */
  w07  = (w06*w09);
  /* #37: @5 = (@5-@7) */
  w05 -= w07;
  /* #38: @7 = (@6*@8) */
  w07  = (w06*w08);
  /* #39: @11 = @19[6] */
  w11 = wr19[6];
  /* #40: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #41: @7 = (@7-@10) */
  w07 -= w10;
  /* #42: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #43: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #44: @9 = (@9-@8) */
  w09 -= w08;
  /* #45: @23 = vertcat(@5, @7, @9) */
  rr=w23;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  /* #46: @24 = @23' */
  casadi_copy(w23, 3, w24);
  /* #47: @5 = mac(@24,@23,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@5) */
  w02 += w05;
  /* #49: @24 = @17[9:12] */
  for (rr=w24, cs=w17+9; cs!=w17+12; cs+=1) *rr++ = *cs;
  /* #50: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #51: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr26 = casadi_c0;
  /* #52: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #53: @28 = @17[6:9] */
  for (rr=w28, cs=w17+6; cs!=w17+9; cs+=1) *rr++ = *cs;
  /* #54: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #55: @30 = mac(@28,@29,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #56: @26 = (@26-@30) */
  for (i=0, rr=w26, cr=wr26, cs=w30; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #57: @31 = @19[9:12] */
  wr31 = wr19+9;
  /* #58: @32 = mac(@26,@31,@25) */
  casadi_copy(w25, 3, w32);
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #59: @32 = (@24-@32) */
  for (i=0, rr=w32, cr=w24, cs=w32; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #60: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #61: @5 = mac(@33,@32,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #62: @2 = (@2+@5) */
  w02 += w05;
  /* #63: @33 = @19[12:15] */
  wr33 = wr19+12;
  /* #64: @34 = @17[12:15] */
  for (rr=w34, cs=w17+12; cs!=w17+15; cs+=1) *rr++ = *cs;
  /* #65: @33 = (@33-@34) */
  for (i=0, rr=w33, cr=wr33, cs=w34; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #66: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #67: @5 = mac(@34,@33,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #68: @2 = (@2+@5) */
  w02 += w05;
  /* #69: @5 = 0.1 */
  w05 = 1.0000000000000001e-01;
  /* #70: @7 = input[1][0] */
  w07 = arg[1] ? arg[1][0] : 0;
  /* #71: @9 = input[1][1] */
  w09 = arg[1] ? arg[1][1] : 0;
  /* #72: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #73: @34 = vertcat(@7, @9, @8) */
  rr=w34;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w08;
  /* #74: @35 = @34' */
  casadi_copy(w34, 3, w35);
  /* #75: @1 = mac(@35,@34,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #76: @1 = (@5*@1) */
  w01  = (w05*w01);
  /* #77: @2 = (@2+@1) */
  w02 += w01;
  /* #78: @1 = dot(@28, @24) */
  w01 = casadi_dot(3, w28, w24);
  /* #79: @7 = sq(@1) */
  w07 = casadi_sq( w01 );
  /* #80: @2 = (@2+@7) */
  w02 += w07;
  /* #81: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #82: @34 = (@5*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #83: @35 = (@5*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #84: @35 = @35' */
  /* #85: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #86: {@5, @2, @7} = vertsplit(@34) */
  w05 = w34[0];
  w02 = w34[1];
  w07 = w34[2];
  /* #87: output[1][0] = @5 */
  if (res[1]) res[1][0] = w05;
  /* #88: output[1][1] = @2 */
  if (res[1]) res[1][1] = w02;
  /* #89: output[1][2] = @7 */
  if (res[1]) res[1][2] = w07;
  /* #90: @17 = zeros(15x1) */
  casadi_clear(w17, 15);
  /* #91: @33 = (2.*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #92: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #93: (@17[12:15] += @33) */
  for (rr=w17+12, cs=w33; rr!=w17+15; rr+=1) *rr += *cs++;
  /* #94: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #95: @24 = (@1*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #96: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: @33 = (-@32) */
  for (i=0, rr=w33, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #98: @31 = @31' */
  /* #99: @27 = mac(@33,@31,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w33+j, ct=wr31+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #100: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<9; ++i) *rr++ = (- *cs++ );
  /* #101: @25 = mac(@27,@28,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #102: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #103: @25 = zeros(1x3) */
  casadi_clear(w25, 3);
  /* #104: @25 = mac(@29,@27,@25) */
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #105: @25 = @25' */
  /* #106: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #107: (@17[6:9] += @24) */
  for (rr=w17+6, cs=w24; rr!=w17+9; rr+=1) *rr += *cs++;
  /* #108: @28 = (@1*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #109: @28 = (@28+@32) */
  for (i=0, rr=w28, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #110: (@17[9:12] += @28) */
  for (rr=w17+9, cs=w28; rr!=w17+12; rr+=1) *rr += *cs++;
  /* #111: @21 = (@3*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #112: @22 = (@3*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #113: @22 = @22' */
  /* #114: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #115: (@17[3:6] += @21) */
  for (rr=w17+3, cs=w21; rr!=w17+6; rr+=1) *rr += *cs++;
  /* #116: @18 = (@0*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #117: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #118: @20 = @20' */
  /* #119: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #120: (@17[:3] += @18) */
  for (rr=w17+0, cs=w18; rr!=w17+3; rr+=1) *rr += *cs++;
  /* #121: {@0, @3, @1, @7, @2, @5, @9, @8, @10, @12, @13, @14, @15, @16, @36} = vertsplit(@17) */
  w00 = w17[0];
  w03 = w17[1];
  w01 = w17[2];
  w07 = w17[3];
  w02 = w17[4];
  w05 = w17[5];
  w09 = w17[6];
  w08 = w17[7];
  w10 = w17[8];
  w12 = w17[9];
  w13 = w17[10];
  w14 = w17[11];
  w15 = w17[12];
  w16 = w17[13];
  w36 = w17[14];
  /* #122: output[1][3] = @0 */
  if (res[1]) res[1][3] = w00;
  /* #123: output[1][4] = @3 */
  if (res[1]) res[1][4] = w03;
  /* #124: output[1][5] = @1 */
  if (res[1]) res[1][5] = w01;
  /* #125: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #126: output[1][7] = @2 */
  if (res[1]) res[1][7] = w02;
  /* #127: output[1][8] = @5 */
  if (res[1]) res[1][8] = w05;
  /* #128: @23 = (2.*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #129: {@5, @2, @7} = vertsplit(@23) */
  w05 = w23[0];
  w02 = w23[1];
  w07 = w23[2];
  /* #130: @1 = (@6*@2) */
  w01  = (w06*w02);
  /* #131: @3 = (@4*@7) */
  w03  = (w04*w07);
  /* #132: @1 = (@1-@3) */
  w01 -= w03;
  /* #133: @1 = (@1+@9) */
  w01 += w09;
  /* #134: output[1][9] = @1 */
  if (res[1]) res[1][9] = w01;
  /* #135: @7 = (@11*@7) */
  w07  = (w11*w07);
  /* #136: @6 = (@6*@5) */
  w06 *= w05;
  /* #137: @7 = (@7-@6) */
  w07 -= w06;
  /* #138: @7 = (@7+@8) */
  w07 += w08;
  /* #139: output[1][10] = @7 */
  if (res[1]) res[1][10] = w07;
  /* #140: @4 = (@4*@5) */
  w04 *= w05;
  /* #141: @11 = (@11*@2) */
  w11 *= w02;
  /* #142: @4 = (@4-@11) */
  w04 -= w11;
  /* #143: @4 = (@4+@10) */
  w04 += w10;
  /* #144: output[1][11] = @4 */
  if (res[1]) res[1][11] = w04;
  /* #145: output[1][12] = @12 */
  if (res[1]) res[1][12] = w12;
  /* #146: output[1][13] = @13 */
  if (res[1]) res[1][13] = w13;
  /* #147: output[1][14] = @14 */
  if (res[1]) res[1][14] = w14;
  /* #148: output[1][15] = @15 */
  if (res[1]) res[1][15] = w15;
  /* #149: output[1][16] = @16 */
  if (res[1]) res[1][16] = w16;
  /* #150: output[1][17] = @36 */
  if (res[1]) res[1][17] = w36;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_jerk_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 123;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 123*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
