/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_jerk_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {51, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {18, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[18] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* planner_payload_jerk_cost_ext_cost_fun_jac:(i0[15],i1[3],i2[0],i3[51])->(o0,o1[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+5, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+23, *w19=w+38, *w21=w+59, *w22=w+62, *w23=w+71;
  casadi_real *w24=w+80, *w25=w+83, *w26=w+86, *w27=w+89, *w28=w+92, *w29=w+95, *w30=w+104, *w31=w+107, *w32=w+110, *w34=w+122, *w35=w+125, *w36=w+128;
  casadi_real *w37=w+131, w38;
  const casadi_real *cr, *cs, *ct, *wr20, *wr21, *wr25, *wr29, *wr33, *wr35, *wr36;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x3) */
  casadi_clear(w02, 3);
  /* #3: @3 = input[0][0] */
  w03 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #7: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #9: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #10: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #11: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #12: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #13: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #14: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #15: @15 = input[0][12] */
  w15 = arg[0] ? arg[0][12] : 0;
  /* #16: @16 = input[0][13] */
  w16 = arg[0] ? arg[0][13] : 0;
  /* #17: @17 = input[0][14] */
  w17 = arg[0] ? arg[0][14] : 0;
  /* #18: @18 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:3] */
  for (rr=w19, cs=w18+0; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #20: @20 = input[3][0] */
  wr20 = arg[3] ? arg[3] : casadi_zeros;
  /* #21: @21 = @20[:3] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<3; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 3, w21);
  /* #24: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #25: @3 = 1 */
  w03 = 1.;
  /* #26: @23 = @22; (@23[0] = @3) */
  casadi_copy(w22, 9, w23);
  for (rr=w23+0, cs=(&w03); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #27: (@23[4] = @3) */
  for (rr=w23+4, cs=(&w03); rr!=w23+5; rr+=1) *rr = *cs++;
  /* #28: @3 = 20 */
  w03 = 20.;
  /* #29: (@23[8] = @3) */
  for (rr=w23+8, cs=(&w03); rr!=w23+9; rr+=1) *rr = *cs++;
  /* #30: @24 = mac(@21,@23,@2) */
  casadi_copy(w02, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #31: @3 = mac(@24,@19,@1) */
  casadi_copy((&w01), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #32: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #33: @4 = 0.5 */
  w04 = 5.0000000000000000e-01;
  /* #34: @19 = @18[3:6] */
  for (rr=w19, cs=w18+3; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #35: @25 = @20[3:6] */
  wr25 = wr20+3;
  /* #36: @19 = (@19-@25) */
  for (i=0, rr=w19, cs=wr25; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @25 = @19' */
  casadi_copy(w19, 3, w25);
  /* #38: @5 = mac(@25,@19,@1) */
  casadi_copy((&w01), 1, (&w05));
  for (i=0, rr=(&w05); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #39: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #40: @3 = (@3+@5) */
  w03 += w05;
  /* #41: @5 = @20[7] */
  w05 = wr20[7];
  /* #42: @6 = (@5*@11) */
  w06  = (w05*w11);
  /* #43: @7 = @20[8] */
  w07 = wr20[8];
  /* #44: @8 = (@7*@10) */
  w08  = (w07*w10);
  /* #45: @6 = (@6-@8) */
  w06 -= w08;
  /* #46: @8 = (@7*@9) */
  w08  = (w07*w09);
  /* #47: @12 = @20[6] */
  w12 = wr20[6];
  /* #48: @11 = (@12*@11) */
  w11  = (w12*w11);
  /* #49: @8 = (@8-@11) */
  w08 -= w11;
  /* #50: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #51: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #52: @10 = (@10-@9) */
  w10 -= w09;
  /* #53: @26 = vertcat(@6, @8, @10) */
  rr=w26;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w10;
  /* #54: @27 = @26' */
  casadi_copy(w26, 3, w27);
  /* #55: @6 = mac(@27,@26,@1) */
  casadi_copy((&w01), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #56: @3 = (@3+@6) */
  w03 += w06;
  /* #57: @27 = @18[9:12] */
  for (rr=w27, cs=w18+9; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #58: @28 = zeros(3x1) */
  casadi_clear(w28, 3);
  /* #59: @29 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr29 = casadi_c0;
  /* #60: @30 = @18[6:9] */
  for (rr=w30, cs=w18+6; cs!=w18+9; cs+=1) *rr++ = *cs;
  /* #61: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #62: @32 = mac(@30,@31,@22) */
  casadi_copy(w22, 9, w32);
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w31+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #63: @29 = (@29-@32) */
  for (i=0, rr=w29, cr=wr29, cs=w32; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #64: @33 = @20[9:12] */
  wr33 = wr20+9;
  /* #65: @34 = mac(@29,@33,@28) */
  casadi_copy(w28, 3, w34);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=wr33+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #66: @34 = (@27-@34) */
  for (i=0, rr=w34, cr=w27, cs=w34; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #67: @35 = @34' */
  casadi_copy(w34, 3, w35);
  /* #68: @6 = mac(@35,@34,@1) */
  casadi_copy((&w01), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #69: @3 = (@3+@6) */
  w03 += w06;
  /* #70: @35 = @20[12:15] */
  wr35 = wr20+12;
  /* #71: @36 = @18[12:15] */
  for (rr=w36, cs=w18+12; cs!=w18+15; cs+=1) *rr++ = *cs;
  /* #72: @35 = (@35-@36) */
  for (i=0, rr=w35, cr=wr35, cs=w36; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #73: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #74: @6 = mac(@36,@35,@1) */
  casadi_copy((&w01), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #75: @3 = (@3+@6) */
  w03 += w06;
  /* #76: @6 = 0.1 */
  w06 = 1.0000000000000001e-01;
  /* #77: @36 = @20[15:18] */
  wr36 = wr20+15;
  /* #78: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #79: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #80: @9 = input[1][2] */
  w09 = arg[1] ? arg[1][2] : 0;
  /* #81: @37 = vertcat(@8, @10, @9) */
  rr=w37;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w09;
  /* #82: @36 = (@36-@37) */
  for (i=0, rr=w36, cr=wr36, cs=w37; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #83: @37 = @36' */
  casadi_copy(w36, 3, w37);
  /* #84: @1 = mac(@37,@36,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #85: @1 = (@6*@1) */
  w01  = (w06*w01);
  /* #86: @3 = (@3+@1) */
  w03 += w01;
  /* #87: @1 = dot(@30, @27) */
  w01 = casadi_dot(3, w30, w27);
  /* #88: @8 = sq(@1) */
  w08 = casadi_sq( w01 );
  /* #89: @3 = (@3+@8) */
  w03 += w08;
  /* #90: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #91: @36 = (@6*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #92: @37 = (@6*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #93: @37 = @37' */
  /* #94: @36 = (@36+@37) */
  for (i=0, rr=w36, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #95: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (- *cs++ );
  /* #96: {@6, @3, @8} = vertsplit(@36) */
  w06 = w36[0];
  w03 = w36[1];
  w08 = w36[2];
  /* #97: output[1][0] = @6 */
  if (res[1]) res[1][0] = w06;
  /* #98: output[1][1] = @3 */
  if (res[1]) res[1][1] = w03;
  /* #99: output[1][2] = @8 */
  if (res[1]) res[1][2] = w08;
  /* #100: @18 = zeros(15x1) */
  casadi_clear(w18, 15);
  /* #101: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #102: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #103: (@18[12:15] += @35) */
  for (rr=w18+12, cs=w35; rr!=w18+15; rr+=1) *rr += *cs++;
  /* #104: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #105: @27 = (@1*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #106: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #107: @35 = (-@34) */
  for (i=0, rr=w35, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #108: @33 = @33' */
  /* #109: @22 = mac(@35,@33,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w35+j, ct=wr33+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #110: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<9; ++i) *rr++ = (- *cs++ );
  /* #111: @28 = mac(@22,@30,@28) */
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #112: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #113: @28 = mac(@31,@22,@2) */
  casadi_copy(w02, 3, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #114: @28 = @28' */
  /* #115: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #116: (@18[6:9] += @27) */
  for (rr=w18+6, cs=w27; rr!=w18+9; rr+=1) *rr += *cs++;
  /* #117: @30 = (@1*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #118: @30 = (@30+@34) */
  for (i=0, rr=w30, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #119: (@18[9:12] += @30) */
  for (rr=w18+9, cs=w30; rr!=w18+12; rr+=1) *rr += *cs++;
  /* #120: @19 = (@4*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #121: @25 = (@4*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #122: @25 = @25' */
  /* #123: @19 = (@19+@25) */
  for (i=0, rr=w19, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #124: (@18[3:6] += @19) */
  for (rr=w18+3, cs=w19; rr!=w18+6; rr+=1) *rr += *cs++;
  /* #125: @24 = @24' */
  /* #126: @24 = (@0*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #127: @21 = (@0*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #128: @22 = @23' */
  for (i=0, rr=w22, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #129: @2 = mac(@21,@22,@2) */
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #130: @2 = @2' */
  /* #131: @24 = (@24+@2) */
  for (i=0, rr=w24, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #132: (@18[:3] += @24) */
  for (rr=w18+0, cs=w24; rr!=w18+3; rr+=1) *rr += *cs++;
  /* #133: {@0, @4, @1, @8, @3, @6, @10, @9, @11, @13, @14, @15, @16, @17, @38} = vertsplit(@18) */
  w00 = w18[0];
  w04 = w18[1];
  w01 = w18[2];
  w08 = w18[3];
  w03 = w18[4];
  w06 = w18[5];
  w10 = w18[6];
  w09 = w18[7];
  w11 = w18[8];
  w13 = w18[9];
  w14 = w18[10];
  w15 = w18[11];
  w16 = w18[12];
  w17 = w18[13];
  w38 = w18[14];
  /* #134: output[1][3] = @0 */
  if (res[1]) res[1][3] = w00;
  /* #135: output[1][4] = @4 */
  if (res[1]) res[1][4] = w04;
  /* #136: output[1][5] = @1 */
  if (res[1]) res[1][5] = w01;
  /* #137: output[1][6] = @8 */
  if (res[1]) res[1][6] = w08;
  /* #138: output[1][7] = @3 */
  if (res[1]) res[1][7] = w03;
  /* #139: output[1][8] = @6 */
  if (res[1]) res[1][8] = w06;
  /* #140: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #141: {@6, @3, @8} = vertsplit(@26) */
  w06 = w26[0];
  w03 = w26[1];
  w08 = w26[2];
  /* #142: @1 = (@7*@3) */
  w01  = (w07*w03);
  /* #143: @4 = (@5*@8) */
  w04  = (w05*w08);
  /* #144: @1 = (@1-@4) */
  w01 -= w04;
  /* #145: @1 = (@1+@10) */
  w01 += w10;
  /* #146: output[1][9] = @1 */
  if (res[1]) res[1][9] = w01;
  /* #147: @8 = (@12*@8) */
  w08  = (w12*w08);
  /* #148: @7 = (@7*@6) */
  w07 *= w06;
  /* #149: @8 = (@8-@7) */
  w08 -= w07;
  /* #150: @8 = (@8+@9) */
  w08 += w09;
  /* #151: output[1][10] = @8 */
  if (res[1]) res[1][10] = w08;
  /* #152: @5 = (@5*@6) */
  w05 *= w06;
  /* #153: @12 = (@12*@3) */
  w12 *= w03;
  /* #154: @5 = (@5-@12) */
  w05 -= w12;
  /* #155: @5 = (@5+@11) */
  w05 += w11;
  /* #156: output[1][11] = @5 */
  if (res[1]) res[1][11] = w05;
  /* #157: output[1][12] = @13 */
  if (res[1]) res[1][12] = w13;
  /* #158: output[1][13] = @14 */
  if (res[1]) res[1][13] = w14;
  /* #159: output[1][14] = @15 */
  if (res[1]) res[1][14] = w15;
  /* #160: output[1][15] = @16 */
  if (res[1]) res[1][15] = w16;
  /* #161: output[1][16] = @17 */
  if (res[1]) res[1][16] = w17;
  /* #162: output[1][17] = @38 */
  if (res[1]) res[1][17] = w38;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_jerk_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 135;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 135*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
