/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[16] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 16, 22, 28, 34, 40};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s3[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s4[65] = 
  {16, 16, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 16, 22, 28,
  34, 40, 46, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 10, 11, 12, 13, 14,
  15, 10, 11, 12, 13, 14, 15, 10,
  11, 12, 13, 14, 15, 10, 11, 12,
  13, 14, 15, 10, 11, 12, 13, 14,
  15};
static const casadi_int casadi_s5[3] = {12, 1, 1};
static const casadi_int casadi_s6[3] = {4, 1, 1};
static const casadi_int casadi_s7[3] = {0, 1, 1};
static const casadi_int casadi_s8[3] = {44, 1, 1};
static const casadi_int casadi_s9[3] = {1, 1, 1};
static const casadi_int casadi_s10[3] = {16, 1, 1};
static const casadi_int casadi_s11[3] = {0, 0, 1};
static const casadi_int casadi_s12[3] = {0, 16, 1};

static const casadi_real casadi_zeros[16] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* planner_payload_cost_ext_cost_fun_jac_hess:(i0[12],i1[4],i2[0],i3[44])->(o0,o1[16],o2[16x16,46nz],o3[],o4[0x16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, *w14=w+15, *w15=w+27, *w16=w+30, *w17=w+46, *w18=w+49, *w19=w+52, *w20=w+56, *w21=w+59, *w22=w+62;
  casadi_real *w23=w+65, *w24=w+69, w25, w26, w27, *w28=w+84, *w29=w+130, w30, *w32=w+142, *w33=w+149, *w34=w+155;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr15, *wr16, *wr17, *wr18;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = 5000 */
  w01 = 5000.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:3] */
  for (rr=w15, cs=w14+0; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #16: @16 = input[3][0] */
  wr16 = arg[3] ? arg[3] : casadi_zeros;
  /* #17: @17 = @16[:3] */
  wr17 = wr16+0;
  /* #18: @15 = (@15-@17) */
  for (i=0, rr=w15, cs=wr17; i<3; ++i) (*rr++) -= (*cs++);
  /* #19: @17 = @15' */
  casadi_copy(w15, 3, w17);
  /* #20: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #21: @2 = mac(@17,@15,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #22: @3 = 0.282 */
  w03 = 2.8199999999999997e-01;
  /* #23: @15 = @14[3:6] */
  for (rr=w15, cs=w14+3; cs!=w14+6; cs+=1) *rr++ = *cs;
  /* #24: @18 = @16[3:6] */
  wr18 = wr16+3;
  /* #25: @15 = (@15-@18) */
  for (i=0, rr=w15, cs=wr18; i<3; ++i) (*rr++) -= (*cs++);
  /* #26: @18 = @15' */
  casadi_copy(w15, 3, w18);
  /* #27: @18 = (@3*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #28: @4 = mac(@18,@15,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w18+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #29: @2 = (@2+@4) */
  w02 += w04;
  /* #30: @4 = 50 */
  w04 = 50.;
  /* #31: @5 = @16[12] */
  w05 = wr16[12];
  /* #32: @6 = input[1][0] */
  w06 = arg[1] ? arg[1][0] : 0;
  /* #33: @5 = (@5-@6) */
  w05 -= w06;
  /* #34: @7 = sq(@5) */
  w07 = casadi_sq( w05 );
  /* #35: @7 = (@4*@7) */
  w07  = (w04*w07);
  /* #36: @2 = (@2+@7) */
  w02 += w07;
  /* #37: @15 = @16[13:16] */
  wr15 = wr16+13;
  /* #38: @7 = input[1][1] */
  w07 = arg[1] ? arg[1][1] : 0;
  /* #39: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #40: @9 = input[1][3] */
  w09 = arg[1] ? arg[1][3] : 0;
  /* #41: @19 = vertcat(@6, @7, @8, @9) */
  rr=w19;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #42: @20 = @19[1:4] */
  for (rr=w20, cs=w19+1; cs!=w19+4; cs+=1) *rr++ = *cs;
  /* #43: @15 = (@15-@20) */
  for (i=0, rr=w15, cr=wr15, cs=w20; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #44: @20 = @15' */
  casadi_copy(w15, 3, w20);
  /* #45: @0 = mac(@20,@15,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @0 = (@4*@0) */
  w00  = (w04*w00);
  /* #47: @2 = (@2+@0) */
  w02 += w00;
  /* #48: @0 = 0.1 */
  w00 = 1.0000000000000001e-01;
  /* #49: @21 = @14[6:9] */
  for (rr=w21, cs=w14+6; cs!=w14+9; cs+=1) *rr++ = *cs;
  /* #50: @22 = @14[9:12] */
  for (rr=w22, cs=w14+9; cs!=w14+12; cs+=1) *rr++ = *cs;
  /* #51: @6 = dot(@21, @22) */
  w06 = casadi_dot(3, w21, w22);
  /* #52: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #53: @7 = (@0*@7) */
  w07  = (w00*w07);
  /* #54: @2 = (@2+@7) */
  w02 += w07;
  /* #55: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #56: @19 = zeros(4x1) */
  casadi_clear(w19, 4);
  /* #57: @15 = (@4*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #58: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #59: @20 = @20' */
  /* #60: @15 = (@15+@20) */
  for (i=0, rr=w15, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #61: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #62: @23 = @19; (@23[1:4] += @15) */
  casadi_copy(w19, 4, w23);
  for (rr=w23+1, cs=w15; rr!=w23+4; rr+=1) *rr += *cs++;
  /* #63: {@2, @7, @8, @9} = vertsplit(@23) */
  w02 = w23[0];
  w07 = w23[1];
  w08 = w23[2];
  w09 = w23[3];
  /* #64: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #65: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #66: @2 = (@2-@5) */
  w02 -= w05;
  /* #67: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #68: output[1][1] = @7 */
  if (res[1]) res[1][1] = w07;
  /* #69: output[1][2] = @8 */
  if (res[1]) res[1][2] = w08;
  /* #70: output[1][3] = @9 */
  if (res[1]) res[1][3] = w09;
  /* #71: @14 = zeros(12x1) */
  casadi_clear(w14, 12);
  /* #72: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #73: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #74: @15 = (@6*@21) */
  for (i=0, rr=w15, cs=w21; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #75: @24 = @14; (@24[9:12] += @15) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w15; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #76: @15 = (@6*@22) */
  for (i=0, rr=w15, cs=w22; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #77: (@24[6:9] += @15) */
  for (rr=w24+6, cs=w15; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #78: @18 = @18' */
  /* #79: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #80: (@24[3:6] += @18) */
  for (rr=w24+3, cs=w18; rr!=w24+6; rr+=1) *rr += *cs++;
  /* #81: @17 = @17' */
  /* #82: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #83: (@24[:3] += @17) */
  for (rr=w24+0, cs=w17; rr!=w24+3; rr+=1) *rr += *cs++;
  /* #84: {@9, @8, @7, @2, @5, @10, @11, @12, @13, @25, @26, @27} = vertsplit(@24) */
  w09 = w24[0];
  w08 = w24[1];
  w07 = w24[2];
  w02 = w24[3];
  w05 = w24[4];
  w10 = w24[5];
  w11 = w24[6];
  w12 = w24[7];
  w13 = w24[8];
  w25 = w24[9];
  w26 = w24[10];
  w27 = w24[11];
  /* #85: output[1][4] = @9 */
  if (res[1]) res[1][4] = w09;
  /* #86: output[1][5] = @8 */
  if (res[1]) res[1][5] = w08;
  /* #87: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #88: output[1][7] = @2 */
  if (res[1]) res[1][7] = w02;
  /* #89: output[1][8] = @5 */
  if (res[1]) res[1][8] = w05;
  /* #90: output[1][9] = @10 */
  if (res[1]) res[1][9] = w10;
  /* #91: output[1][10] = @11 */
  if (res[1]) res[1][10] = w11;
  /* #92: output[1][11] = @12 */
  if (res[1]) res[1][11] = w12;
  /* #93: output[1][12] = @13 */
  if (res[1]) res[1][12] = w13;
  /* #94: output[1][13] = @25 */
  if (res[1]) res[1][13] = w25;
  /* #95: output[1][14] = @26 */
  if (res[1]) res[1][14] = w26;
  /* #96: output[1][15] = @27 */
  if (res[1]) res[1][15] = w27;
  /* #97: @28 = zeros(16x16,46nz) */
  casadi_clear(w28, 46);
  /* #98: @29 = ones(16x1,11nz) */
  casadi_fill(w29, 11, 1.);
  /* #99: {@27, @26, @25, @13, @12, @11, @10, @5, @2, @7, @8, NULL, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w27 = w29[0];
  w26 = w29[1];
  w25 = w29[2];
  w13 = w29[3];
  w12 = w29[4];
  w11 = w29[5];
  w10 = w29[6];
  w05 = w29[7];
  w02 = w29[8];
  w07 = w29[9];
  w08 = w29[10];
  /* #100: @23 = vertcat(@27, @26, @25, @13) */
  rr=w23;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w13;
  /* #101: @17 = @23[1:4] */
  for (rr=w17, cs=w23+1; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #102: @18 = (-@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) *rr++ = (- *cs++ );
  /* #103: @18 = @18' */
  /* #104: @18 = (@4*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #105: @18 = @18' */
  /* #106: @17 = (@4*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #107: @18 = (@18-@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #108: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #109: (@19[1:4] += @18) */
  for (rr=w19+1, cs=w18; rr!=w19+4; rr+=1) *rr += *cs++;
  /* #110: {@26, @25, @13, @9} = vertsplit(@19) */
  w26 = w19[0];
  w25 = w19[1];
  w13 = w19[2];
  w09 = w19[3];
  /* #111: @27 = (-@27) */
  w27 = (- w27 );
  /* #112: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #113: @4 = (@4*@27) */
  w04 *= w27;
  /* #114: @26 = (@26-@4) */
  w26 -= w04;
  /* #115: @4 = sparsity_cast(@8) */
  w04 = w08;
  /* #116: @27 = project(@22) */
  casadi_sparsify(w22, (&w27), casadi_s0, 0);
  /* #117: @30 = dot(@4, @27) */
  w30 = casadi_dot(1, (&w04), (&w27));
  /* #118: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #119: @30 = (@0*@30) */
  w30  = (w00*w30);
  /* #120: @18 = (@21*@30) */
  for (i=0, rr=w18, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w30);
  /* #121: @4 = (@6*@4) */
  w04  = (w06*w04);
  /* #122: @17 = dense(@4) */
  casadi_densify((&w04), casadi_s0, w17, 0);
  /* #123: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #124: @24 = @14; (@24[9:12] += @18) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w18; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #125: @18 = (@22*@30) */
  for (i=0, rr=w18, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w30);
  /* #126: (@24[6:9] += @18) */
  for (rr=w24+6, cs=w18; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #127: @31 = 00 */
  /* #128: @32 = vertcat(@12, @11, @10, @5, @2, @7, @8, @31, @31, @31, @31, @31) */
  rr=w32;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  *rr++ = w08;
  /* #129: @18 = @32[3:6] */
  for (rr=w18, cs=w32+3; cs!=w32+6; cs+=1) *rr++ = *cs;
  /* #130: @18 = @18' */
  /* #131: @18 = (@3*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #132: @18 = @18' */
  /* #133: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #134: (@24[3:6] += @18) */
  for (rr=w24+3, cs=w18; rr!=w24+6; rr+=1) *rr += *cs++;
  /* #135: @18 = @32[:3] */
  for (rr=w18, cs=w32+0; cs!=w32+3; cs+=1) *rr++ = *cs;
  /* #136: @18 = @18' */
  /* #137: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #138: @18 = @18' */
  /* #139: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #140: (@24[:3] += @18) */
  for (rr=w24+0, cs=w18; rr!=w24+3; rr+=1) *rr += *cs++;
  /* #141: {@1, @3, @12, @11, @10, @5, @2, @7, @8, @30, @4, @27} = vertsplit(@24) */
  w01 = w24[0];
  w03 = w24[1];
  w12 = w24[2];
  w11 = w24[3];
  w10 = w24[4];
  w05 = w24[5];
  w02 = w24[6];
  w07 = w24[7];
  w08 = w24[8];
  w30 = w24[9];
  w04 = w24[10];
  w27 = w24[11];
  /* #142: @16 = vertcat(@26, @25, @13, @9, @1, @3, @12, @11, @10, @5, @2, @7, @8, @30, @4, @27) */
  rr=w16;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w30;
  *rr++ = w04;
  *rr++ = w27;
  /* #143: (@28[:16] = @16) */
  for (rr=w28+0, cs=w16; rr!=w28+16; rr+=1) *rr = *cs++;
  /* #144: (@28[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 22, 28, 34, 40] = @16) */
  for (cii=casadi_s1, rr=w28, cs=w16; cii!=casadi_s1+16; ++cii, ++cs) rr[*cii] = *cs;
  /* #145: @26 = ones(16x1,1nz) */
  w26 = 1.;
  /* #146: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @25, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w25 = w26;
  /* #147: @25 = sparsity_cast(@25) */
  /* #148: @26 = project(@22) */
  casadi_sparsify(w22, (&w26), casadi_s2, 0);
  /* #149: @13 = dot(@25, @26) */
  w13 = casadi_dot(1, (&w25), (&w26));
  /* #150: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #151: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #152: @18 = (@21*@13) */
  for (i=0, rr=w18, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w13);
  /* #153: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #154: @17 = dense(@25) */
  casadi_densify((&w25), casadi_s2, w17, 0);
  /* #155: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #156: @24 = @14; (@24[9:12] += @18) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w18; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #157: @18 = (@22*@13) */
  for (i=0, rr=w18, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w13);
  /* #158: (@24[6:9] += @18) */
  for (rr=w24+6, cs=w18; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #159: {@13, @25, @26, @9, @1, @3, @12, @11, @10, @5, @2, @7} = vertsplit(@24) */
  w13 = w24[0];
  w25 = w24[1];
  w26 = w24[2];
  w09 = w24[3];
  w01 = w24[4];
  w03 = w24[5];
  w12 = w24[6];
  w11 = w24[7];
  w10 = w24[8];
  w05 = w24[9];
  w02 = w24[10];
  w07 = w24[11];
  /* #160: @24 = vertcat(@31, @31, @31, @31, @13, @25, @26, @9, @1, @3, @12, @11, @10, @5, @2, @7) */
  rr=w24;
  *rr++ = w13;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  /* #161: @33 = @24[6:12] */
  for (rr=w33, cs=w24+6; cs!=w24+12; cs+=1) *rr++ = *cs;
  /* #162: (@28[16:22] = @33) */
  for (rr=w28+16, cs=w33; rr!=w28+22; rr+=1) *rr = *cs++;
  /* #163: (@28[11:47:6] = @33) */
  for (rr=w28+11, cs=w33; rr!=w28+47; rr+=6) *rr = *cs++;
  /* #164: @13 = ones(16x1,1nz) */
  w13 = 1.;
  /* #165: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @25, NULL, NULL, NULL} = vertsplit(@13) */
  w25 = w13;
  /* #166: @25 = sparsity_cast(@25) */
  /* #167: @13 = project(@22) */
  casadi_sparsify(w22, (&w13), casadi_s3, 0);
  /* #168: @26 = dot(@25, @13) */
  w26 = casadi_dot(1, (&w25), (&w13));
  /* #169: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #170: @26 = (@0*@26) */
  w26  = (w00*w26);
  /* #171: @18 = (@21*@26) */
  for (i=0, rr=w18, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #172: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #173: @17 = dense(@25) */
  casadi_densify((&w25), casadi_s3, w17, 0);
  /* #174: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #175: @24 = @14; (@24[9:12] += @18) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w18; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #176: @18 = (@22*@26) */
  for (i=0, rr=w18, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #177: (@24[6:9] += @18) */
  for (rr=w24+6, cs=w18; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #178: {@26, @25, @13, @9, @1, @3, @12, @11, @10, @5, @2, @7} = vertsplit(@24) */
  w26 = w24[0];
  w25 = w24[1];
  w13 = w24[2];
  w09 = w24[3];
  w01 = w24[4];
  w03 = w24[5];
  w12 = w24[6];
  w11 = w24[7];
  w10 = w24[8];
  w05 = w24[9];
  w02 = w24[10];
  w07 = w24[11];
  /* #179: @24 = vertcat(@31, @31, @31, @31, @26, @25, @13, @9, @1, @3, @12, @11, @10, @5, @2, @7) */
  rr=w24;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  /* #180: @33 = @24[6:12] */
  for (rr=w33, cs=w24+6; cs!=w24+12; cs+=1) *rr++ = *cs;
  /* #181: (@28[22:28] = @33) */
  for (rr=w28+22, cs=w33; rr!=w28+28; rr+=1) *rr = *cs++;
  /* #182: (@28[12:48:6] = @33) */
  for (rr=w28+12, cs=w33; rr!=w28+48; rr+=6) *rr = *cs++;
  /* #183: @26 = project(@21) */
  casadi_sparsify(w21, (&w26), casadi_s0, 0);
  /* #184: @25 = ones(16x1,1nz) */
  w25 = 1.;
  /* #185: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @13, NULL, NULL} = vertsplit(@25) */
  w13 = w25;
  /* #186: @13 = sparsity_cast(@13) */
  /* #187: @25 = dot(@26, @13) */
  w25 = casadi_dot(1, (&w26), (&w13));
  /* #188: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #189: @25 = (@0*@25) */
  w25  = (w00*w25);
  /* #190: @18 = (@21*@25) */
  for (i=0, rr=w18, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #191: @24 = @14; (@24[9:12] += @18) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w18; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #192: @18 = (@22*@25) */
  for (i=0, rr=w18, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #193: @13 = (@6*@13) */
  w13  = (w06*w13);
  /* #194: @17 = dense(@13) */
  casadi_densify((&w13), casadi_s0, w17, 0);
  /* #195: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #196: (@24[6:9] += @18) */
  for (rr=w24+6, cs=w18; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #197: {@13, @25, @26, @9, @1, @3, @12, @11, @10, @5, @2, @7} = vertsplit(@24) */
  w13 = w24[0];
  w25 = w24[1];
  w26 = w24[2];
  w09 = w24[3];
  w01 = w24[4];
  w03 = w24[5];
  w12 = w24[6];
  w11 = w24[7];
  w10 = w24[8];
  w05 = w24[9];
  w02 = w24[10];
  w07 = w24[11];
  /* #198: @24 = vertcat(@31, @31, @31, @31, @13, @25, @26, @9, @1, @3, @12, @11, @10, @5, @2, @7) */
  rr=w24;
  *rr++ = w13;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  /* #199: @33 = @24[6:12] */
  for (rr=w33, cs=w24+6; cs!=w24+12; cs+=1) *rr++ = *cs;
  /* #200: (@28[28:34] = @33) */
  for (rr=w28+28, cs=w33; rr!=w28+34; rr+=1) *rr = *cs++;
  /* #201: (@28[13:49:6] = @33) */
  for (rr=w28+13, cs=w33; rr!=w28+49; rr+=6) *rr = *cs++;
  /* #202: @13 = project(@21) */
  casadi_sparsify(w21, (&w13), casadi_s2, 0);
  /* #203: @25 = ones(16x1,1nz) */
  w25 = 1.;
  /* #204: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @26, NULL} = vertsplit(@25) */
  w26 = w25;
  /* #205: @26 = sparsity_cast(@26) */
  /* #206: @25 = dot(@13, @26) */
  w25 = casadi_dot(1, (&w13), (&w26));
  /* #207: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #208: @25 = (@0*@25) */
  w25  = (w00*w25);
  /* #209: @18 = (@21*@25) */
  for (i=0, rr=w18, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #210: @24 = @14; (@24[9:12] += @18) */
  casadi_copy(w14, 12, w24);
  for (rr=w24+9, cs=w18; rr!=w24+12; rr+=1) *rr += *cs++;
  /* #211: @18 = (@22*@25) */
  for (i=0, rr=w18, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #212: @26 = (@6*@26) */
  w26  = (w06*w26);
  /* #213: @17 = dense(@26) */
  casadi_densify((&w26), casadi_s2, w17, 0);
  /* #214: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #215: (@24[6:9] += @18) */
  for (rr=w24+6, cs=w18; rr!=w24+9; rr+=1) *rr += *cs++;
  /* #216: {@26, @25, @13, @9, @1, @3, @12, @11, @10, @5, @2, @7} = vertsplit(@24) */
  w26 = w24[0];
  w25 = w24[1];
  w13 = w24[2];
  w09 = w24[3];
  w01 = w24[4];
  w03 = w24[5];
  w12 = w24[6];
  w11 = w24[7];
  w10 = w24[8];
  w05 = w24[9];
  w02 = w24[10];
  w07 = w24[11];
  /* #217: @24 = vertcat(@31, @31, @31, @31, @26, @25, @13, @9, @1, @3, @12, @11, @10, @5, @2, @7) */
  rr=w24;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w07;
  /* #218: @33 = @24[6:12] */
  for (rr=w33, cs=w24+6; cs!=w24+12; cs+=1) *rr++ = *cs;
  /* #219: (@28[34:40] = @33) */
  for (rr=w28+34, cs=w33; rr!=w28+40; rr+=1) *rr = *cs++;
  /* #220: (@28[14:50:6] = @33) */
  for (rr=w28+14, cs=w33; rr!=w28+50; rr+=6) *rr = *cs++;
  /* #221: @26 = project(@21) */
  casadi_sparsify(w21, (&w26), casadi_s3, 0);
  /* #222: @25 = ones(16x1,1nz) */
  w25 = 1.;
  /* #223: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @13} = vertsplit(@25) */
  w13 = w25;
  /* #224: @13 = sparsity_cast(@13) */
  /* #225: @25 = dot(@26, @13) */
  w25 = casadi_dot(1, (&w26), (&w13));
  /* #226: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #227: @0 = (@0*@25) */
  w00 *= w25;
  /* #228: @21 = (@21*@0) */
  for (i=0, rr=w21; i<3; ++i) (*rr++) *= w00;
  /* #229: (@14[9:12] += @21) */
  for (rr=w14+9, cs=w21; rr!=w14+12; rr+=1) *rr += *cs++;
  /* #230: @22 = (@22*@0) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) *= w00;
  /* #231: @6 = (@6*@13) */
  w06 *= w13;
  /* #232: @21 = dense(@6) */
  casadi_densify((&w06), casadi_s3, w21, 0);
  /* #233: @22 = (@22+@21) */
  for (i=0, rr=w22, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #234: (@14[6:9] += @22) */
  for (rr=w14+6, cs=w22; rr!=w14+9; rr+=1) *rr += *cs++;
  /* #235: {@6, @13, @0, @25, @26, @9, @1, @3, @12, @11, @10, @5} = vertsplit(@14) */
  w06 = w14[0];
  w13 = w14[1];
  w00 = w14[2];
  w25 = w14[3];
  w26 = w14[4];
  w09 = w14[5];
  w01 = w14[6];
  w03 = w14[7];
  w12 = w14[8];
  w11 = w14[9];
  w10 = w14[10];
  w05 = w14[11];
  /* #236: @14 = vertcat(@31, @31, @31, @31, @6, @13, @0, @25, @26, @9, @1, @3, @12, @11, @10, @5) */
  rr=w14;
  *rr++ = w06;
  *rr++ = w13;
  *rr++ = w00;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w09;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w05;
  /* #237: @33 = @14[6:12] */
  for (rr=w33, cs=w14+6; cs!=w14+12; cs+=1) *rr++ = *cs;
  /* #238: (@28[40:46] = @33) */
  for (rr=w28+40, cs=w33; rr!=w28+46; rr+=1) *rr = *cs++;
  /* #239: (@28[15:51:6] = @33) */
  for (rr=w28+15, cs=w33; rr!=w28+51; rr+=6) *rr = *cs++;
  /* #240: @34 = @28' */
  casadi_trans(w28,casadi_s4, w34, casadi_s4, iw);
  /* #241: output[2][0] = @34 */
  casadi_copy(w34, 46, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s4;
    case 3: return casadi_s11;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 21;
  if (sz_iw) *sz_iw = 17;
  if (sz_w) *sz_w = 201;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 21*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 17*sizeof(casadi_int);
  if (sz_w) *sz_w = 201*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
