/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {56, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[20] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* planner_payload_cost_ext_cost_e_fun_jac:(i0[16],i1[0],i2[0],i3[56])->(o0,o1[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+21, *w19=w+37, *w21=w+60, *w22=w+63, *w23=w+66;
  casadi_real *w24=w+69, *w25=w+72, *w26=w+75, *w27=w+84, *w28=w+93, *w29=w+96, *w30=w+99, *w32=w+111, *w33=w+114, *w34=w+117, *w35=w+120, w36;
  casadi_real w37, w38;
  const casadi_real *cr, *cs, *ct, *wr20, *wr21, *wr22, *wr26, *wr31, *wr34;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = 5000 */
  w01 = 5000.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = input[0][15] */
  w17 = arg[0] ? arg[0][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:3] */
  for (rr=w19, cs=w18+0; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #20: @20 = input[3][0] */
  wr20 = arg[3] ? arg[3] : casadi_zeros;
  /* #21: @21 = @20[:3] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<3; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 3, w21);
  /* #24: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #25: @1 = mac(@21,@19,@0) */
  casadi_copy((&w00), 1, (&w01));
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #26: @2 = 0.564 */
  w02 = 5.6399999999999995e-01;
  /* #27: @19 = @18[3:6] */
  for (rr=w19, cs=w18+3; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #28: @22 = @20[3:6] */
  wr22 = wr20+3;
  /* #29: @19 = (@19-@22) */
  for (i=0, rr=w19, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #30: @22 = @19' */
  casadi_copy(w19, 3, w22);
  /* #31: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #32: @2 = mac(@22,@19,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #33: @1 = (@1+@2) */
  w01 += w02;
  /* #34: @2 = 10 */
  w02 = 10.;
  /* #35: @3 = @20[7] */
  w03 = wr20[7];
  /* #36: @4 = (@3*@10) */
  w04  = (w03*w10);
  /* #37: @5 = @20[8] */
  w05 = wr20[8];
  /* #38: @6 = (@5*@9) */
  w06  = (w05*w09);
  /* #39: @4 = (@4-@6) */
  w04 -= w06;
  /* #40: @6 = (@5*@8) */
  w06  = (w05*w08);
  /* #41: @7 = @20[6] */
  w07 = wr20[6];
  /* #42: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #43: @6 = (@6-@10) */
  w06 -= w10;
  /* #44: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #45: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #46: @9 = (@9-@8) */
  w09 -= w08;
  /* #47: @19 = vertcat(@4, @6, @9) */
  rr=w19;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w09;
  /* #48: @23 = @19' */
  casadi_copy(w19, 3, w23);
  /* #49: @4 = mac(@23,@19,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #50: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #51: @1 = (@1+@4) */
  w01 += w04;
  /* #52: @24 = @18[9:12] */
  for (rr=w24, cs=w18+9; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #53: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #54: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr26 = casadi_c0;
  /* #55: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #56: @28 = @18[6:9] */
  for (rr=w28, cs=w18+6; cs!=w18+9; cs+=1) *rr++ = *cs;
  /* #57: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #58: @30 = mac(@28,@29,@27) */
  casadi_copy(w27, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #59: @26 = (@26-@30) */
  for (i=0, rr=w26, cr=wr26, cs=w30; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #60: @31 = @20[9:12] */
  wr31 = wr20+9;
  /* #61: @32 = mac(@26,@31,@25) */
  casadi_copy(w25, 3, w32);
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=wr31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #62: @24 = (@24-@32) */
  for (i=0, rr=w24, cs=w32; i<3; ++i) (*rr++) -= (*cs++);
  /* #63: @32 = @24' */
  casadi_copy(w24, 3, w32);
  /* #64: @4 = mac(@32,@24,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #65: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #66: @1 = (@1+@4) */
  w01 += w04;
  /* #67: @4 = @20[12] */
  w04 = wr20[12];
  /* #68: @4 = (@4-@14) */
  w04 -= w14;
  /* #69: @14 = sq(@4) */
  w14 = casadi_sq( w04 );
  /* #70: @14 = (@2*@14) */
  w14  = (w02*w14);
  /* #71: @1 = (@1+@14) */
  w01 += w14;
  /* #72: @33 = @18[13:16] */
  for (rr=w33, cs=w18+13; cs!=w18+16; cs+=1) *rr++ = *cs;
  /* #73: @34 = @20[13:16] */
  wr34 = wr20+13;
  /* #74: @35 = mac(@26,@34,@25) */
  casadi_copy(w25, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=wr34+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #75: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #76: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #77: @0 = mac(@35,@33,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #78: @0 = (@2*@0) */
  w00  = (w02*w00);
  /* #79: @1 = (@1+@0) */
  w01 += w00;
  /* #80: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #81: @18 = zeros(16x1) */
  casadi_clear(w18, 16);
  /* #82: @33 = (@2*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #83: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #84: @35 = @35' */
  /* #85: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #86: (@18[13:16] += @33) */
  for (rr=w18+13, cs=w33; rr!=w18+16; rr+=1) *rr += *cs++;
  /* #87: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #88: @34 = @34' */
  /* #89: @26 = mac(@33,@34,@27) */
  casadi_copy(w27, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w33+j, ct=wr34+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #90: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #91: @33 = mac(@26,@28,@25) */
  casadi_copy(w25, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #93: @35 = mac(@29,@26,@34) */
  casadi_copy(w34, 3, w35);
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #94: @35 = @35' */
  /* #95: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #96: @24 = (@2*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #97: @32 = (@2*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #98: @32 = @32' */
  /* #99: @24 = (@24+@32) */
  for (i=0, rr=w24, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #100: @32 = (-@24) */
  for (i=0, rr=w32, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #101: @31 = @31' */
  /* #102: @27 = mac(@32,@31,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=wr31+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #103: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<9; ++i) *rr++ = (- *cs++ );
  /* #104: @25 = mac(@27,@28,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #105: @33 = (@33+@25) */
  for (i=0, rr=w33, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #106: @34 = mac(@29,@27,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @34 = @34' */
  /* #108: @33 = (@33+@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #109: (@18[6:9] += @33) */
  for (rr=w18+6, cs=w33; rr!=w18+9; rr+=1) *rr += *cs++;
  /* #110: (@18[9:12] += @24) */
  for (rr=w18+9, cs=w24; rr!=w18+12; rr+=1) *rr += *cs++;
  /* #111: @22 = @22' */
  /* #112: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #113: (@18[3:6] += @22) */
  for (rr=w18+3, cs=w22; rr!=w18+6; rr+=1) *rr += *cs++;
  /* #114: @21 = @21' */
  /* #115: @21 = (2.*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #116: (@18[:3] += @21) */
  for (rr=w18+0, cs=w21; rr!=w18+3; rr+=1) *rr += *cs++;
  /* #117: {@1, @0, @14, @6, @9, @8, @10, @11, @12, @13, @15, @16, @17, @36, @37, @38} = vertsplit(@18) */
  w01 = w18[0];
  w00 = w18[1];
  w14 = w18[2];
  w06 = w18[3];
  w09 = w18[4];
  w08 = w18[5];
  w10 = w18[6];
  w11 = w18[7];
  w12 = w18[8];
  w13 = w18[9];
  w15 = w18[10];
  w16 = w18[11];
  w17 = w18[12];
  w36 = w18[13];
  w37 = w18[14];
  w38 = w18[15];
  /* #118: output[1][0] = @1 */
  if (res[1]) res[1][0] = w01;
  /* #119: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #120: output[1][2] = @14 */
  if (res[1]) res[1][2] = w14;
  /* #121: output[1][3] = @6 */
  if (res[1]) res[1][3] = w06;
  /* #122: output[1][4] = @9 */
  if (res[1]) res[1][4] = w09;
  /* #123: output[1][5] = @8 */
  if (res[1]) res[1][5] = w08;
  /* #124: @19 = (@2*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #125: @23 = (@2*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #126: @23 = @23' */
  /* #127: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #128: {@8, @9, @6} = vertsplit(@19) */
  w08 = w19[0];
  w09 = w19[1];
  w06 = w19[2];
  /* #129: @14 = (@5*@9) */
  w14  = (w05*w09);
  /* #130: @0 = (@3*@6) */
  w00  = (w03*w06);
  /* #131: @14 = (@14-@0) */
  w14 -= w00;
  /* #132: @14 = (@14+@10) */
  w14 += w10;
  /* #133: output[1][6] = @14 */
  if (res[1]) res[1][6] = w14;
  /* #134: @6 = (@7*@6) */
  w06  = (w07*w06);
  /* #135: @5 = (@5*@8) */
  w05 *= w08;
  /* #136: @6 = (@6-@5) */
  w06 -= w05;
  /* #137: @6 = (@6+@11) */
  w06 += w11;
  /* #138: output[1][7] = @6 */
  if (res[1]) res[1][7] = w06;
  /* #139: @3 = (@3*@8) */
  w03 *= w08;
  /* #140: @7 = (@7*@9) */
  w07 *= w09;
  /* #141: @3 = (@3-@7) */
  w03 -= w07;
  /* #142: @3 = (@3+@12) */
  w03 += w12;
  /* #143: output[1][8] = @3 */
  if (res[1]) res[1][8] = w03;
  /* #144: output[1][9] = @13 */
  if (res[1]) res[1][9] = w13;
  /* #145: output[1][10] = @15 */
  if (res[1]) res[1][10] = w15;
  /* #146: output[1][11] = @16 */
  if (res[1]) res[1][11] = w16;
  /* #147: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #148: @2 = (@2*@4) */
  w02 *= w04;
  /* #149: @17 = (@17-@2) */
  w17 -= w02;
  /* #150: output[1][12] = @17 */
  if (res[1]) res[1][12] = w17;
  /* #151: output[1][13] = @36 */
  if (res[1]) res[1][13] = w36;
  /* #152: output[1][14] = @37 */
  if (res[1]) res[1][14] = w37;
  /* #153: output[1][15] = @38 */
  if (res[1]) res[1][15] = w38;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 126;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 126*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
