/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {44, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {16, 1, 1};

static const casadi_real casadi_zeros[16] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* planner_payload_cost_ext_cost_fun_jac:(i0[12],i1[4],i2[0],i3[44])->(o0,o1[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, *w14=w+15, *w15=w+27, *w17=w+46, *w18=w+49, *w19=w+52, *w20=w+55, *w21=w+58, *w22=w+62, *w23=w+65;
  casadi_real *w24=w+68, w25, w26;
  const casadi_real *cr, *cs, *ct, *wr16, *wr17, *wr18, *wr20;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = 5000 */
  w01 = 5000.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:3] */
  for (rr=w15, cs=w14+0; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #16: @16 = input[3][0] */
  wr16 = arg[3] ? arg[3] : casadi_zeros;
  /* #17: @17 = @16[:3] */
  wr17 = wr16+0;
  /* #18: @15 = (@15-@17) */
  for (i=0, rr=w15, cs=wr17; i<3; ++i) (*rr++) -= (*cs++);
  /* #19: @17 = @15' */
  casadi_copy(w15, 3, w17);
  /* #20: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #21: @1 = mac(@17,@15,@0) */
  casadi_copy((&w00), 1, (&w01));
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #22: @2 = 0.275 */
  w02 = 2.7500000000000002e-01;
  /* #23: @15 = @14[3:6] */
  for (rr=w15, cs=w14+3; cs!=w14+6; cs+=1) *rr++ = *cs;
  /* #24: @18 = @16[3:6] */
  wr18 = wr16+3;
  /* #25: @15 = (@15-@18) */
  for (i=0, rr=w15, cs=wr18; i<3; ++i) (*rr++) -= (*cs++);
  /* #26: @18 = @15' */
  casadi_copy(w15, 3, w18);
  /* #27: @18 = (@2*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #28: @2 = mac(@18,@15,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w18+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #29: @1 = (@1+@2) */
  w01 += w02;
  /* #30: @2 = 0.1 */
  w02 = 1.0000000000000001e-01;
  /* #31: @3 = @16[7] */
  w03 = wr16[7];
  /* #32: @4 = (@3*@10) */
  w04  = (w03*w10);
  /* #33: @5 = @16[8] */
  w05 = wr16[8];
  /* #34: @6 = (@5*@9) */
  w06  = (w05*w09);
  /* #35: @4 = (@4-@6) */
  w04 -= w06;
  /* #36: @6 = (@5*@8) */
  w06  = (w05*w08);
  /* #37: @7 = @16[6] */
  w07 = wr16[6];
  /* #38: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #39: @6 = (@6-@10) */
  w06 -= w10;
  /* #40: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #41: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #42: @9 = (@9-@8) */
  w09 -= w08;
  /* #43: @15 = vertcat(@4, @6, @9) */
  rr=w15;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w09;
  /* #44: @19 = @15' */
  casadi_copy(w15, 3, w19);
  /* #45: @4 = mac(@19,@15,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w19+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #46: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #47: @1 = (@1+@4) */
  w01 += w04;
  /* #48: @4 = 20 */
  w04 = 20.;
  /* #49: @6 = @16[12] */
  w06 = wr16[12];
  /* #50: @9 = input[1][0] */
  w09 = arg[1] ? arg[1][0] : 0;
  /* #51: @6 = (@6-@9) */
  w06 -= w09;
  /* #52: @8 = sq(@6) */
  w08 = casadi_sq( w06 );
  /* #53: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #54: @1 = (@1+@8) */
  w01 += w08;
  /* #55: @20 = @16[13:16] */
  wr20 = wr16+13;
  /* #56: @8 = input[1][1] */
  w08 = arg[1] ? arg[1][1] : 0;
  /* #57: @10 = input[1][2] */
  w10 = arg[1] ? arg[1][2] : 0;
  /* #58: @11 = input[1][3] */
  w11 = arg[1] ? arg[1][3] : 0;
  /* #59: @21 = vertcat(@9, @8, @10, @11) */
  rr=w21;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w11;
  /* #60: @22 = @21[1:4] */
  for (rr=w22, cs=w21+1; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #61: @20 = (@20-@22) */
  for (i=0, rr=w20, cr=wr20, cs=w22; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #62: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #63: @0 = mac(@22,@20,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #64: @0 = (@4*@0) */
  w00  = (w04*w00);
  /* #65: @1 = (@1+@0) */
  w01 += w00;
  /* #66: @0 = 10 */
  w00 = 10.;
  /* #67: @23 = @14[6:9] */
  for (rr=w23, cs=w14+6; cs!=w14+9; cs+=1) *rr++ = *cs;
  /* #68: @24 = @14[9:12] */
  for (rr=w24, cs=w14+9; cs!=w14+12; cs+=1) *rr++ = *cs;
  /* #69: @9 = dot(@23, @24) */
  w09 = casadi_dot(3, w23, w24);
  /* #70: @8 = sq(@9) */
  w08 = casadi_sq( w09 );
  /* #71: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #72: @1 = (@1+@8) */
  w01 += w08;
  /* #73: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #74: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #75: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #76: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #77: @22 = @22' */
  /* #78: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #79: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #80: (@21[1:4] += @20) */
  for (rr=w21+1, cs=w20; rr!=w21+4; rr+=1) *rr += *cs++;
  /* #81: {@1, @8, @10, @11} = vertsplit(@21) */
  w01 = w21[0];
  w08 = w21[1];
  w10 = w21[2];
  w11 = w21[3];
  /* #82: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #83: @4 = (@4*@6) */
  w04 *= w06;
  /* #84: @1 = (@1-@4) */
  w01 -= w04;
  /* #85: output[1][0] = @1 */
  if (res[1]) res[1][0] = w01;
  /* #86: output[1][1] = @8 */
  if (res[1]) res[1][1] = w08;
  /* #87: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #88: output[1][3] = @11 */
  if (res[1]) res[1][3] = w11;
  /* #89: @14 = zeros(12x1) */
  casadi_clear(w14, 12);
  /* #90: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #91: @0 = (@0*@9) */
  w00 *= w09;
  /* #92: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #93: (@14[9:12] += @23) */
  for (rr=w14+9, cs=w23; rr!=w14+12; rr+=1) *rr += *cs++;
  /* #94: @24 = (@0*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #95: (@14[6:9] += @24) */
  for (rr=w14+6, cs=w24; rr!=w14+9; rr+=1) *rr += *cs++;
  /* #96: @18 = @18' */
  /* #97: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #98: (@14[3:6] += @18) */
  for (rr=w14+3, cs=w18; rr!=w14+6; rr+=1) *rr += *cs++;
  /* #99: @17 = @17' */
  /* #100: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #101: (@14[:3] += @17) */
  for (rr=w14+0, cs=w17; rr!=w14+3; rr+=1) *rr += *cs++;
  /* #102: {@0, @9, @11, @10, @8, @1, @4, @6, @12, @13, @25, @26} = vertsplit(@14) */
  w00 = w14[0];
  w09 = w14[1];
  w11 = w14[2];
  w10 = w14[3];
  w08 = w14[4];
  w01 = w14[5];
  w04 = w14[6];
  w06 = w14[7];
  w12 = w14[8];
  w13 = w14[9];
  w25 = w14[10];
  w26 = w14[11];
  /* #103: output[1][4] = @0 */
  if (res[1]) res[1][4] = w00;
  /* #104: output[1][5] = @9 */
  if (res[1]) res[1][5] = w09;
  /* #105: output[1][6] = @11 */
  if (res[1]) res[1][6] = w11;
  /* #106: output[1][7] = @10 */
  if (res[1]) res[1][7] = w10;
  /* #107: output[1][8] = @8 */
  if (res[1]) res[1][8] = w08;
  /* #108: output[1][9] = @1 */
  if (res[1]) res[1][9] = w01;
  /* #109: @15 = (@2*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #110: @19 = (@2*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #111: @19 = @19' */
  /* #112: @15 = (@15+@19) */
  for (i=0, rr=w15, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #113: {@2, @1, @8} = vertsplit(@15) */
  w02 = w15[0];
  w01 = w15[1];
  w08 = w15[2];
  /* #114: @10 = (@5*@1) */
  w10  = (w05*w01);
  /* #115: @11 = (@3*@8) */
  w11  = (w03*w08);
  /* #116: @10 = (@10-@11) */
  w10 -= w11;
  /* #117: @10 = (@10+@4) */
  w10 += w04;
  /* #118: output[1][10] = @10 */
  if (res[1]) res[1][10] = w10;
  /* #119: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #120: @5 = (@5*@2) */
  w05 *= w02;
  /* #121: @8 = (@8-@5) */
  w08 -= w05;
  /* #122: @8 = (@8+@6) */
  w08 += w06;
  /* #123: output[1][11] = @8 */
  if (res[1]) res[1][11] = w08;
  /* #124: @3 = (@3*@2) */
  w03 *= w02;
  /* #125: @7 = (@7*@1) */
  w07 *= w01;
  /* #126: @3 = (@3-@7) */
  w03 -= w07;
  /* #127: @3 = (@3+@12) */
  w03 += w12;
  /* #128: output[1][12] = @3 */
  if (res[1]) res[1][12] = w03;
  /* #129: output[1][13] = @13 */
  if (res[1]) res[1][13] = w13;
  /* #130: output[1][14] = @25 */
  if (res[1]) res[1][14] = w25;
  /* #131: output[1][15] = @26 */
  if (res[1]) res[1][15] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 73;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 73*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
