/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {56, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[20] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* planner_payload_cost_ext_cost_e_fun_jac:(i0[16],i1[0],i2[0],i3[56])->(o0,o1[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+19, *w19=w+35, *w21=w+58, *w22=w+61, *w23=w+64;
  const casadi_real *cs, *ct, *wr20, *wr21, *wr22;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = 5000 */
  w01 = 5000.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = input[0][15] */
  w17 = arg[0] ? arg[0][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:3] */
  for (rr=w19, cs=w18+0; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #20: @20 = input[3][0] */
  wr20 = arg[3] ? arg[3] : casadi_zeros;
  /* #21: @21 = @20[:3] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<3; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 3, w21);
  /* #24: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #25: @1 = mac(@21,@19,@0) */
  casadi_copy((&w00), 1, (&w01));
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #26: @2 = 0.282 */
  w02 = 2.8199999999999997e-01;
  /* #27: @19 = @18[3:6] */
  for (rr=w19, cs=w18+3; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #28: @22 = @20[3:6] */
  wr22 = wr20+3;
  /* #29: @19 = (@19-@22) */
  for (i=0, rr=w19, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #30: @22 = @19' */
  casadi_copy(w19, 3, w22);
  /* #31: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #32: @0 = mac(@22,@19,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #33: @1 = (@1+@0) */
  w01 += w00;
  /* #34: @0 = 50 */
  w00 = 50.;
  /* #35: @2 = @20[12] */
  w02 = wr20[12];
  /* #36: @2 = (@2-@14) */
  w02 -= w14;
  /* #37: @14 = sq(@2) */
  w14 = casadi_sq( w02 );
  /* #38: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #39: @1 = (@1+@14) */
  w01 += w14;
  /* #40: @14 = 0.1 */
  w14 = 1.0000000000000001e-01;
  /* #41: @19 = @18[6:9] */
  for (rr=w19, cs=w18+6; cs!=w18+9; cs+=1) *rr++ = *cs;
  /* #42: @23 = @18[9:12] */
  for (rr=w23, cs=w18+9; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #43: @3 = dot(@19, @23) */
  w03 = casadi_dot(3, w19, w23);
  /* #44: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #45: @4 = (@14*@4) */
  w04  = (w14*w04);
  /* #46: @1 = (@1+@4) */
  w01 += w04;
  /* #47: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #48: @18 = zeros(16x1) */
  casadi_clear(w18, 16);
  /* #49: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #50: @14 = (@14*@3) */
  w14 *= w03;
  /* #51: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #52: (@18[9:12] += @19) */
  for (rr=w18+9, cs=w19; rr!=w18+12; rr+=1) *rr += *cs++;
  /* #53: @23 = (@14*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #54: (@18[6:9] += @23) */
  for (rr=w18+6, cs=w23; rr!=w18+9; rr+=1) *rr += *cs++;
  /* #55: @22 = @22' */
  /* #56: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #57: (@18[3:6] += @22) */
  for (rr=w18+3, cs=w22; rr!=w18+6; rr+=1) *rr += *cs++;
  /* #58: @21 = @21' */
  /* #59: @21 = (2.*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #60: (@18[:3] += @21) */
  for (rr=w18+0, cs=w21; rr!=w18+3; rr+=1) *rr += *cs++;
  /* #61: {@14, @3, @1, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @15, @16, @17} = vertsplit(@18) */
  w14 = w18[0];
  w03 = w18[1];
  w01 = w18[2];
  w04 = w18[3];
  w05 = w18[4];
  w06 = w18[5];
  w07 = w18[6];
  w08 = w18[7];
  w09 = w18[8];
  w10 = w18[9];
  w11 = w18[10];
  w12 = w18[11];
  w13 = w18[12];
  w15 = w18[13];
  w16 = w18[14];
  w17 = w18[15];
  /* #62: output[1][0] = @14 */
  if (res[1]) res[1][0] = w14;
  /* #63: output[1][1] = @3 */
  if (res[1]) res[1][1] = w03;
  /* #64: output[1][2] = @1 */
  if (res[1]) res[1][2] = w01;
  /* #65: output[1][3] = @4 */
  if (res[1]) res[1][3] = w04;
  /* #66: output[1][4] = @5 */
  if (res[1]) res[1][4] = w05;
  /* #67: output[1][5] = @6 */
  if (res[1]) res[1][5] = w06;
  /* #68: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #69: output[1][7] = @8 */
  if (res[1]) res[1][7] = w08;
  /* #70: output[1][8] = @9 */
  if (res[1]) res[1][8] = w09;
  /* #71: output[1][9] = @10 */
  if (res[1]) res[1][9] = w10;
  /* #72: output[1][10] = @11 */
  if (res[1]) res[1][10] = w11;
  /* #73: output[1][11] = @12 */
  if (res[1]) res[1][11] = w12;
  /* #74: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #75: @0 = (@0*@2) */
  w00 *= w02;
  /* #76: @13 = (@13-@0) */
  w13 -= w00;
  /* #77: output[1][12] = @13 */
  if (res[1]) res[1][12] = w13;
  /* #78: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #79: output[1][14] = @16 */
  if (res[1]) res[1][14] = w16;
  /* #80: output[1][15] = @17 */
  if (res[1]) res[1][15] = w17;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 67;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 67*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
