/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[20] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 15,
  46, 47, 48, 49};
static const casadi_int casadi_s2[20] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 16, 22, 28, 34, 40,
  46, 47, 48, 49};
static const casadi_int casadi_s3[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s5[73] = 
  {20, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 16, 22, 28,
  34, 40, 46, 47, 48, 49, 50, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 10,
  11, 12, 13, 14, 15, 10, 11, 12,
  13, 14, 15, 10, 11, 12, 13, 14,
  15, 10, 11, 12, 13, 14, 15, 10,
  11, 12, 13, 14, 15, 16, 17, 18,
  19};
static const casadi_int casadi_s6[3] = {16, 1, 1};
static const casadi_int casadi_s7[3] = {4, 1, 1};
static const casadi_int casadi_s8[3] = {0, 1, 1};
static const casadi_int casadi_s9[3] = {56, 1, 1};
static const casadi_int casadi_s10[3] = {1, 1, 1};
static const casadi_int casadi_s11[3] = {20, 1, 1};
static const casadi_int casadi_s12[3] = {0, 0, 1};
static const casadi_int casadi_s13[3] = {0, 20, 1};

static const casadi_real casadi_zeros[20] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* planner_payload_cost_ext_cost_0_fun_jac_hess:(i0[16],i1[4],i2[0],i3[56])->(o0,o1[20],o2[20x20,50nz],o3[],o4[0x20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+19, *w19=w+35, *w20=w+38, *w21=w+58, *w22=w+61;
  casadi_real *w23=w+64, *w24=w+67, *w25=w+70, *w26=w+73, *w27=w+76, *w28=w+79, *w29=w+82, *w30=w+86, *w31=w+89, *w32=w+92, *w33=w+95, *w34=w+99;
  casadi_real w35, w36, w37, w38, w39, w40, w41, w42, *w43=w+123, *w44=w+173, *w46=w+188, w47;
  casadi_real w48, w49, *w50=w+202, *w51=w+204, w52, w53, *w54=w+208, *w55=w+214;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr20, *wr21, *wr22, *wr24, *wr27;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = 5000 */
  w01 = 5000.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = input[0][15] */
  w17 = arg[0] ? arg[0][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:3] */
  for (rr=w19, cs=w18+0; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #20: @20 = input[3][0] */
  wr20 = arg[3] ? arg[3] : casadi_zeros;
  /* #21: @21 = @20[:3] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<3; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 3, w21);
  /* #24: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #25: @2 = mac(@21,@19,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #26: @3 = 0.282 */
  w03 = 2.8199999999999997e-01;
  /* #27: @19 = @18[3:6] */
  for (rr=w19, cs=w18+3; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #28: @22 = @20[3:6] */
  wr22 = wr20+3;
  /* #29: @19 = (@19-@22) */
  for (i=0, rr=w19, cs=wr22; i<3; ++i) (*rr++) -= (*cs++);
  /* #30: @22 = @19' */
  casadi_copy(w19, 3, w22);
  /* #31: @22 = (@3*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #32: @4 = mac(@22,@19,@0) */
  casadi_copy((&w00), 1, (&w04));
  for (i=0, rr=(&w04); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #33: @2 = (@2+@4) */
  w02 += w04;
  /* #34: @4 = 0.1 */
  w04 = 1.0000000000000001e-01;
  /* #35: @5 = @20[7] */
  w05 = wr20[7];
  /* #36: @6 = (@5*@10) */
  w06  = (w05*w10);
  /* #37: @7 = @20[8] */
  w07 = wr20[8];
  /* #38: @11 = (@7*@9) */
  w11  = (w07*w09);
  /* #39: @6 = (@6-@11) */
  w06 -= w11;
  /* #40: @11 = (@7*@8) */
  w11  = (w07*w08);
  /* #41: @12 = @20[6] */
  w12 = wr20[6];
  /* #42: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #43: @11 = (@11-@10) */
  w11 -= w10;
  /* #44: @9 = (@12*@9) */
  w09  = (w12*w09);
  /* #45: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #46: @9 = (@9-@8) */
  w09 -= w08;
  /* #47: @19 = vertcat(@6, @11, @9) */
  rr=w19;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w09;
  /* #48: @23 = @19' */
  casadi_copy(w19, 3, w23);
  /* #49: @6 = mac(@23,@19,@0) */
  casadi_copy((&w00), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #50: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #51: @2 = (@2+@6) */
  w02 += w06;
  /* #52: @24 = @20[9:12] */
  wr24 = wr20+9;
  /* #53: @25 = @18[9:12] */
  for (rr=w25, cs=w18+9; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #54: @24 = (@24-@25) */
  for (i=0, rr=w24, cr=wr24, cs=w25; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #55: @26 = @24' */
  casadi_copy(w24, 3, w26);
  /* #56: @6 = mac(@26,@24,@0) */
  casadi_copy((&w00), 1, (&w06));
  for (i=0, rr=(&w06); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w26+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #57: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #58: @2 = (@2+@6) */
  w02 += w06;
  /* #59: @6 = 50 */
  w06 = 50.;
  /* #60: @11 = @20[12] */
  w11 = wr20[12];
  /* #61: @11 = (@11-@14) */
  w11 -= w14;
  /* #62: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #63: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #64: @2 = (@2+@14) */
  w02 += w14;
  /* #65: @27 = @20[13:16] */
  wr27 = wr20+13;
  /* #66: @28 = @18[13:16] */
  for (rr=w28, cs=w18+13; cs!=w18+16; cs+=1) *rr++ = *cs;
  /* #67: @27 = (@27-@28) */
  for (i=0, rr=w27, cr=wr27, cs=w28; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #68: @28 = @27' */
  casadi_copy(w27, 3, w28);
  /* #69: @14 = mac(@28,@27,@0) */
  casadi_copy((&w00), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #70: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #71: @2 = (@2+@14) */
  w02 += w14;
  /* #72: @14 = 0.01 */
  w14 = 1.0000000000000000e-02;
  /* #73: @9 = input[1][0] */
  w09 = arg[1] ? arg[1][0] : 0;
  /* #74: @8 = sq(@9) */
  w08 = casadi_sq( w09 );
  /* #75: @8 = (@14*@8) */
  w08  = (w14*w08);
  /* #76: @2 = (@2+@8) */
  w02 += w08;
  /* #77: @8 = input[1][1] */
  w08 = arg[1] ? arg[1][1] : 0;
  /* #78: @10 = input[1][2] */
  w10 = arg[1] ? arg[1][2] : 0;
  /* #79: @13 = input[1][3] */
  w13 = arg[1] ? arg[1][3] : 0;
  /* #80: @29 = vertcat(@9, @8, @10, @13) */
  rr=w29;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w13;
  /* #81: @30 = @29[1:4] */
  for (rr=w30, cs=w29+1; cs!=w29+4; cs+=1) *rr++ = *cs;
  /* #82: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #83: @0 = mac(@31,@30,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w31+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #84: @0 = (@14*@0) */
  w00  = (w14*w00);
  /* #85: @2 = (@2+@0) */
  w02 += w00;
  /* #86: @32 = @18[6:9] */
  for (rr=w32, cs=w18+6; cs!=w18+9; cs+=1) *rr++ = *cs;
  /* #87: @0 = dot(@32, @25) */
  w00 = casadi_dot(3, w32, w25);
  /* #88: @8 = sq(@0) */
  w08 = casadi_sq( w00 );
  /* #89: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #90: @2 = (@2+@8) */
  w02 += w08;
  /* #91: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #92: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #93: @30 = (@14*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #94: @31 = (@14*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #95: @31 = @31' */
  /* #96: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #97: @33 = @29; (@33[1:4] += @30) */
  casadi_copy(w29, 4, w33);
  for (rr=w33+1, cs=w30; rr!=w33+4; rr+=1) *rr += *cs++;
  /* #98: {@2, @8, @10, @13} = vertsplit(@33) */
  w02 = w33[0];
  w08 = w33[1];
  w10 = w33[2];
  w13 = w33[3];
  /* #99: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #100: @9 = (@14*@9) */
  w09  = (w14*w09);
  /* #101: @2 = (@2+@9) */
  w02 += w09;
  /* #102: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #103: output[1][1] = @8 */
  if (res[1]) res[1][1] = w08;
  /* #104: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #105: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #106: @18 = zeros(16x1) */
  casadi_clear(w18, 16);
  /* #107: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #108: @0 = (@4*@0) */
  w00  = (w04*w00);
  /* #109: @30 = (@0*@25) */
  for (i=0, rr=w30, cs=w25; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #110: @34 = @18; (@34[6:9] += @30) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w30; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #111: @27 = (@6*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #112: @28 = (@6*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #113: @28 = @28' */
  /* #114: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #115: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #116: (@34[13:16] += @27) */
  for (rr=w34+13, cs=w27; rr!=w34+16; rr+=1) *rr += *cs++;
  /* #117: @27 = (@0*@32) */
  for (i=0, rr=w27, cs=w32; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #118: @24 = (@4*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #119: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #120: @26 = @26' */
  /* #121: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @27 = (@27-@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #123: (@34[9:12] += @27) */
  for (rr=w34+9, cs=w27; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #124: @22 = @22' */
  /* #125: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #126: (@34[3:6] += @22) */
  for (rr=w34+3, cs=w22; rr!=w34+6; rr+=1) *rr += *cs++;
  /* #127: @21 = @21' */
  /* #128: @21 = (2.*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #129: (@34[:3] += @21) */
  for (rr=w34+0, cs=w21; rr!=w34+3; rr+=1) *rr += *cs++;
  /* #130: {@13, @10, @8, @2, @9, @15, @16, @17, @35, @36, @37, @38, @39, @40, @41, @42} = vertsplit(@34) */
  w13 = w34[0];
  w10 = w34[1];
  w08 = w34[2];
  w02 = w34[3];
  w09 = w34[4];
  w15 = w34[5];
  w16 = w34[6];
  w17 = w34[7];
  w35 = w34[8];
  w36 = w34[9];
  w37 = w34[10];
  w38 = w34[11];
  w39 = w34[12];
  w40 = w34[13];
  w41 = w34[14];
  w42 = w34[15];
  /* #131: output[1][4] = @13 */
  if (res[1]) res[1][4] = w13;
  /* #132: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #133: output[1][6] = @8 */
  if (res[1]) res[1][6] = w08;
  /* #134: output[1][7] = @2 */
  if (res[1]) res[1][7] = w02;
  /* #135: output[1][8] = @9 */
  if (res[1]) res[1][8] = w09;
  /* #136: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #137: @19 = (@4*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #138: @23 = (@4*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #139: @23 = @23' */
  /* #140: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #141: {@15, @9, @2} = vertsplit(@19) */
  w15 = w19[0];
  w09 = w19[1];
  w02 = w19[2];
  /* #142: @8 = (@7*@9) */
  w08  = (w07*w09);
  /* #143: @10 = (@5*@2) */
  w10  = (w05*w02);
  /* #144: @8 = (@8-@10) */
  w08 -= w10;
  /* #145: @8 = (@8+@16) */
  w08 += w16;
  /* #146: output[1][10] = @8 */
  if (res[1]) res[1][10] = w08;
  /* #147: @2 = (@12*@2) */
  w02  = (w12*w02);
  /* #148: @8 = (@7*@15) */
  w08  = (w07*w15);
  /* #149: @2 = (@2-@8) */
  w02 -= w08;
  /* #150: @2 = (@2+@17) */
  w02 += w17;
  /* #151: output[1][11] = @2 */
  if (res[1]) res[1][11] = w02;
  /* #152: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #153: @9 = (@12*@9) */
  w09  = (w12*w09);
  /* #154: @15 = (@15-@9) */
  w15 -= w09;
  /* #155: @15 = (@15+@35) */
  w15 += w35;
  /* #156: output[1][12] = @15 */
  if (res[1]) res[1][12] = w15;
  /* #157: output[1][13] = @36 */
  if (res[1]) res[1][13] = w36;
  /* #158: output[1][14] = @37 */
  if (res[1]) res[1][14] = w37;
  /* #159: output[1][15] = @38 */
  if (res[1]) res[1][15] = w38;
  /* #160: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #161: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #162: @39 = (@39-@11) */
  w39 -= w11;
  /* #163: output[1][16] = @39 */
  if (res[1]) res[1][16] = w39;
  /* #164: output[1][17] = @40 */
  if (res[1]) res[1][17] = w40;
  /* #165: output[1][18] = @41 */
  if (res[1]) res[1][18] = w41;
  /* #166: output[1][19] = @42 */
  if (res[1]) res[1][19] = w42;
  /* #167: @43 = zeros(20x20,50nz) */
  casadi_clear(w43, 50);
  /* #168: @44 = ones(20x1,15nz) */
  casadi_fill(w44, 15, 1.);
  /* #169: {@42, @41, @40, @39, @11, @38, @37, @36, @15, @35, @9, NULL, NULL, NULL, NULL, NULL, @2, @17, @8, @16} = vertsplit(@44) */
  w42 = w44[0];
  w41 = w44[1];
  w40 = w44[2];
  w39 = w44[3];
  w11 = w44[4];
  w38 = w44[5];
  w37 = w44[6];
  w36 = w44[7];
  w15 = w44[8];
  w35 = w44[9];
  w09 = w44[10];
  w02 = w44[11];
  w17 = w44[12];
  w08 = w44[13];
  w16 = w44[14];
  /* #170: @33 = vertcat(@42, @41, @40, @39) */
  rr=w33;
  *rr++ = w42;
  *rr++ = w41;
  *rr++ = w40;
  *rr++ = w39;
  /* #171: @19 = @33[1:4] */
  for (rr=w19, cs=w33+1; cs!=w33+4; cs+=1) *rr++ = *cs;
  /* #172: @23 = (@14*@19) */
  for (i=0, rr=w23, cs=w19; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #173: @19 = @19' */
  /* #174: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #175: @19 = @19' */
  /* #176: @23 = (@23+@19) */
  for (i=0, rr=w23, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #177: (@29[1:4] += @23) */
  for (rr=w29+1, cs=w23; rr!=w29+4; rr+=1) *rr += *cs++;
  /* #178: {@41, @40, @39, @10} = vertsplit(@29) */
  w41 = w29[0];
  w40 = w29[1];
  w39 = w29[2];
  w10 = w29[3];
  /* #179: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #180: @14 = (@14*@42) */
  w14 *= w42;
  /* #181: @41 = (@41+@14) */
  w41 += w14;
  /* #182: @14 = sparsity_cast(@9) */
  w14 = w09;
  /* #183: @42 = project(@25) */
  casadi_sparsify(w25, (&w42), casadi_s0, 0);
  /* #184: @13 = dot(@14, @42) */
  w13 = casadi_dot(1, (&w14), (&w42));
  /* #185: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #186: @13 = (@4*@13) */
  w13  = (w04*w13);
  /* #187: @23 = (@25*@13) */
  for (i=0, rr=w23, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w13);
  /* #188: @34 = @18; (@34[6:9] += @23) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w23; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #189: @45 = 00 */
  /* #190: @46 = vertcat(@11, @38, @37, @36, @15, @35, @9, @45, @45, @45, @45, @45, @2, @17, @8, @16) */
  rr=w46;
  *rr++ = w11;
  *rr++ = w38;
  *rr++ = w37;
  *rr++ = w36;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w09;
  *rr++ = w02;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  /* #191: @23 = @46[8:11] */
  for (rr=w23, cs=w46+8; cs!=w46+11; cs+=1) *rr++ = *cs;
  /* #192: @19 = (-@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #193: @19 = @19' */
  /* #194: @19 = (@6*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #195: @19 = @19' */
  /* #196: @23 = (@6*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #197: @19 = (@19-@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) -= (*cs++);
  /* #198: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #199: (@34[13:16] += @19) */
  for (rr=w34+13, cs=w19; rr!=w34+16; rr+=1) *rr += *cs++;
  /* #200: @19 = (@32*@13) */
  for (i=0, rr=w19, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w13);
  /* #201: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #202: @23 = dense(@14) */
  casadi_densify((&w14), casadi_s0, w23, 0);
  /* #203: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #204: (@34[9:12] += @19) */
  for (rr=w34+9, cs=w19; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #205: @19 = @46[3:6] */
  for (rr=w19, cs=w46+3; cs!=w46+6; cs+=1) *rr++ = *cs;
  /* #206: @19 = @19' */
  /* #207: @19 = (@3*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #208: @19 = @19' */
  /* #209: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #210: (@34[3:6] += @19) */
  for (rr=w34+3, cs=w19; rr!=w34+6; rr+=1) *rr += *cs++;
  /* #211: @19 = @46[:3] */
  for (rr=w19, cs=w46+0; cs!=w46+3; cs+=1) *rr++ = *cs;
  /* #212: @19 = @19' */
  /* #213: @19 = (@1*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #214: @19 = @19' */
  /* #215: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #216: (@34[:3] += @19) */
  for (rr=w34+0, cs=w19; rr!=w34+3; rr+=1) *rr += *cs++;
  /* #217: {@1, @3, @14, @13, @11, @38, @37, @36, @15, @35, @17, @8, @16, @42, @47, @48} = vertsplit(@34) */
  w01 = w34[0];
  w03 = w34[1];
  w14 = w34[2];
  w13 = w34[3];
  w11 = w34[4];
  w38 = w34[5];
  w37 = w34[6];
  w36 = w34[7];
  w15 = w34[8];
  w35 = w34[9];
  w17 = w34[10];
  w08 = w34[11];
  w16 = w34[12];
  w42 = w34[13];
  w47 = w34[14];
  w48 = w34[15];
  /* #218: @49 = (@7*@9) */
  w49  = (w07*w09);
  /* #219: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #220: @9 = (-@9) */
  w09 = (- w09 );
  /* #221: @50 = vertcat(@45, @49, @9) */
  rr=w50;
  *rr++ = w49;
  *rr++ = w09;
  /* #222: @51 = (@4*@50) */
  for (i=0, rr=w51, cs=w50; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #223: @50 = @50' */
  /* #224: @50 = (@4*@50) */
  for (i=0, rr=w50, cs=w50; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #225: @50 = @50' */
  /* #226: @51 = (@51+@50) */
  for (i=0, rr=w51, cs=w50; i<2; ++i) (*rr++) += (*cs++);
  /* #227: {NULL, @49, @9} = vertsplit(@51) */
  w49 = w51[0];
  w09 = w51[1];
  /* #228: @52 = (@7*@49) */
  w52  = (w07*w49);
  /* #229: @53 = (@5*@9) */
  w53  = (w05*w09);
  /* #230: @52 = (@52-@53) */
  w52 -= w53;
  /* #231: @52 = (@52+@37) */
  w52 += w37;
  /* #232: @9 = (@12*@9) */
  w09  = (w12*w09);
  /* #233: @9 = (@9+@36) */
  w09 += w36;
  /* #234: @49 = (@12*@49) */
  w49  = (w12*w49);
  /* #235: @15 = (@15-@49) */
  w15 -= w49;
  /* #236: @2 = (-@2) */
  w02 = (- w02 );
  /* #237: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #238: @6 = (@6*@2) */
  w06 *= w02;
  /* #239: @16 = (@16-@6) */
  w16 -= w06;
  /* #240: @20 = vertcat(@41, @40, @39, @10, @1, @3, @14, @13, @11, @38, @52, @9, @15, @35, @17, @8, @16, @42, @47, @48) */
  rr=w20;
  *rr++ = w41;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w10;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w38;
  *rr++ = w52;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w42;
  *rr++ = w47;
  *rr++ = w48;
  /* #241: (@43[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 46, 47, 48, 49] = @20) */
  for (cii=casadi_s1, rr=w43, cs=w20; cii!=casadi_s1+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #242: (@43[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 22, 28, 34, 40, 46, 47, 48, 49] = @20) */
  for (cii=casadi_s2, rr=w43, cs=w20; cii!=casadi_s2+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #243: @41 = ones(20x1,1nz) */
  w41 = 1.;
  /* #244: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@41) */
  w40 = w41;
  /* #245: @41 = sparsity_cast(@40) */
  w41 = w40;
  /* #246: @39 = project(@25) */
  casadi_sparsify(w25, (&w39), casadi_s3, 0);
  /* #247: @10 = dot(@41, @39) */
  w10 = casadi_dot(1, (&w41), (&w39));
  /* #248: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #249: @10 = (@4*@10) */
  w10  = (w04*w10);
  /* #250: @19 = (@25*@10) */
  for (i=0, rr=w19, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #251: @34 = @18; (@34[6:9] += @19) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w19; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #252: @19 = (@32*@10) */
  for (i=0, rr=w19, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #253: @41 = (@0*@41) */
  w41  = (w00*w41);
  /* #254: @23 = dense(@41) */
  casadi_densify((&w41), casadi_s3, w23, 0);
  /* #255: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #256: (@34[9:12] += @19) */
  for (rr=w34+9, cs=w19; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #257: {@41, @10, @39, @1, @3, @14, @13, @11, @38, @52, @9, @15, @35, @17, @8, @16} = vertsplit(@34) */
  w41 = w34[0];
  w10 = w34[1];
  w39 = w34[2];
  w01 = w34[3];
  w03 = w34[4];
  w14 = w34[5];
  w13 = w34[6];
  w11 = w34[7];
  w38 = w34[8];
  w52 = w34[9];
  w09 = w34[10];
  w15 = w34[11];
  w35 = w34[12];
  w17 = w34[13];
  w08 = w34[14];
  w16 = w34[15];
  /* #258: @42 = (@7*@40) */
  w42  = (w07*w40);
  /* #259: @42 = (-@42) */
  w42 = (- w42 );
  /* #260: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #261: @51 = vertcat(@42, @45, @40) */
  rr=w51;
  *rr++ = w42;
  *rr++ = w40;
  /* #262: @50 = (@4*@51) */
  for (i=0, rr=w50, cs=w51; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #263: @51 = @51' */
  /* #264: @51 = (@4*@51) */
  for (i=0, rr=w51, cs=w51; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #265: @51 = @51' */
  /* #266: @50 = (@50+@51) */
  for (i=0, rr=w50, cs=w51; i<2; ++i) (*rr++) += (*cs++);
  /* #267: {@42, NULL, @40} = vertsplit(@50) */
  w42 = w50[0];
  w40 = w50[1];
  /* #268: @47 = (@5*@40) */
  w47  = (w05*w40);
  /* #269: @13 = (@13-@47) */
  w13 -= w47;
  /* #270: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #271: @47 = (@7*@42) */
  w47  = (w07*w42);
  /* #272: @40 = (@40-@47) */
  w40 -= w47;
  /* #273: @40 = (@40+@11) */
  w40 += w11;
  /* #274: @42 = (@5*@42) */
  w42  = (w05*w42);
  /* #275: @42 = (@42+@38) */
  w42 += w38;
  /* #276: @34 = vertcat(@45, @45, @45, @45, @41, @10, @39, @1, @3, @14, @13, @40, @42, @52, @9, @15, @35, @17, @8, @16) */
  rr=w34;
  *rr++ = w41;
  *rr++ = w10;
  *rr++ = w39;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w42;
  *rr++ = w52;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  /* #277: @54 = @34[6:12] */
  for (rr=w54, cs=w34+6; cs!=w34+12; cs+=1) *rr++ = *cs;
  /* #278: (@43[16:22] = @54) */
  for (rr=w43+16, cs=w54; rr!=w43+22; rr+=1) *rr = *cs++;
  /* #279: (@43[11:47:6] = @54) */
  for (rr=w43+11, cs=w54; rr!=w43+47; rr+=6) *rr = *cs++;
  /* #280: @41 = ones(20x1,1nz) */
  w41 = 1.;
  /* #281: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@41) */
  w10 = w41;
  /* #282: @41 = sparsity_cast(@10) */
  w41 = w10;
  /* #283: @39 = project(@25) */
  casadi_sparsify(w25, (&w39), casadi_s4, 0);
  /* #284: @1 = dot(@41, @39) */
  w01 = casadi_dot(1, (&w41), (&w39));
  /* #285: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #286: @1 = (@4*@1) */
  w01  = (w04*w01);
  /* #287: @19 = (@25*@1) */
  for (i=0, rr=w19, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w01);
  /* #288: @34 = @18; (@34[6:9] += @19) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w19; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #289: @19 = (@32*@1) */
  for (i=0, rr=w19, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w01);
  /* #290: @41 = (@0*@41) */
  w41  = (w00*w41);
  /* #291: @23 = dense(@41) */
  casadi_densify((&w41), casadi_s4, w23, 0);
  /* #292: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #293: (@34[9:12] += @19) */
  for (rr=w34+9, cs=w19; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #294: {@41, @1, @39, @3, @14, @13, @40, @42, @52, @9, @15, @35, @17, @8, @16, @38} = vertsplit(@34) */
  w41 = w34[0];
  w01 = w34[1];
  w39 = w34[2];
  w03 = w34[3];
  w14 = w34[4];
  w13 = w34[5];
  w40 = w34[6];
  w42 = w34[7];
  w52 = w34[8];
  w09 = w34[9];
  w15 = w34[10];
  w35 = w34[11];
  w17 = w34[12];
  w08 = w34[13];
  w16 = w34[14];
  w38 = w34[15];
  /* #295: @11 = (@5*@10) */
  w11  = (w05*w10);
  /* #296: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #297: @10 = (-@10) */
  w10 = (- w10 );
  /* #298: @50 = vertcat(@11, @10, @45) */
  rr=w50;
  *rr++ = w11;
  *rr++ = w10;
  /* #299: @51 = (@4*@50) */
  for (i=0, rr=w51, cs=w50; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #300: @50 = @50' */
  /* #301: @50 = (@4*@50) */
  for (i=0, rr=w50, cs=w50; i<2; ++i) (*rr++)  = (w04*(*cs++));
  /* #302: @50 = @50' */
  /* #303: @51 = (@51+@50) */
  for (i=0, rr=w51, cs=w50; i<2; ++i) (*rr++) += (*cs++);
  /* #304: {@11, @10, NULL} = vertsplit(@51) */
  w11 = w51[0];
  w10 = w51[1];
  /* #305: @47 = (@7*@10) */
  w47  = (w07*w10);
  /* #306: @47 = (@47+@40) */
  w47 += w40;
  /* #307: @7 = (@7*@11) */
  w07 *= w11;
  /* #308: @42 = (@42-@7) */
  w42 -= w07;
  /* #309: @5 = (@5*@11) */
  w05 *= w11;
  /* #310: @12 = (@12*@10) */
  w12 *= w10;
  /* #311: @5 = (@5-@12) */
  w05 -= w12;
  /* #312: @5 = (@5+@52) */
  w05 += w52;
  /* #313: @34 = vertcat(@45, @45, @45, @45, @41, @1, @39, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8, @16, @38) */
  rr=w34;
  *rr++ = w41;
  *rr++ = w01;
  *rr++ = w39;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w47;
  *rr++ = w42;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w38;
  /* #314: @54 = @34[6:12] */
  for (rr=w54, cs=w34+6; cs!=w34+12; cs+=1) *rr++ = *cs;
  /* #315: (@43[22:28] = @54) */
  for (rr=w43+22, cs=w54; rr!=w43+28; rr+=1) *rr = *cs++;
  /* #316: (@43[12:48:6] = @54) */
  for (rr=w43+12, cs=w54; rr!=w43+48; rr+=6) *rr = *cs++;
  /* #317: @41 = project(@32) */
  casadi_sparsify(w32, (&w41), casadi_s0, 0);
  /* #318: @1 = ones(20x1,1nz) */
  w01 = 1.;
  /* #319: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @39, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w39 = w01;
  /* #320: @39 = sparsity_cast(@39) */
  /* #321: @1 = dot(@41, @39) */
  w01 = casadi_dot(1, (&w41), (&w39));
  /* #322: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #323: @1 = (@4*@1) */
  w01  = (w04*w01);
  /* #324: @19 = (@25*@1) */
  for (i=0, rr=w19, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w01);
  /* #325: @41 = (@0*@39) */
  w41  = (w00*w39);
  /* #326: @23 = dense(@41) */
  casadi_densify((&w41), casadi_s0, w23, 0);
  /* #327: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #328: @34 = @18; (@34[6:9] += @19) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w19; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #329: @19 = (@32*@1) */
  for (i=0, rr=w19, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w01);
  /* #330: @1 = (-@39) */
  w01 = (- w39 );
  /* #331: @1 = @1' */
  /* #332: @1 = (@4*@1) */
  w01  = (w04*w01);
  /* #333: @1 = @1' */
  /* #334: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #335: @1 = (@1-@39) */
  w01 -= w39;
  /* #336: @1 = (-@1) */
  w01 = (- w01 );
  /* #337: @23 = dense(@1) */
  casadi_densify((&w01), casadi_s0, w23, 0);
  /* #338: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #339: (@34[9:12] += @19) */
  for (rr=w34+9, cs=w19; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #340: {@1, @39, @41, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8, @16, @38} = vertsplit(@34) */
  w01 = w34[0];
  w39 = w34[1];
  w41 = w34[2];
  w03 = w34[3];
  w14 = w34[4];
  w13 = w34[5];
  w47 = w34[6];
  w42 = w34[7];
  w05 = w34[8];
  w09 = w34[9];
  w15 = w34[10];
  w35 = w34[11];
  w17 = w34[12];
  w08 = w34[13];
  w16 = w34[14];
  w38 = w34[15];
  /* #341: @34 = vertcat(@45, @45, @45, @45, @1, @39, @41, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8, @16, @38) */
  rr=w34;
  *rr++ = w01;
  *rr++ = w39;
  *rr++ = w41;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w47;
  *rr++ = w42;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w38;
  /* #342: @54 = @34[6:12] */
  for (rr=w54, cs=w34+6; cs!=w34+12; cs+=1) *rr++ = *cs;
  /* #343: (@43[28:34] = @54) */
  for (rr=w43+28, cs=w54; rr!=w43+34; rr+=1) *rr = *cs++;
  /* #344: (@43[13:49:6] = @54) */
  for (rr=w43+13, cs=w54; rr!=w43+49; rr+=6) *rr = *cs++;
  /* #345: @1 = project(@32) */
  casadi_sparsify(w32, (&w01), casadi_s3, 0);
  /* #346: @39 = ones(20x1,1nz) */
  w39 = 1.;
  /* #347: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL, NULL, NULL} = vertsplit(@39) */
  w41 = w39;
  /* #348: @41 = sparsity_cast(@41) */
  /* #349: @39 = dot(@1, @41) */
  w39 = casadi_dot(1, (&w01), (&w41));
  /* #350: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #351: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #352: @19 = (@25*@39) */
  for (i=0, rr=w19, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #353: @1 = (@0*@41) */
  w01  = (w00*w41);
  /* #354: @23 = dense(@1) */
  casadi_densify((&w01), casadi_s3, w23, 0);
  /* #355: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #356: @34 = @18; (@34[6:9] += @19) */
  casadi_copy(w18, 16, w34);
  for (rr=w34+6, cs=w19; rr!=w34+9; rr+=1) *rr += *cs++;
  /* #357: @19 = (@32*@39) */
  for (i=0, rr=w19, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #358: @39 = (-@41) */
  w39 = (- w41 );
  /* #359: @39 = @39' */
  /* #360: @39 = (@4*@39) */
  w39  = (w04*w39);
  /* #361: @39 = @39' */
  /* #362: @41 = (@4*@41) */
  w41  = (w04*w41);
  /* #363: @39 = (@39-@41) */
  w39 -= w41;
  /* #364: @39 = (-@39) */
  w39 = (- w39 );
  /* #365: @23 = dense(@39) */
  casadi_densify((&w39), casadi_s3, w23, 0);
  /* #366: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #367: (@34[9:12] += @19) */
  for (rr=w34+9, cs=w19; rr!=w34+12; rr+=1) *rr += *cs++;
  /* #368: {@39, @41, @1, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8, @16, @38} = vertsplit(@34) */
  w39 = w34[0];
  w41 = w34[1];
  w01 = w34[2];
  w03 = w34[3];
  w14 = w34[4];
  w13 = w34[5];
  w47 = w34[6];
  w42 = w34[7];
  w05 = w34[8];
  w09 = w34[9];
  w15 = w34[10];
  w35 = w34[11];
  w17 = w34[12];
  w08 = w34[13];
  w16 = w34[14];
  w38 = w34[15];
  /* #369: @34 = vertcat(@45, @45, @45, @45, @39, @41, @1, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8, @16, @38) */
  rr=w34;
  *rr++ = w39;
  *rr++ = w41;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w47;
  *rr++ = w42;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w38;
  /* #370: @54 = @34[6:12] */
  for (rr=w54, cs=w34+6; cs!=w34+12; cs+=1) *rr++ = *cs;
  /* #371: (@43[34:40] = @54) */
  for (rr=w43+34, cs=w54; rr!=w43+40; rr+=1) *rr = *cs++;
  /* #372: (@43[14:50:6] = @54) */
  for (rr=w43+14, cs=w54; rr!=w43+50; rr+=6) *rr = *cs++;
  /* #373: @39 = project(@32) */
  casadi_sparsify(w32, (&w39), casadi_s4, 0);
  /* #374: @41 = ones(20x1,1nz) */
  w41 = 1.;
  /* #375: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL, NULL} = vertsplit(@41) */
  w01 = w41;
  /* #376: @1 = sparsity_cast(@1) */
  /* #377: @41 = dot(@39, @1) */
  w41 = casadi_dot(1, (&w39), (&w01));
  /* #378: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #379: @41 = (@4*@41) */
  w41  = (w04*w41);
  /* #380: @25 = (@25*@41) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w41;
  /* #381: @0 = (@0*@1) */
  w00 *= w01;
  /* #382: @19 = dense(@0) */
  casadi_densify((&w00), casadi_s4, w19, 0);
  /* #383: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #384: (@18[6:9] += @25) */
  for (rr=w18+6, cs=w25; rr!=w18+9; rr+=1) *rr += *cs++;
  /* #385: @32 = (@32*@41) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) *= w41;
  /* #386: @41 = (-@1) */
  w41 = (- w01 );
  /* #387: @41 = @41' */
  /* #388: @41 = (@4*@41) */
  w41  = (w04*w41);
  /* #389: @41 = @41' */
  /* #390: @4 = (@4*@1) */
  w04 *= w01;
  /* #391: @41 = (@41-@4) */
  w41 -= w04;
  /* #392: @41 = (-@41) */
  w41 = (- w41 );
  /* #393: @25 = dense(@41) */
  casadi_densify((&w41), casadi_s4, w25, 0);
  /* #394: @32 = (@32+@25) */
  for (i=0, rr=w32, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #395: (@18[9:12] += @32) */
  for (rr=w18+9, cs=w32; rr!=w18+12; rr+=1) *rr += *cs++;
  /* #396: {@41, @4, @1, @0, @39, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8} = vertsplit(@18) */
  w41 = w18[0];
  w04 = w18[1];
  w01 = w18[2];
  w00 = w18[3];
  w39 = w18[4];
  w03 = w18[5];
  w14 = w18[6];
  w13 = w18[7];
  w47 = w18[8];
  w42 = w18[9];
  w05 = w18[10];
  w09 = w18[11];
  w15 = w18[12];
  w35 = w18[13];
  w17 = w18[14];
  w08 = w18[15];
  /* #397: @18 = vertcat(@45, @45, @45, @45, @41, @4, @1, @0, @39, @3, @14, @13, @47, @42, @5, @9, @15, @35, @17, @8) */
  rr=w18;
  *rr++ = w41;
  *rr++ = w04;
  *rr++ = w01;
  *rr++ = w00;
  *rr++ = w39;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w47;
  *rr++ = w42;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w35;
  *rr++ = w17;
  *rr++ = w08;
  /* #398: @54 = @18[6:12] */
  for (rr=w54, cs=w18+6; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #399: (@43[40:46] = @54) */
  for (rr=w43+40, cs=w54; rr!=w43+46; rr+=1) *rr = *cs++;
  /* #400: (@43[15:51:6] = @54) */
  for (rr=w43+15, cs=w54; rr!=w43+51; rr+=6) *rr = *cs++;
  /* #401: @55 = @43' */
  casadi_trans(w43,casadi_s5, w55, casadi_s5, iw);
  /* #402: output[2][0] = @55 */
  casadi_copy(w55, 50, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s5;
    case 3: return casadi_s12;
    case 4: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 25;
  if (sz_iw) *sz_iw = 21;
  if (sz_w) *sz_w = 264;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 25*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 21*sizeof(casadi_int);
  if (sz_w) *sz_w = 264*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
