/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[10] = 
  {0, 1, 2, 3, 12, 21, 34, 38,
  46, 50};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s3[7] = {4, 13, 22, 30, 39, 42, 51};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s5[7] = {5, 14, 23, 31, 35, 43, 47};
static const casadi_int casadi_s6[5] = {6, 15, 24, 36, 40};
static const casadi_int casadi_s7[5] = {7, 16, 25, 32, 41};
static const casadi_int casadi_s8[5] = {8, 17, 26, 33, 37};
static const casadi_int casadi_s9[5] = {9, 18, 27, 48, 52};
static const casadi_int casadi_s10[5] = {10, 19, 28, 44, 53};
static const casadi_int casadi_s11[5] = {11, 20, 29, 45, 49};
static const casadi_int casadi_s12[72] = 
  {15, 15, 0, 0, 0, 0, 1, 2,
  3, 10, 17, 24, 29, 34, 39, 44,
  49, 54, 0, 1, 2, 3, 4, 5,
  7, 8, 10, 11, 3, 4, 5, 6,
  8, 9, 11, 3, 4, 5, 6, 7,
  9, 10, 3, 4, 5, 7, 8, 3,
  4, 5, 6, 8, 3, 4, 5, 6,
  7, 3, 4, 5, 10, 11, 3, 4,
  5, 9, 11, 3, 4, 5, 9, 10};
static const casadi_int casadi_s13[72] = 
  {15, 15, 0, 1, 2, 3, 12, 21,
  30, 34, 38, 42, 46, 50, 54, 54,
  54, 54, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  7, 8, 10, 11, 6, 8, 9, 11,
  6, 7, 9, 10, 7, 8, 13, 14,
  6, 8, 12, 14, 6, 7, 12, 13};
static const casadi_int casadi_s14[33] = 
  {15, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14};
static const casadi_int casadi_s15[9] = 
  {15, 3, 0, 1, 2, 3, 12, 13,
  14};
static const casadi_int casadi_s16[21] = 
  {3, 15, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 1,
  2, 3, 0, 1, 2};
static const casadi_int casadi_s17[3] = {15, 1, 1};
static const casadi_int casadi_s18[3] = {3, 1, 1};
static const casadi_int casadi_s19[3] = {0, 1, 1};
static const casadi_int casadi_s20[3] = {0, 0, 1};
static const casadi_int casadi_s21[3] = {51, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[3] = {0., 0., 9.8100000000000005e+00};

static const casadi_real casadi_zeros[15] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* planner_payload_jerk_impl_dae_fun_jac_x_xdot_u:(i0[15],i1[15],i2[3],i3[0],i4[],i5[51])->(o0[15],o1[15x15,54nz],o2[15x15,15nz],o3[15x3,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, *w04=w+18, w05, w06, w07, *w08=w+24, *w09=w+27, w10;
  casadi_real w11, w12, *w13=w+33, w14, w15, w16, *w17=w+39, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, *w29=w+53, *w30=w+68, *w31=w+122, *w33=w+129, *w34=w+131, *w35=w+141;
  casadi_real *w36=w+151, *w38=w+158, *w39=w+163, *w40=w+168;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *wr00;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][4] */
  w02 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[0][5] */
  w03 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = [-0, -0, -9.81] */
  casadi_copy(casadi_c0, 3, w04);
  /* #5: @5 = input[0][6] */
  w05 = arg[0] ? arg[0][6] : 0;
  /* #6: @6 = input[0][7] */
  w06 = arg[0] ? arg[0][7] : 0;
  /* #7: @7 = input[0][8] */
  w07 = arg[0] ? arg[0][8] : 0;
  /* #8: @8 = vertcat(@5, @6, @7) */
  rr=w08;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #9: @9 = [0, 0, 9.81] */
  casadi_copy(casadi_c1, 3, w09);
  /* #10: @10 = input[0][12] */
  w10 = arg[0] ? arg[0][12] : 0;
  /* #11: @11 = input[0][13] */
  w11 = arg[0] ? arg[0][13] : 0;
  /* #12: @12 = input[0][14] */
  w12 = arg[0] ? arg[0][14] : 0;
  /* #13: @13 = vertcat(@10, @11, @12) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @9 = (@9+@13) */
  for (i=0, rr=w09, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #15: @10 = dot(@8, @9) */
  w10 = casadi_dot(3, w08, w09);
  /* #16: @13 = (@8*@10) */
  for (i=0, rr=w13, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #17: @4 = (@4+@13) */
  for (i=0, rr=w04, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #18: @11 = 0.76 */
  w11 = 7.6000000000000001e-01;
  /* #19: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #20: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #21: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #22: @13 = vertcat(@12, @14, @15) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  /* #23: @16 = dot(@13, @13) */
  w16 = casadi_dot(3, w13, w13);
  /* #24: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #25: @17 = (@16*@8) */
  for (i=0, rr=w17, cs=w08; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #26: @4 = (@4-@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #27: @18 = (@14*@7) */
  w18  = (w14*w07);
  /* #28: @19 = (@15*@6) */
  w19  = (w15*w06);
  /* #29: @18 = (@18-@19) */
  w18 -= w19;
  /* #30: @19 = (@15*@5) */
  w19  = (w15*w05);
  /* #31: @20 = (@12*@7) */
  w20  = (w12*w07);
  /* #32: @19 = (@19-@20) */
  w19 -= w20;
  /* #33: @20 = (@12*@6) */
  w20  = (w12*w06);
  /* #34: @21 = (@14*@5) */
  w21  = (w14*w05);
  /* #35: @20 = (@20-@21) */
  w20 -= w21;
  /* #36: @21 = -1.31579 */
  w21 = -1.3157894736842106e+00;
  /* #37: @22 = @9[2] */
  for (rr=(&w22), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #38: @23 = (@6*@22) */
  w23  = (w06*w22);
  /* #39: @24 = @9[1] */
  for (rr=(&w24), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #40: @25 = (@7*@24) */
  w25  = (w07*w24);
  /* #41: @23 = (@23-@25) */
  w23 -= w25;
  /* #42: @25 = @9[0] */
  for (rr=(&w25), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #43: @26 = (@7*@25) */
  w26  = (w07*w25);
  /* #44: @27 = (@5*@22) */
  w27  = (w05*w22);
  /* #45: @26 = (@26-@27) */
  w26 -= w27;
  /* #46: @27 = (@5*@24) */
  w27  = (w05*w24);
  /* #47: @28 = (@6*@25) */
  w28  = (w06*w25);
  /* #48: @27 = (@27-@28) */
  w27 -= w28;
  /* #49: @17 = vertcat(@23, @26, @27) */
  rr=w17;
  *rr++ = w23;
  *rr++ = w26;
  *rr++ = w27;
  /* #50: @17 = (@21*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #51: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #52: @26 = input[2][1] */
  w26 = arg[2] ? arg[2][1] : 0;
  /* #53: @27 = input[2][2] */
  w27 = arg[2] ? arg[2][2] : 0;
  /* #54: @29 = vertcat(@1, @2, @3, @4, @18, @19, @20, @17, @23, @26, @27) */
  rr=w29;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  *rr++ = w23;
  *rr++ = w26;
  *rr++ = w27;
  /* #55: @0 = (@0-@29) */
  for (i=0, rr=w00, cr=wr00, cs=w29; i<15; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #56: output[0][0] = @0 */
  casadi_copy(w00, 15, res[0]);
  /* #57: @30 = zeros(15x15,54nz) */
  casadi_clear(w30, 54);
  /* #58: @31 = ones(15x1,7nz) */
  casadi_fill(w31, 7, 1.);
  /* #59: {NULL, NULL, NULL, @1, @2, @3, @18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w01 = w31[3];
  w02 = w31[4];
  w03 = w31[5];
  w18 = w31[6];
  /* #60: @32 = 00 */
  /* #61: @19 = vertcat(@18, @32, @32) */
  rr=(&w19);
  *rr++ = w18;
  /* #62: @20 = (@10*@19) */
  w20  = (w10*w19);
  /* #63: @4 = dense(@20) */
  casadi_densify((&w20), casadi_s0, w04, 0);
  /* #64: @20 = project(@9) */
  casadi_sparsify(w09, (&w20), casadi_s0, 0);
  /* #65: @23 = dot(@19, @20) */
  w23 = casadi_dot(1, (&w19), (&w20));
  /* #66: @17 = (@8*@23) */
  for (i=0, rr=w17, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #67: @4 = (@4+@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #68: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #69: @19 = (-@19) */
  w19 = (- w19 );
  /* #70: @17 = dense(@19) */
  casadi_densify((&w19), casadi_s0, w17, 0);
  /* #71: @4 = (@4+@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #72: @19 = (@15*@18) */
  w19  = (w15*w18);
  /* #73: @23 = (@14*@18) */
  w23  = (w14*w18);
  /* #74: @23 = (-@23) */
  w23 = (- w23 );
  /* #75: @20 = (@22*@18) */
  w20  = (w22*w18);
  /* #76: @20 = (-@20) */
  w20 = (- w20 );
  /* #77: @18 = (@24*@18) */
  w18  = (w24*w18);
  /* #78: @33 = vertcat(@32, @20, @18) */
  rr=w33;
  *rr++ = w20;
  *rr++ = w18;
  /* #79: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #80: @34 = vertcat(@1, @2, @3, @4, @32, @19, @23, @33, @32, @32, @32) */
  rr=w34;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w19;
  *rr++ = w23;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #81: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<10; ++i) *rr++ = (- *cs++ );
  /* #82: @35 = @34[:10] */
  for (rr=w35, cs=w34+0; cs!=w34+10; cs+=1) *rr++ = *cs;
  /* #83: (@30[0, 1, 2, 3, 12, 21, 34, 38, 46, 50] = @35) */
  for (cii=casadi_s1, rr=w30, cs=w35; cii!=casadi_s1+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #84: @1 = ones(15x1,1nz) */
  w01 = 1.;
  /* #85: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w02 = w01;
  /* #86: @1 = vertcat(@32, @2, @32) */
  rr=(&w01);
  *rr++ = w02;
  /* #87: @3 = (@10*@1) */
  w03  = (w10*w01);
  /* #88: @4 = dense(@3) */
  casadi_densify((&w03), casadi_s2, w04, 0);
  /* #89: @3 = project(@9) */
  casadi_sparsify(w09, (&w03), casadi_s2, 0);
  /* #90: @19 = dot(@1, @3) */
  w19 = casadi_dot(1, (&w01), (&w03));
  /* #91: @17 = (@8*@19) */
  for (i=0, rr=w17, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w19);
  /* #92: @4 = (@4+@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #93: @1 = (@16*@1) */
  w01  = (w16*w01);
  /* #94: @1 = (-@1) */
  w01 = (- w01 );
  /* #95: @17 = dense(@1) */
  casadi_densify((&w01), casadi_s2, w17, 0);
  /* #96: @4 = (@4+@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #97: @15 = (@15*@2) */
  w15 *= w02;
  /* #98: @15 = (-@15) */
  w15 = (- w15 );
  /* #99: @1 = (@12*@2) */
  w01  = (w12*w02);
  /* #100: @22 = (@22*@2) */
  w22 *= w02;
  /* #101: @2 = (@25*@2) */
  w02  = (w25*w02);
  /* #102: @2 = (-@2) */
  w02 = (- w02 );
  /* #103: @33 = vertcat(@22, @32, @2) */
  rr=w33;
  *rr++ = w22;
  *rr++ = w02;
  /* #104: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #105: @31 = vertcat(@32, @32, @32, @4, @15, @32, @1, @33, @32, @32, @32) */
  rr=w31;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w15;
  *rr++ = w01;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #106: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<7; ++i) *rr++ = (- *cs++ );
  /* #107: @36 = @31[:7] */
  for (rr=w36, cs=w31+0; cs!=w31+7; cs+=1) *rr++ = *cs;
  /* #108: (@30[4, 13, 22, 30, 39, 42, 51] = @36) */
  for (cii=casadi_s3, rr=w30, cs=w36; cii!=casadi_s3+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #109: @15 = ones(15x1,1nz) */
  w15 = 1.;
  /* #110: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w01 = w15;
  /* #111: @15 = vertcat(@32, @32, @1) */
  rr=(&w15);
  *rr++ = w01;
  /* #112: @10 = (@10*@15) */
  w10 *= w15;
  /* #113: @4 = dense(@10) */
  casadi_densify((&w10), casadi_s4, w04, 0);
  /* #114: @10 = project(@9) */
  casadi_sparsify(w09, (&w10), casadi_s4, 0);
  /* #115: @22 = dot(@15, @10) */
  w22 = casadi_dot(1, (&w15), (&w10));
  /* #116: @9 = (@8*@22) */
  for (i=0, rr=w09, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w22);
  /* #117: @4 = (@4+@9) */
  for (i=0, rr=w04, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #118: @16 = (@16*@15) */
  w16 *= w15;
  /* #119: @16 = (-@16) */
  w16 = (- w16 );
  /* #120: @9 = dense(@16) */
  casadi_densify((&w16), casadi_s4, w09, 0);
  /* #121: @4 = (@4+@9) */
  for (i=0, rr=w04, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @14 = (@14*@1) */
  w14 *= w01;
  /* #123: @12 = (@12*@1) */
  w12 *= w01;
  /* #124: @12 = (-@12) */
  w12 = (- w12 );
  /* #125: @24 = (@24*@1) */
  w24 *= w01;
  /* #126: @24 = (-@24) */
  w24 = (- w24 );
  /* #127: @25 = (@25*@1) */
  w25 *= w01;
  /* #128: @33 = vertcat(@24, @25, @32) */
  rr=w33;
  *rr++ = w24;
  *rr++ = w25;
  /* #129: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #130: @36 = vertcat(@32, @32, @32, @4, @14, @12, @32, @33, @32, @32, @32) */
  rr=w36;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w14;
  *rr++ = w12;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #131: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<7; ++i) *rr++ = (- *cs++ );
  /* #132: @31 = @36[:7] */
  for (rr=w31, cs=w36+0; cs!=w36+7; cs+=1) *rr++ = *cs;
  /* #133: (@30[5, 14, 23, 31, 35, 43, 47] = @31) */
  for (cii=casadi_s5, rr=w30, cs=w31; cii!=casadi_s5+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #134: @14 = project(@13) */
  casadi_sparsify(w13, (&w14), casadi_s0, 0);
  /* #135: @12 = ones(15x1,1nz) */
  w12 = 1.;
  /* #136: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @24, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w24 = w12;
  /* #137: @12 = vertcat(@24, @32, @32) */
  rr=(&w12);
  *rr++ = w24;
  /* #138: @25 = dot(@14, @12) */
  w25 = casadi_dot(1, (&w14), (&w12));
  /* #139: @1 = dot(@12, @14) */
  w01 = casadi_dot(1, (&w12), (&w14));
  /* #140: @25 = (@25+@1) */
  w25 += w01;
  /* #141: @25 = (@11*@25) */
  w25  = (w11*w25);
  /* #142: @4 = (@8*@25) */
  for (i=0, rr=w04, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #143: @4 = (-@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #144: @25 = (@7*@24) */
  w25  = (w07*w24);
  /* #145: @25 = (-@25) */
  w25 = (- w25 );
  /* #146: @24 = (@6*@24) */
  w24  = (w06*w24);
  /* #147: @37 = zeros(3x1,0nz) */
  /* #148: @38 = vertcat(@32, @32, @32, @4, @32, @25, @24, @37, @32, @32, @32) */
  rr=w38;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w25;
  *rr++ = w24;
  /* #149: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) *rr++ = (- *cs++ );
  /* #150: @39 = @38[:5] */
  for (rr=w39, cs=w38+0; cs!=w38+5; cs+=1) *rr++ = *cs;
  /* #151: (@30[6, 15, 24, 36, 40] = @39) */
  for (cii=casadi_s6, rr=w30, cs=w39; cii!=casadi_s6+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #152: @25 = project(@13) */
  casadi_sparsify(w13, (&w25), casadi_s2, 0);
  /* #153: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #154: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL, NULL} = vertsplit(@24) */
  w01 = w24;
  /* #155: @24 = vertcat(@32, @1, @32) */
  rr=(&w24);
  *rr++ = w01;
  /* #156: @12 = dot(@25, @24) */
  w12 = casadi_dot(1, (&w25), (&w24));
  /* #157: @14 = dot(@24, @25) */
  w14 = casadi_dot(1, (&w24), (&w25));
  /* #158: @12 = (@12+@14) */
  w12 += w14;
  /* #159: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #160: @4 = (@8*@12) */
  for (i=0, rr=w04, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #161: @4 = (-@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #162: @12 = (@7*@1) */
  w12  = (w07*w01);
  /* #163: @1 = (@5*@1) */
  w01  = (w05*w01);
  /* #164: @1 = (-@1) */
  w01 = (- w01 );
  /* #165: @39 = vertcat(@32, @32, @32, @4, @12, @32, @1, @37, @32, @32, @32) */
  rr=w39;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w12;
  *rr++ = w01;
  /* #166: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<5; ++i) *rr++ = (- *cs++ );
  /* #167: @38 = @39[:5] */
  for (rr=w38, cs=w39+0; cs!=w39+5; cs+=1) *rr++ = *cs;
  /* #168: (@30[7, 16, 25, 32, 41] = @38) */
  for (cii=casadi_s7, rr=w30, cs=w38; cii!=casadi_s7+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #169: @12 = project(@13) */
  casadi_sparsify(w13, (&w12), casadi_s4, 0);
  /* #170: @1 = ones(15x1,1nz) */
  w01 = 1.;
  /* #171: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL} = vertsplit(@1) */
  w14 = w01;
  /* #172: @1 = vertcat(@32, @32, @14) */
  rr=(&w01);
  *rr++ = w14;
  /* #173: @24 = dot(@12, @1) */
  w24 = casadi_dot(1, (&w12), (&w01));
  /* #174: @25 = dot(@1, @12) */
  w25 = casadi_dot(1, (&w01), (&w12));
  /* #175: @24 = (@24+@25) */
  w24 += w25;
  /* #176: @11 = (@11*@24) */
  w11 *= w24;
  /* #177: @13 = (@8*@11) */
  for (i=0, rr=w13, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #178: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #179: @11 = (@6*@14) */
  w11  = (w06*w14);
  /* #180: @11 = (-@11) */
  w11 = (- w11 );
  /* #181: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #182: @38 = vertcat(@32, @32, @32, @13, @11, @14, @32, @37, @32, @32, @32) */
  rr=w38;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  *rr++ = w11;
  *rr++ = w14;
  /* #183: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) *rr++ = (- *cs++ );
  /* #184: @39 = @38[:5] */
  for (rr=w39, cs=w38+0; cs!=w38+5; cs+=1) *rr++ = *cs;
  /* #185: (@30[8, 17, 26, 33, 37] = @39) */
  for (cii=casadi_s8, rr=w30, cs=w39; cii!=casadi_s8+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #186: @11 = project(@8) */
  casadi_sparsify(w08, (&w11), casadi_s0, 0);
  /* #187: @14 = ones(15x1,1nz) */
  w14 = 1.;
  /* #188: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @24, NULL, NULL} = vertsplit(@14) */
  w24 = w14;
  /* #189: @14 = vertcat(@24, @32, @32) */
  rr=(&w14);
  *rr++ = w24;
  /* #190: @25 = dot(@11, @14) */
  w25 = casadi_dot(1, (&w11), (&w14));
  /* #191: @13 = (@8*@25) */
  for (i=0, rr=w13, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #192: @25 = (@7*@24) */
  w25  = (w07*w24);
  /* #193: @24 = (@6*@24) */
  w24  = (w06*w24);
  /* #194: @24 = (-@24) */
  w24 = (- w24 );
  /* #195: @33 = vertcat(@32, @25, @24) */
  rr=w33;
  *rr++ = w25;
  *rr++ = w24;
  /* #196: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #197: @39 = vertcat(@32, @32, @32, @13, @32, @32, @32, @33, @32, @32, @32) */
  rr=w39;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #198: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<5; ++i) *rr++ = (- *cs++ );
  /* #199: @38 = @39[:5] */
  for (rr=w38, cs=w39+0; cs!=w39+5; cs+=1) *rr++ = *cs;
  /* #200: (@30[9, 18, 27, 48, 52] = @38) */
  for (cii=casadi_s9, rr=w30, cs=w38; cii!=casadi_s9+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #201: @25 = project(@8) */
  casadi_sparsify(w08, (&w25), casadi_s2, 0);
  /* #202: @24 = ones(15x1,1nz) */
  w24 = 1.;
  /* #203: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @11, NULL} = vertsplit(@24) */
  w11 = w24;
  /* #204: @24 = vertcat(@32, @11, @32) */
  rr=(&w24);
  *rr++ = w11;
  /* #205: @14 = dot(@25, @24) */
  w14 = casadi_dot(1, (&w25), (&w24));
  /* #206: @13 = (@8*@14) */
  for (i=0, rr=w13, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w14);
  /* #207: @7 = (@7*@11) */
  w07 *= w11;
  /* #208: @7 = (-@7) */
  w07 = (- w07 );
  /* #209: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #210: @33 = vertcat(@7, @32, @11) */
  rr=w33;
  *rr++ = w07;
  *rr++ = w11;
  /* #211: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #212: @38 = vertcat(@32, @32, @32, @13, @32, @32, @32, @33, @32, @32, @32) */
  rr=w38;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #213: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<5; ++i) *rr++ = (- *cs++ );
  /* #214: @39 = @38[:5] */
  for (rr=w39, cs=w38+0; cs!=w38+5; cs+=1) *rr++ = *cs;
  /* #215: (@30[10, 19, 28, 44, 53] = @39) */
  for (cii=casadi_s10, rr=w30, cs=w39; cii!=casadi_s10+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #216: @7 = project(@8) */
  casadi_sparsify(w08, (&w07), casadi_s4, 0);
  /* #217: @11 = ones(15x1,1nz) */
  w11 = 1.;
  /* #218: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14} = vertsplit(@11) */
  w14 = w11;
  /* #219: @11 = vertcat(@32, @32, @14) */
  rr=(&w11);
  *rr++ = w14;
  /* #220: @25 = dot(@7, @11) */
  w25 = casadi_dot(1, (&w07), (&w11));
  /* #221: @8 = (@8*@25) */
  for (i=0, rr=w08; i<3; ++i) (*rr++) *= w25;
  /* #222: @6 = (@6*@14) */
  w06 *= w14;
  /* #223: @5 = (@5*@14) */
  w05 *= w14;
  /* #224: @5 = (-@5) */
  w05 = (- w05 );
  /* #225: @33 = vertcat(@6, @5, @32) */
  rr=w33;
  *rr++ = w06;
  *rr++ = w05;
  /* #226: @33 = (@21*@33) */
  for (i=0, rr=w33, cs=w33; i<2; ++i) (*rr++)  = (w21*(*cs++));
  /* #227: @39 = vertcat(@32, @32, @32, @8, @32, @32, @32, @33, @32, @32, @32) */
  rr=w39;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<2; ++i) *rr++ = *cs++;
  /* #228: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<5; ++i) *rr++ = (- *cs++ );
  /* #229: @38 = @39[:5] */
  for (rr=w38, cs=w39+0; cs!=w39+5; cs+=1) *rr++ = *cs;
  /* #230: (@30[11, 20, 29, 45, 49] = @38) */
  for (cii=casadi_s11, rr=w30, cs=w38; cii!=casadi_s11+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #231: @40 = @30' */
  casadi_trans(w30,casadi_s13, w40, casadi_s12, iw);
  /* #232: output[1][0] = @40 */
  casadi_copy(w40, 54, res[1]);
  /* #233: @0 = zeros(15x15,15nz) */
  casadi_clear(w00, 15);
  /* #234: @29 = ones(15x1) */
  casadi_fill(w29, 15, 1.);
  /* #235: (@0[:15] = @29) */
  for (rr=w00+0, cs=w29; rr!=w00+15; rr+=1) *rr = *cs++;
  /* #236: @29 = @0' */
  casadi_trans(w00,casadi_s14, w29, casadi_s14, iw);
  /* #237: output[2][0] = @29 */
  casadi_copy(w29, 15, res[2]);
  /* #238: @8 = zeros(3x15,3nz) */
  casadi_clear(w08, 3);
  /* #239: @13 = ones(3x1) */
  casadi_fill(w13, 3, 1.);
  /* #240: {@21, @6, @5} = vertsplit(@13) */
  w21 = w13[0];
  w06 = w13[1];
  w05 = w13[2];
  /* #241: @13 = vertcat(@32, @32, @32, @37, @32, @32, @32, @37, @21, @6, @5) */
  rr=w13;
  *rr++ = w21;
  *rr++ = w06;
  *rr++ = w05;
  /* #242: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) *rr++ = (- *cs++ );
  /* #243: @4 = @13[:3] */
  for (rr=w04, cs=w13+0; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #244: (@8[:3] = @4) */
  for (rr=w08+0, cs=w04; rr!=w08+3; rr+=1) *rr = *cs++;
  /* #245: @4 = @8' */
  casadi_trans(w08,casadi_s16, w04, casadi_s15, iw);
  /* #246: output[3][0] = @4 */
  casadi_copy(w04, 3, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s17;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    case 4: return casadi_s20;
    case 5: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s12;
    case 2: return casadi_s14;
    case 3: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 19;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 222;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_jerk_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 19*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 222*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
