/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[6] = {0, 1, 2, 3, 10, 14};
static const casadi_int casadi_s1[3] = {4, 6, 15};
static const casadi_int casadi_s2[3] = {5, 7, 11};
static const casadi_int casadi_s3[33] = 
  {12, 12, 0, 0, 0, 0, 1, 2,
  3, 6, 9, 12, 14, 16, 18, 0,
  1, 2, 3, 7, 8, 4, 6, 8,
  5, 6, 7, 7, 8, 6, 8, 6,
  7};
static const casadi_int casadi_s4[33] = 
  {12, 12, 0, 1, 2, 3, 4, 5,
  6, 10, 14, 18, 18, 18, 18, 3,
  4, 5, 6, 7, 8, 7, 8, 10,
  11, 6, 8, 9, 11, 6, 7, 9,
  10};
static const casadi_int casadi_s5[27] = 
  {12, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s6[13] = 
  {12, 4, 0, 3, 4, 5, 6, 3,
  4, 5, 9, 10, 11};
static const casadi_int casadi_s7[21] = 
  {4, 12, 0, 0, 0, 0, 1, 2,
  3, 3, 3, 3, 4, 5, 6, 0,
  0, 0, 1, 2, 3};
static const casadi_int casadi_s8[3] = {12, 1, 1};
static const casadi_int casadi_s9[3] = {4, 1, 1};
static const casadi_int casadi_s10[3] = {0, 1, 1};
static const casadi_int casadi_s11[3] = {0, 0, 1};
static const casadi_int casadi_s12[3] = {44, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 9.8100000000000005e+00};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* planner_payload_impl_dae_fun_jac_x_xdot_u:(i0[12],i1[12],i2[4],i3[0],i4[],i5[44])->(o0[12],o1[12x12,18nz],o2[12x12,12nz],o3[12x4,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+20, *w10=w+23;
  casadi_real *w11=w+26, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+38, *w22=w+50;
  casadi_real *w23=w+68, *w25=w+75, *w26=w+81, *w28=w+87, *w29=w+89, *w30=w+91, *w31=w+109, *w32=w+113;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *wr00;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][4] */
  w02 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[0][5] */
  w03 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = -8.86525 */
  w04 = -8.8652482269503547e+00;
  /* #5: @5 = input[2][0] */
  w05 = arg[2] ? arg[2][0] : 0;
  /* #6: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #7: @6 = input[0][6] */
  w06 = arg[0] ? arg[0][6] : 0;
  /* #8: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][7] : 0;
  /* #9: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][8] : 0;
  /* #10: @9 = vertcat(@6, @7, @8) */
  rr=w09;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #11: @10 = (@5*@9) */
  for (i=0, rr=w10, cs=w09; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #12: @11 = [0, 0, 9.81] */
  casadi_copy(casadi_c0, 3, w11);
  /* #13: @10 = (@10-@11) */
  for (i=0, rr=w10, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #15: @13 = (@12*@8) */
  w13  = (w12*w08);
  /* #16: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #17: @15 = (@14*@7) */
  w15  = (w14*w07);
  /* #18: @13 = (@13-@15) */
  w13 -= w15;
  /* #19: @15 = (@14*@6) */
  w15  = (w14*w06);
  /* #20: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #21: @17 = (@16*@8) */
  w17  = (w16*w08);
  /* #22: @15 = (@15-@17) */
  w15 -= w17;
  /* #23: @17 = (@16*@7) */
  w17  = (w16*w07);
  /* #24: @18 = (@12*@6) */
  w18  = (w12*w06);
  /* #25: @17 = (@17-@18) */
  w17 -= w18;
  /* #26: @18 = input[2][1] */
  w18 = arg[2] ? arg[2][1] : 0;
  /* #27: @19 = input[2][2] */
  w19 = arg[2] ? arg[2][2] : 0;
  /* #28: @20 = input[2][3] */
  w20 = arg[2] ? arg[2][3] : 0;
  /* #29: @21 = vertcat(@1, @2, @3, @10, @13, @15, @17, @18, @19, @20) */
  rr=w21;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #30: @0 = (@0-@21) */
  for (i=0, rr=w00, cr=wr00, cs=w21; i<12; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #31: output[0][0] = @0 */
  casadi_copy(w00, 12, res[0]);
  /* #32: @22 = zeros(12x12,18nz) */
  casadi_clear(w22, 18);
  /* #33: @23 = ones(12x1,7nz) */
  casadi_fill(w23, 7, 1.);
  /* #34: {NULL, NULL, NULL, @1, @2, @3, @13, NULL, NULL, NULL, NULL, NULL} = vertsplit(@23) */
  w01 = w23[3];
  w02 = w23[4];
  w03 = w23[5];
  w13 = w23[6];
  /* #35: @24 = 00 */
  /* #36: @15 = vertcat(@13, @24, @24) */
  rr=(&w15);
  *rr++ = w13;
  /* #37: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #38: @17 = (@14*@13) */
  w17  = (w14*w13);
  /* #39: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #40: @13 = (-@13) */
  w13 = (- w13 );
  /* #41: @25 = vertcat(@1, @2, @3, @15, @24, @17, @13, @24, @24, @24) */
  rr=w25;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w13;
  /* #42: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<6; ++i) *rr++ = (- *cs++ );
  /* #43: @26 = @25[:6] */
  for (rr=w26, cs=w25+0; cs!=w25+6; cs+=1) *rr++ = *cs;
  /* #44: (@22[0, 1, 2, 3, 10, 14] = @26) */
  for (cii=casadi_s0, rr=w22, cs=w26; cii!=casadi_s0+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #45: @1 = ones(12x1,1nz) */
  w01 = 1.;
  /* #46: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w02 = w01;
  /* #47: @1 = vertcat(@24, @2, @24) */
  rr=(&w01);
  *rr++ = w02;
  /* #48: @1 = (@5*@1) */
  w01  = (w05*w01);
  /* #49: @14 = (@14*@2) */
  w14 *= w02;
  /* #50: @14 = (-@14) */
  w14 = (- w14 );
  /* #51: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #52: @10 = vertcat(@24, @24, @24, @1, @14, @24, @2, @24, @24, @24) */
  rr=w10;
  *rr++ = w01;
  *rr++ = w14;
  *rr++ = w02;
  /* #53: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (- *cs++ );
  /* #54: @11 = @10[:3] */
  for (rr=w11, cs=w10+0; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #55: (@22[4, 6, 15] = @11) */
  for (cii=casadi_s1, rr=w22, cs=w11; cii!=casadi_s1+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #56: @1 = ones(12x1,1nz) */
  w01 = 1.;
  /* #57: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL} = vertsplit(@1) */
  w14 = w01;
  /* #58: @1 = vertcat(@24, @24, @14) */
  rr=(&w01);
  *rr++ = w14;
  /* #59: @5 = (@5*@1) */
  w05 *= w01;
  /* #60: @12 = (@12*@14) */
  w12 *= w14;
  /* #61: @16 = (@16*@14) */
  w16 *= w14;
  /* #62: @16 = (-@16) */
  w16 = (- w16 );
  /* #63: @11 = vertcat(@24, @24, @24, @5, @12, @16, @24, @24, @24, @24) */
  rr=w11;
  *rr++ = w05;
  *rr++ = w12;
  *rr++ = w16;
  /* #64: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #65: @10 = @11[:3] */
  for (rr=w10, cs=w11+0; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #66: (@22[5, 7, 11] = @10) */
  for (cii=casadi_s2, rr=w22, cs=w10; cii!=casadi_s2+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #67: @27 = zeros(3x1,0nz) */
  /* #68: @5 = ones(12x1,1nz) */
  w05 = 1.;
  /* #69: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @12, NULL, NULL} = vertsplit(@5) */
  w12 = w05;
  /* #70: @5 = (@8*@12) */
  w05  = (w08*w12);
  /* #71: @5 = (-@5) */
  w05 = (- w05 );
  /* #72: @12 = (@7*@12) */
  w12  = (w07*w12);
  /* #73: @28 = vertcat(@24, @24, @24, @27, @24, @5, @12, @24, @24, @24) */
  rr=w28;
  *rr++ = w05;
  *rr++ = w12;
  /* #74: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<2; ++i) *rr++ = (- *cs++ );
  /* #75: @29 = @28[:2] */
  for (rr=w29, cs=w28+0; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #76: (@22[12:20:4] = @29) */
  for (rr=w22+12, cs=w29; rr!=w22+20; rr+=4) *rr = *cs++;
  /* #77: @5 = ones(12x1,1nz) */
  w05 = 1.;
  /* #78: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @12, NULL} = vertsplit(@5) */
  w12 = w05;
  /* #79: @8 = (@8*@12) */
  w08 *= w12;
  /* #80: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #81: @12 = (-@12) */
  w12 = (- w12 );
  /* #82: @29 = vertcat(@24, @24, @24, @27, @8, @24, @12, @24, @24, @24) */
  rr=w29;
  *rr++ = w08;
  *rr++ = w12;
  /* #83: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<2; ++i) *rr++ = (- *cs++ );
  /* #84: @28 = @29[:2] */
  for (rr=w28, cs=w29+0; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #85: (@22[8:26:9] = @28) */
  for (rr=w22+8, cs=w28; rr!=w22+26; rr+=9) *rr = *cs++;
  /* #86: @8 = ones(12x1,1nz) */
  w08 = 1.;
  /* #87: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @12} = vertsplit(@8) */
  w12 = w08;
  /* #88: @7 = (@7*@12) */
  w07 *= w12;
  /* #89: @7 = (-@7) */
  w07 = (- w07 );
  /* #90: @6 = (@6*@12) */
  w06 *= w12;
  /* #91: @28 = vertcat(@24, @24, @24, @27, @7, @6, @24, @24, @24, @24) */
  rr=w28;
  *rr++ = w07;
  *rr++ = w06;
  /* #92: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<2; ++i) *rr++ = (- *cs++ );
  /* #93: @29 = @28[:2] */
  for (rr=w29, cs=w28+0; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #94: (@22[9:17:4] = @29) */
  for (rr=w22+9, cs=w29; rr!=w22+17; rr+=4) *rr = *cs++;
  /* #95: @30 = @22' */
  casadi_trans(w22,casadi_s4, w30, casadi_s3, iw);
  /* #96: output[1][0] = @30 */
  casadi_copy(w30, 18, res[1]);
  /* #97: @0 = zeros(12x12,12nz) */
  casadi_clear(w00, 12);
  /* #98: @21 = ones(12x1) */
  casadi_fill(w21, 12, 1.);
  /* #99: (@0[:12] = @21) */
  for (rr=w00+0, cs=w21; rr!=w00+12; rr+=1) *rr = *cs++;
  /* #100: @21 = @0' */
  casadi_trans(w00,casadi_s5, w21, casadi_s5, iw);
  /* #101: output[2][0] = @21 */
  casadi_copy(w21, 12, res[2]);
  /* #102: @26 = zeros(4x12,6nz) */
  casadi_clear(w26, 6);
  /* #103: @31 = ones(4x1) */
  casadi_fill(w31, 4, 1.);
  /* #104: {@7, @6, @12, @8} = vertsplit(@31) */
  w07 = w31[0];
  w06 = w31[1];
  w12 = w31[2];
  w08 = w31[3];
  /* #105: @4 = (@4*@7) */
  w04 *= w07;
  /* #106: @9 = (@9*@4) */
  for (i=0, rr=w09; i<3; ++i) (*rr++) *= w04;
  /* #107: @25 = vertcat(@24, @24, @24, @9, @24, @24, @24, @6, @12, @8) */
  rr=w25;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w08;
  /* #108: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<6; ++i) *rr++ = (- *cs++ );
  /* #109: @32 = @25[:6] */
  for (rr=w32, cs=w25+0; cs!=w25+6; cs+=1) *rr++ = *cs;
  /* #110: (@26[:6] = @32) */
  for (rr=w26+0, cs=w32; rr!=w26+6; rr+=1) *rr = *cs++;
  /* #111: @32 = @26' */
  casadi_trans(w26,casadi_s7, w32, casadi_s6, iw);
  /* #112: output[3][0] = @32 */
  casadi_copy(w32, 6, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    case 4: return casadi_s11;
    case 5: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s3;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 119;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 119*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
