/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) planner_payload_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {44, 1, 1};
static const casadi_int casadi_s3[17] = 
  {16, 1, 0, 13, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* planner_payload_expl_vde_adj:(i0[12],i1[12],i2[4],i3[44])->(o0[16x1,13nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w01, w02, w03, w05, w06, w07, w08, w09, w10, w11, w12;
  casadi_real *w13=w+26, w14, w15;
  const casadi_real *cs, *wr00, *wr04;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, @9, @10} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  wr04 = wr00+3;
  w05 = wr00[6];
  w06 = wr00[7];
  w07 = wr00[8];
  w08 = wr00[9];
  w09 = wr00[10];
  w10 = wr00[11];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][11] */
  w03 = arg[0] ? arg[0][11] : 0;
  /* #6: @2 = (@3*@6) */
  w02  = (w03*w06);
  /* #7: @1 = input[0][10] */
  w01 = arg[0] ? arg[0][10] : 0;
  /* #8: @11 = (@1*@7) */
  w11  = (w01*w07);
  /* #9: @2 = (@2-@11) */
  w02 -= w11;
  /* #10: @11 = -9.09091 */
  w11 = -9.0909090909090917e+00;
  /* #11: @12 = input[2][0] */
  w12 = arg[2] ? arg[2][0] : 0;
  /* #12: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #13: @13 = (@12*@4) */
  for (i=0, rr=w13, cs=wr04; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #14: {@12, @14, @15} = vertsplit(@13) */
  w12 = w13[0];
  w14 = w13[1];
  w15 = w13[2];
  /* #15: @2 = (@2+@12) */
  w02 += w12;
  /* #16: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #17: @2 = input[0][9] */
  w02 = arg[0] ? arg[0][9] : 0;
  /* #18: @12 = (@2*@7) */
  w12  = (w02*w07);
  /* #19: @3 = (@3*@5) */
  w03 *= w05;
  /* #20: @12 = (@12-@3) */
  w12 -= w03;
  /* #21: @12 = (@12+@14) */
  w12 += w14;
  /* #22: output[0][4] = @12 */
  if (res[0]) res[0][4] = w12;
  /* #23: @1 = (@1*@5) */
  w01 *= w05;
  /* #24: @2 = (@2*@6) */
  w02 *= w06;
  /* #25: @1 = (@1-@2) */
  w01 -= w02;
  /* #26: @1 = (@1+@15) */
  w01 += w15;
  /* #27: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  /* #28: @1 = input[0][7] */
  w01 = arg[0] ? arg[0][7] : 0;
  /* #29: @15 = (@1*@7) */
  w15  = (w01*w07);
  /* #30: @2 = input[0][8] */
  w02 = arg[0] ? arg[0][8] : 0;
  /* #31: @12 = (@2*@6) */
  w12  = (w02*w06);
  /* #32: @15 = (@15-@12) */
  w15 -= w12;
  /* #33: output[0][6] = @15 */
  if (res[0]) res[0][6] = w15;
  /* #34: @15 = (@2*@5) */
  w15  = (w02*w05);
  /* #35: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #36: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #37: @15 = (@15-@7) */
  w15 -= w07;
  /* #38: output[0][7] = @15 */
  if (res[0]) res[0][7] = w15;
  /* #39: @6 = (@12*@6) */
  w06  = (w12*w06);
  /* #40: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #41: @6 = (@6-@5) */
  w06 -= w05;
  /* #42: output[0][8] = @6 */
  if (res[0]) res[0][8] = w06;
  /* #43: @13 = vertcat(@12, @1, @2) */
  rr=w13;
  *rr++ = w12;
  *rr++ = w01;
  *rr++ = w02;
  /* #44: @12 = dot(@13, @4) */
  w12 = casadi_dot(3, w13, wr04);
  /* #45: @11 = (@11*@12) */
  w11 *= w12;
  /* #46: output[0][9] = @11 */
  if (res[0]) res[0][9] = w11;
  /* #47: output[0][10] = @8 */
  if (res[0]) res[0][10] = w08;
  /* #48: output[0][11] = @9 */
  if (res[0]) res[0][11] = w09;
  /* #49: output[0][12] = @10 */
  if (res[0]) res[0][12] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void planner_payload_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void planner_payload_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void planner_payload_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int planner_payload_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real planner_payload_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* planner_payload_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* planner_payload_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}

CASADI_SYMBOL_EXPORT int planner_payload_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 31*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
